// Mocks generated by Mockito 5.4.4 from annotations
// in orionhealth_health/test/features/auth/application/bloc/auth_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:local_auth/local_auth.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:orionhealth_health/features/auth/domain/entities/auth_credentials.dart'
    as _i4;
import 'package:orionhealth_health/features/auth/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:orionhealth_health/features/auth/infrastructure/services/biometric_service.dart'
    as _i7;
import 'package:orionhealth_health/features/auth/infrastructure/services/encryption_service.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.AuthCredentials?> getCredentials() => (super.noSuchMethod(
        Invocation.method(
          #getCredentials,
          [],
        ),
        returnValue: _i3.Future<_i4.AuthCredentials?>.value(),
      ) as _i3.Future<_i4.AuthCredentials?>);

  @override
  _i3.Future<void> saveCredentials(_i4.AuthCredentials? credentials) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCredentials,
          [credentials],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCredentials() => (super.noSuchMethod(
        Invocation.method(
          #deleteCredentials,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> hasPinSet() => (super.noSuchMethod(
        Invocation.method(
          #hasPinSet,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> isBiometricsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricsEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i5.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> hashPin(
    String? pin,
    String? salt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hashPin,
          [
            pin,
            salt,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #hashPin,
            [
              pin,
              salt,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> encrypt(
    String? data,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #encrypt,
          [
            data,
            key,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #encrypt,
            [
              data,
              key,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> decrypt(
    String? encryptedData,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #decrypt,
          [
            encryptedData,
            key,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #decrypt,
            [
              encryptedData,
              key,
            ],
          ),
        )),
      ) as _i3.Future<String>);
}

/// A class which mocks [BiometricService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricService extends _i1.Mock implements _i7.BiometricService {
  MockBiometricService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> isBiometricAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricAvailable,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i8.BiometricType>> getAvailableBiometrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableBiometrics,
          [],
        ),
        returnValue:
            _i3.Future<List<_i8.BiometricType>>.value(<_i8.BiometricType>[]),
      ) as _i3.Future<List<_i8.BiometricType>>);

  @override
  _i3.Future<bool> authenticate({required String? localizedReason}) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
          {#localizedReason: localizedReason},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
