include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/src/vector_index_objectbox.dart
    - lib/src/objectbox.g.dart
    - lib/src/models/backend_operation_log.dart
    - lib/src/models/patient_package.dart
