// Mocks generated by Mockito 5.4.4 from annotations
// in orionhealth_health/test/features/auth/infrastructure/services/ble_medical_sharing_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:orionhealth_health/features/auth/infrastructure/services/encryption_service.dart'
    as _i7;
import 'package:orionhealth_health/features/health_sharing/domain/entities/shared_health_package.dart'
    as _i2;
import 'package:orionhealth_health/features/health_sharing/infrastructure/ble_sharing_service.dart'
    as _i5;
import 'package:orionhealth_health/features/ssi/domain/entities/did.dart'
    as _i3;
import 'package:orionhealth_health/features/ssi/domain/entities/verifiable_credential.dart'
    as _i4;
import 'package:orionhealth_health/features/ssi/domain/services/ssi_service.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharingResult_0 extends _i1.SmartFake implements _i2.SharingResult {
  _FakeSharingResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDid_1 extends _i1.SmartFake implements _i3.Did {
  _FakeDid_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifiableCredential_2 extends _i1.SmartFake
    implements _i4.VerifiableCredential {
  _FakeVerifiableCredential_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BleSharingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleSharingService extends _i1.Mock implements _i5.BleSharingService {
  MockBleSharingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i5.BleSharingState> get stateStream => (super.noSuchMethod(
        Invocation.getter(#stateStream),
        returnValue: _i6.Stream<_i5.BleSharingState>.empty(),
      ) as _i6.Stream<_i5.BleSharingState>);

  @override
  _i6.Stream<_i2.SharedHealthPackage> get incomingData => (super.noSuchMethod(
        Invocation.getter(#incomingData),
        returnValue: _i6.Stream<_i2.SharedHealthPackage>.empty(),
      ) as _i6.Stream<_i2.SharedHealthPackage>);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> startAdvertising(String? nodeId) => (super.noSuchMethod(
        Invocation.method(
          #startAdvertising,
          [nodeId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> stopAdvertising() => (super.noSuchMethod(
        Invocation.method(
          #stopAdvertising,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i5.BleDevice>> scanForDevices(
          {Duration? timeout = const Duration(seconds: 15)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanForDevices,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i6.Future<List<_i5.BleDevice>>.value(<_i5.BleDevice>[]),
      ) as _i6.Future<List<_i5.BleDevice>>);

  @override
  _i6.Future<bool> connect(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [deviceId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.SharingResult> sendData(_i2.SharedHealthPackage? package) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendData,
          [package],
        ),
        returnValue: _i6.Future<_i2.SharingResult>.value(_FakeSharingResult_0(
          this,
          Invocation.method(
            #sendData,
            [package],
          ),
        )),
      ) as _i6.Future<_i2.SharingResult>);

  @override
  _i6.Future<_i2.SharedHealthPackage?> receiveData(
          {Duration? timeout = const Duration(seconds: 30)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #receiveData,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i6.Future<_i2.SharedHealthPackage?>.value(),
      ) as _i6.Future<_i2.SharedHealthPackage?>);

  @override
  _i6.Future<void> startMedicalDataStream(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #startMedicalDataStream,
          [deviceId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i7.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> hashPin(
    String? pin,
    String? salt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hashPin,
          [
            pin,
            salt,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #hashPin,
            [
              pin,
              salt,
            ],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i9.Uint8List> encryptBytes(_i9.Uint8List? plainBytes) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptBytes,
          [plainBytes],
        ),
        returnValue: _i6.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
      ) as _i6.Future<_i9.Uint8List>);

  @override
  _i6.Future<_i9.Uint8List> decryptBytes(_i9.Uint8List? encryptedBytes) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptBytes,
          [encryptedBytes],
        ),
        returnValue: _i6.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
      ) as _i6.Future<_i9.Uint8List>);

  @override
  _i6.Future<dynamic> encrypt(
    String? data, [
    String? key,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #encrypt,
          [
            data,
            key,
          ],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<String> decrypt(
    String? encryptedData,
    String? key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #decrypt,
          [
            encryptedData,
            key,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #decrypt,
            [
              encryptedData,
              key,
            ],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> generatePinSalt() => (super.noSuchMethod(
        Invocation.method(
          #generatePinSalt,
          [],
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #generatePinSalt,
            [],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<bool> verifyPin(
    String? pin,
    String? storedHash,
    String? salt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPin,
          [
            pin,
            storedHash,
            salt,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [SsiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSsiService extends _i1.Mock implements _i10.SsiService {
  MockSsiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Did> createDid() => (super.noSuchMethod(
        Invocation.method(
          #createDid,
          [],
        ),
        returnValue: _i6.Future<_i3.Did>.value(_FakeDid_1(
          this,
          Invocation.method(
            #createDid,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Did>);

  @override
  _i6.Future<Map<String, dynamic>?> resolveDid(String? did) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveDid,
          [did],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<_i4.VerifiableCredential> issueCredential({
    required String? schemaId,
    required String? subjectDid,
    required Map<String, dynamic>? claims,
    DateTime? expirationDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #issueCredential,
          [],
          {
            #schemaId: schemaId,
            #subjectDid: subjectDid,
            #claims: claims,
            #expirationDate: expirationDate,
          },
        ),
        returnValue: _i6.Future<_i4.VerifiableCredential>.value(
            _FakeVerifiableCredential_2(
          this,
          Invocation.method(
            #issueCredential,
            [],
            {
              #schemaId: schemaId,
              #subjectDid: subjectDid,
              #claims: claims,
              #expirationDate: expirationDate,
            },
          ),
        )),
      ) as _i6.Future<_i4.VerifiableCredential>);

  @override
  _i6.Future<bool> verifyCredential(_i4.VerifiableCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyCredential,
          [credential],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<Map<String, dynamic>> createPresentation({
    required _i4.VerifiableCredential? credential,
    required List<String>? disclosedFields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPresentation,
          [],
          {
            #credential: credential,
            #disclosedFields: disclosedFields,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> revokeCredential(String? credentialId) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeCredential,
          [credentialId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isAvailable,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}
