dst = r'E:\scripts-python\orionhealth\scripts\final_generator.py'

more_icd10 = """
# ===== ICD-10 Chapters 5-6 (Mental + Nervous) =====
ICD10_MORE = [
("E61","Other nutrient deficiencies","Endocrine",["zinc deficiency","magnesium deficiency"]),
("E63","Other nutritional deficiencies","Endocrine",["nutritional deficiency NOS"]),
("E64","Sequelae of malnutrition","Endocrine",["malnutrition sequelae"]),
("E65","Localized adiposity","Endocrine",["fat distribution disorder"]),
("E66","Obesity","Endocrine",["obesity","obesidad"]),
("E67","Other hyperalimentation","Endocrine",["hypervitaminosis"]),
("E70","Phenylketonuria","Endocrine",["PKU","phenylketonuria"]),
("E71","Branched-chain amino acid disorders","Endocrine",["MSUD","maple syrup urine disease"]),
("E72","Other amino acid metabolism","Endocrine",["homocystinuria"]),
("E73","Lactose intolerance","Endocrine",["lactose intolerance","intolerancia lactosa"]),
("E74","Carbohydrate metabolism","Endocrine",["galactosemia"]),
("E75","Sphingolipid storage","Endocrine",["Gaucher","Niemann-Pick"]),
("E76","Glycosaminoglycan metabolism","Endocrine",["mucopolysaccharidosis"]),
("E78","Lipoprotein metabolism","Endocrine",["hyperlipidemia","familial hypercholesterolemia"]),
("E79","Purine/pyrimidine metabolism","Endocrine",["hyperuricemia","gout","gota"]),
("E80","Porphyrin/bilirubin metabolism","Endocrine",["porphyria","Gilbert syndrome"]),
("E83","Mineral metabolism","Endocrine",["hypercalcemia","hypocalcemia"]),
("E84","Cystic fibrosis","Endocrine",["CF","mucoviscidosis","fibrosis quistica"]),
("E85","Amyloidosis","Endocrine",["amyloid","amiloidosis"]),
("E86","Volume depletion","Endocrine",["dehydration","deshidratacion"]),
("E87","Fluid/electrolyte disorders","Endocrine",["hypernatremia","hyponatremia","hyperkalemia"]),
("E88","Metabolic disorders NEC","Endocrine",["metabolic syndrome","insulin resistance"]),
("E89","Post-procedural endocrine","Endocrine",["post-thyroidectomy hypothyroidism"]),
("E90","Endocrine disorder in disease","Endocrine",["endocrine disorder NEC"]),
("F00","Dementia in Alzheimer","Mental Health",["Alzheimer dementia","demencia Alzheimer"]),
("F01","Vascular dementia","Mental Health",["multi-infarct dementia","demencia vascular"]),
("F03","Unspecified dementia","Mental Health",["dementia NOS","demencia"]),
("F04","Organic amnestic syndrome","Mental Health",["Korsakoff syndrome","amnesia"]),
("F05","Delirium","Mental Health",["delirium","acute confusional state"]),
("F06","Mental disorder due to brain damage","Mental Health",["organic brain syndrome"]),
("F07","Personality/organic mental","Mental Health",["post-concussion syndrome"]),
("F09","Organic mental disorder NOS","Mental Health",["symptomatic psychosis"]),
("F10","Alcohol use disorders","Mental Health",["alcoholism","alcohol use disorder","dependencia alcohol"]),
("F11","Opioid use disorders","Mental Health",["opioid addiction","heroin","opioid use"]),
("F12","Cannabis use disorders","Mental Health",["marijuana use","cannabis addiction"]),
("F13","Sedative use disorders","Mental Health",["benzodiazepine dependence"]),
("F14","Cocaine use disorders","Mental Health",["cocaine addiction","cocaine use"]),
("F15","Stimulant use disorders","Mental Health",["amphetamine","methamphetamine","cocaine"]),
("F16","Hallucinogen use disorders","Mental Health",["LSD","PCP","hallucinogen"]),
("F17","Nicotine dependence","Mental Health",["tobacco use","smoking","nicotine addiction"]),
("F18","Inhalant use disorders","Mental Health",["solvent abuse","inhalant"]),
("F19","Polysubstance use disorders","Mental Health",["multiple drug use","polypharmacy"]),
("F20","Schizophrenia","Mental Health",["schizophrenia","esquizofrenia"]),
("F21","Schizotypal disorder","Mental Health",["schizotypal personality"]),
("F22","Persistent delusional disorder","Mental Health",["delusional disorder","paranoia"]),
("F23","Acute psychotic disorder","Mental Health",["brief psychotic disorder"]),
("F24","Induced delusional disorder","Mental Health",["folie a deux"]),
("F25","Schizoaffective disorders","Mental Health",["schizoaffective","schizoafectivo"]),
("F28","Other psychotic disorders","Mental Health",["psychosis NOS","psicosis"]),
("F29","Unspecified psychosis","Mental Health",["psychosis NOS"]),
("F30","Manic episode","Mental Health",["mania","bipolar mania"]),
("F31","Bipolar affective disorder","Mental Health",["bipolar disorder","manic depression"]),
("F32","Depressive episode","Mental Health",["major depression","depression","depresion"]),
("F33","Recurrent depressive disorder","Mental Health",["MDD","recurrent depression"]),
("F34","Persistent mood disorders","Mental Health",["dysthymia","cyclothymia"]),
("F38","Other mood disorders","Mental Health",["mood disorder NOS"]),
("F39","Unspecified mood disorder","Mental Health",["affective disorder NOS"]),
("F40","Phobic anxiety disorders","Mental Health",["agoraphobia","social phobia"]),
("F41","Other anxiety disorders","Mental Health",["GAD","panic disorder","anxiety"]),
("F42","OCD","Mental Health",["obsessive-compulsive disorder","TOC"]),
("F43","Reaction to severe stress","Mental Health",["PTSD","acute stress reaction","post-traumatic"]),
("F44","Dissociative disorders","Mental Health",["conversion disorder","dissociative identity"]),
("F45","Somatoform disorders","Mental Health",["somatization","hypochondriasis"]),
("F48","Other neurotic disorders","Mental Health",["neurasthenia","depersonalization"]),
("F50","Eating disorders","Mental Health",["anorexia","bulimia","anorexia nervosa"]),
("F51","Nonorganic sleep disorders","Mental Health",["insomnia","hypersomnia","nightmare"]),
("F52","Sexual dysfunction","Mental Health",["erectile dysfunction","impotence"]),
("F53","Puerperal mental disorder","Mental Health",["postpartum depression"]),
("F54","Psychological/behavioral factors","Mental Health",["psychosomatic"]),
("F59","Behavioral syndromes NEC","Mental Health",["behavioral syndrome NOS"]),
("F60","Specific personality disorders","Mental Health",["borderline","narcissistic","antisocial"]),
("F61","Mixed personality disorders","Mental Health",["personality disorder NOS"]),
("F63","Impulse disorders","Mental Health",["kleptomania","pyromania","gambling"]),
("F64","Gender identity disorders","Mental Health",["gender dysphoria","transsexualism"]),
("F65","Paraphilias","Mental Health",["pedophilia","exhibitionism"]),
("F66","Sexual orientation disorders","Mental Health",["sexual maturation disorder"]),
("F68","Other personality disorders","Mental Health",["factitious disorder","Munchausen"]),
("F69","Adult personality disorder NOS","Mental Health",["personality disorder NOS"]),
("F70","Mild mental retardation","Mental Health",["intellectual disability mild","MR"]),
("F71","Moderate mental retardation","Mental Health",["intellectual disability moderate"]),
("F72","Severe mental retardation","Mental Health",["intellectual disability severe"]),
("F73","Profound mental retardation","Mental Health",["intellectual disability profound"]),
("F78","Other mental retardation","Mental Health",["intellectual disability NEC"]),
("F79","Unspecified mental retardation","Mental Health",["intellectual disability NOS"]),
("F80","Speech/language disorders","Mental Health",["speech delay","language delay"]),
("F81","Learning disorders","Mental Health",["dyslexia","dyscalculia","learning disability"]),
("F82","Developmental coordination","Mental Health",["dyspraxia"]),
("F83","Mixed developmental disorder","Mental Health",["developmental delay"]),
("F84","Pervasive developmental disorders","Mental Health",["autism","ASD","Asperger","autismo"]),
("F88","Other developmental disorders","Mental Health",["developmental disorder NOS"]),
("F89","Developmental disorder NOS","Mental Health",["developmental delay NOS"]),
("F90","ADHD","Mental Health",["ADHD","attention deficit","hyperactivity","TDAH"]),
("F91","Conduct disorders","Mental Health",["conduct disorder","behavioral disorder"]),
("F92","Mixed conduct/emotional","Mental Health",["emotional disorder"]),
("F93","Emotional disorders childhood","Mental Health",["separation anxiety"]),
("F94","Social functioning disorders","Mental Health",["selective mutism"]),
("F95","Tic disorders","Mental Health",["Tourette","tourette syndrome","tics"]),
("F98","Other childhood behavioral","Mental Health",["enuresis","encopresis","stuttering"]),
("F99","Mental disorder NOS","Mental Health",["mental illness NOS"]),
("G00","Bacterial meningitis","Neurology",["bacterial meningitis","meningitis bacteriana"]),
("G01","Meningitis in bacterial disease","Neurology",["meningitis"]),
("G02","Meningitis in other diseases","Neurology",["meningitis NEC"]),
("G03","Meningitis due to other causes","Neurology",["meningitis NOS"]),
("G04","Encephalitis/myelitis","Neurology",["encephalitis","meningoencephalitis"]),
("G06","Intracranial abscess","Neurology",["brain abscess","intracranial abscess"]),
("G08","Intracranial phlebitis","Neurology",["cerebral thrombophlebitis"]),
("G09","CNS inflammatory sequelae","Neurology",["post-inflammatory CNS"]),
("G10","Huntington disease","Neurology",["Huntington chorea","Huntington"]),
("G11","Hereditary ataxia","Neurology",["Friedreich ataxia","ataxia","cerebellar ataxia"]),
("G12","Spinal muscular atrophy","Neurology",["SMA","ALS","amyotrophic lateral sclerosis"]),
("G20","Parkinson disease","Neurology",["Parkinson","parkinsonismo","Parkinson disease"]),
("G21","Secondary parkinsonism","Neurology",["drug-induced parkinsonism"]),
("G23","Other basal ganglia diseases","Neurology",["progressive supranuclear palsy","PSP"]),
("G24","Dystonia","Neurology",["dystonia","cervical dystonia","torticollis"]),
("G25","Other extrapyramidal disorders","Neurology",["tremor","restless legs","RLS","blepharospasm"]),
("G30","Alzheimer disease","Neurology",["Alzheimer","Alzheimer disease"]),
("G31","Other degenerative nervous system","Neurology",["frontotemporal dementia","DLB"]),
("G35","Multiple sclerosis","Neurology",["MS","multiple sclerosis","esclerosis multiple"]),
("G36","Other demyelinating CNS","Neurology",["neuromyelitis optica","Devic"]),
("G37","Other demyelinating disease","Neurology",["demyelination NOS"]),
("G40","Epilepsy","Neurology",["seizures","epilepsy","convulsions","epilepsia"]),
("G41","Status epilepticus","Neurology",["status epilepticus","estado epileptico"]),
("G43","Migraine","Neurology",["migraine","migrana","migraine headache"]),
("G44","Other headache syndromes","Neurology",["tension headache","cluster headache"]),
("G45","Transient cerebral ischemic attacks","Neurology",["TIA","transient ischemic attack"]),
("G46","Cerebrovascular syndromes","Neurology",["cerebrovascular syndrome"]),
("G47","Sleep disorders","Neurology",["sleep apnea","insomnia","narcolepsy","sleep disorder"]),
("G50","Trigeminal nerve disorders","Neurology",["trigeminal neuralgia","tic douloureux"]),
("G51","Facial nerve disorders","Neurology",["Bell palsy","facial nerve palsy","paralisis facial"]),
("G54","Nerve root/plexus disorders","Neurology",["cervical radiculopathy","sciatica","hernia discal"]),
("G56","Mononeuropathy upper limb","Neurology",["carpal tunnel syndrome","CTS"]),
("G57","Mononeuropathy lower limb","Neurology",["tarsal tunnel syndrome","peroneal palsy"]),
("G58","Other mononeuropathies","Neurology",["mononeuritis","mononeuropathy NOS"]),
("G60","Hereditary neuropathy","Neurology",["Charcot-Marie-Tooth","CMT"]),
("G61","Inflammatory polyneuropathy","Neurology",["Guillain-Barre","GBS"]),
("G62","Other polyneuropathies","Neurology",["peripheral neuropathy","diabetic neuropathy"]),
("G63","Polyneuropathy in disease","Neurology",["alcoholic neuropathy"]),
("G64","Other peripheral nervous system","Neurology",["peripheral neuropathy NOS"]),
("G70","Myasthenia gravis","Neurology",["MG","myasthenia gravis","miastenia gravis"]),
("G71","Muscular dystrophies","Neurology",["Duchenne MD","muscular dystrophy","Becker MD"]),
("G72","Other myopathies","Neurology",["myopathy","inflammatory myopathy"]),
("G80","Cerebral palsy","Neurology",["CP","cerebral palsy","paralisis cerebral"]),
("G81","Hemiplegia","Neurology",["hemiplegia","hemiparesis"]),
("G82","Paraplegia/tetraplegia","Neurology",["paraplegia","quadriplegia","paraplejia"]),
("G83","Other paralytic syndromes","Neurology",["monoplegia","paresis"]),
("G90","Autonomic nervous system disorders","Neurology",["dysautonomia","POTS"]),
("G91","Hydrocephalus","Neurology",["hydrocephalus","hidrocefalia","NPH"]),
("G92","Toxic encephalopathy","Neurology",["toxic encephalopathy"]),
("G93","Other brain disorders","Neurology",["brain edema","chronic fatigue syndrome","ME/CFS"]),
("G95","Spinal cord diseases","Neurology",["myelopathy","spinal cord compression"]),
("G96","CNS disorders NEC","Neurology",["CNS disorder NOS"]),
("G97","Post-procedural nervous system","Neurology",["post-lumbar puncture headache"]),
("G98","Nervous system disorder NEC","Neurology",["nervous system disorder NOS"]),
]

print("ICD-10 MORE entries: " + str(len(ICD10_MORE)))
"""

with open(dst, 'a', encoding='utf-8') as f:
    f.write(more_icd10)

print("Appended ICD-10 chapters 4-6")
