#!/usr/bin/env python3
"""Append remaining ICD-10, LOINC, RxNorm, SNOMED data + execution to build_all.py"""
import os

script_path = r'E:\scripts-python\orionhealth\scripts\build_all.py'

with open(script_path, 'r') as f:
    content = f.read()

# Find where the ICD10 list ends - it has a ']' at the end of file with truncated E58
# Strip the trailing "] and incomplete E58 entry
# The file ends with: ...\n("E58","Dietary calcium deficiency","Endocrine",["calcium deficiency"]),\n

# Remove the trailing closing bracket and the incomplete E58 line
# The pattern is: the ICD10 list's closing ']' and everything after the last valid entry
# Find the position of the last complete entry
lines = content.splitlines()
# Find the last line that is just ']' - the list closer
close_line = None
for i in range(len(lines)-1, -1, -1):
    if lines[i].strip() == ']':
        close_line = i
        break

if close_line:
    print(f'Found closing ] at line {close_line+1}')
    # Keep everything up to (but not including) the closing ]
    new_content = '\n'.join(lines[:close_line]) + ',\n'
else:
    new_content = content.rstrip() + ',\n'

# Now append all remaining ICD-10 data
appendage = r'''
("E61","Other nutrient deficiencies","Endocrine",["zinc deficiency","magnesium deficiency"]),
("E63","Other nutritional deficiencies","Endocrine",["nutritional deficiency NOS"]),
("E64","Sequelae of malnutrition","Endocrine",["malnutrition sequelae"]),
("E65","Localized adiposity","Endocrine",["fat distribution disorder"]),
("E66","Obesity","Endocrine",["obesity","obesidad"]),
("E67","Other hyperalimentation","Endocrine",["hypervitaminosis"]),
("E70","Phenylketonuria","Endocrine",["PKU","phenylketonuria"]),
("E71","Branched-chain amino acid disorders","Endocrine",["MSUD","maple syrup urine disease"]),
("E72","Other amino acid metabolism","Endocrine",["homocystinuria"]),
("E73","Lactose intolerance","Endocrine",["lactose intolerance","intolerancia lactosa"]),
("E74","Carbohydrate metabolism","Endocrine",["galactosemia"]),
("E75","Sphingolipid storage","Endocrine",["Gaucher","Niemann-Pick"]),
("E76","Glycosaminoglycan metabolism","Endocrine",["mucopolysaccharidosis"]),
("E78","Lipoprotein metabolism","Endocrine",["hyperlipidemia","familial hypercholesterolemia"]),
("E79","Purine/pyrimidine metabolism","Endocrine",["hyperuricemia","gout","gota"]),
("E80","Porphyrin/bilirubin metabolism","Endocrine",["porphyria","Gilbert syndrome"]),
("E83","Mineral metabolism","Endocrine",["hypercalcemia","hypocalcemia"]),
("E84","Cystic fibrosis","Endocrine",["CF","mucoviscidosis","fibrosis quistica"]),
("E85","Amyloidosis","Endocrine",["amyloid","amiloidosis"]),
("E86","Volume depletion","Endocrine",["dehydration","deshidratacion"]),
("E87","Fluid/electrolyte disorders","Endocrine",["hypernatremia","hyponatremia","hyperkalemia"]),
("E88","Metabolic disorders NEC","Endocrine",["metabolic syndrome","insulin resistance"]),
("E89","Post-procedural endocrine","Endocrine",["post-thyroidectomy hypothyroidism"]),
("E90","Endocrine disorder in disease","Endocrine",["endocrine disorder NEC"]),

("F00","Dementia in Alzheimer","Mental Health",["Alzheimer dementia","demencia Alzheimer"]),
("F01","Vascular dementia","Mental Health",["multi-infarct dementia","demencia vascular"]),
("F03","Unspecified dementia","Mental Health",["dementia NOS","demencia"]),
("F04","Organic amnestic syndrome","Mental Health",["Korsakoff syndrome","amnesia"]),
("F05","Delirium","Mental Health",["delirium","acute confusional state"]),
("F06","Mental disorder due to brain damage","Mental Health",["organic brain syndrome"]),
("F07","Personality/organic mental","Mental Health",["post-concussion syndrome"]),
("F09","Organic mental disorder NOS","Mental Health",["symptomatic psychosis"]),
("F10","Alcohol use disorders","Mental Health",["alcoholism","alcohol use disorder","dependencia alcohol"]),
("F11","Opioid use disorders","Mental Health",["opioid addiction","heroin","opioid use"]),
("F12","Cannabis use disorders","Mental Health",["marijuana use","cannabis addiction"]),
("F13","Sedative use disorders","Mental Health",["benzodiazepine dependence"]),
("F14","Cocaine use disorders","Mental Health",["cocaine addiction","cocaine use"]),
("F15","Stimulant use disorders","Mental Health",["amphetamine","methamphetamine","cocaine"]),
("F16","Hallucinogen use disorders","Mental Health",["LSD","PCP","hallucinogen"]),
("F17","Nicotine dependence","Mental Health",["tobacco use","smoking","nicotine addiction"]),
("F18","Inhalant use disorders","Mental Health",["solvent abuse","inhalant"]),
("F19","Polysubstance use disorders","Mental Health",["multiple drug use","polypharmacy"]),
("F20","Schizophrenia","Mental Health",["schizophrenia","esquizofrenia"]),
("F21","Schizotypal disorder","Mental Health",["schizotypal personality"]),
("F22","Persistent delusional disorder","Mental Health",["delusional disorder","paranoia"]),
("F23","Acute psychotic disorder","Mental Health",["brief psychotic disorder"]),
("F24","Induced delusional disorder","Mental Health",["folie a deux"]),
("F25","Schizoaffective disorders","Mental Health",["schizoaffective","schizoafectivo"]),
("F28","Other psychotic disorders","Mental Health",["psychosis NOS","psicosis"]),
("F29","Unspecified psychosis","Mental Health",["psychosis NOS"]),
("F30","Manic episode","Mental Health",["mania","bipolar mania"]),
("F31","Bipolar affective disorder","Mental Health",["bipolar disorder","manic depression"]),
("F32","Depressive episode","Mental Health",["major depression","depression","depresion"]),
("F33","Recurrent depressive disorder","Mental Health",["MDD","recurrent depression"]),
("F34","Persistent mood disorders","Mental Health",["dysthymia","cyclothymia"]),
("F38","Other mood disorders","Mental Health",["mood disorder NOS"]),
("F39","Unspecified mood disorder","Mental Health",["affective disorder NOS"]),
("F40","Phobic anxiety disorders","Mental Health",["agoraphobia","social phobia"]),
("F41","Other anxiety disorders","Mental Health",["GAD","panic disorder","anxiety"]),
("F42","OCD","Mental Health",["obsessive-compulsive disorder","TOC"]),
("F43","Reaction to severe stress","Mental Health",["PTSD","acute stress reaction","post-traumatic"]),
("F44","Dissociative disorders","Mental Health",["conversion disorder","dissociative identity"]),
("F45","Somatoform disorders","Mental Health",["somatization","hypochondriasis"]),
("F48","Other neurotic disorders","Mental Health",["neurasthenia","depersonalization"]),
("F50","Eating disorders","Mental Health",["anorexia","bulimia","anorexia nervosa"]),
("F51","Nonorganic sleep disorders","Mental Health",["insomnia","hypersomnia","nightmare"]),
("F52","Sexual dysfunction","Mental Health",["erectile dysfunction","impotence"]),
("F53","Puerperal mental disorder","Mental Health",["postpartum depression"]),
("F54","Psychological/behavioral factors","Mental Health",["psychosomatic"]),
("F59","Behavioral syndromes NEC","Mental Health",["behavioral syndrome NOS"]),
("F60","Specific personality disorders","Mental Health",["borderline","narcissistic","antisocial"]),
("F61","Mixed personality disorders","Mental Health",["personality disorder NOS"]),
("F63","Impulse disorders","Mental Health",["kleptomania","pyromania","gambling"]),
("F64","Gender identity disorders","Mental Health",["gender dysphoria","transsexualism"]),
("F65","Paraphilias","Mental Health",["pedophilia","exhibitionism"]),
("F66","Sexual orientation disorders","Mental Health",["sexual maturation disorder"]),
("F68","Other personality disorders","Mental Health",["factitious disorder","Munchausen"]),
("F69","Adult personality disorder NOS","Mental Health",["personality disorder NOS"]),
("F70","Mild mental retardation","Mental Health",["intellectual disability mild","MR"]),
("F71","Moderate mental retardation","Mental Health",["intellectual disability moderate"]),
("F72","Severe mental retardation","Mental Health",["intellectual disability severe"]),
("F73","Profound mental retardation","Mental Health",["intellectual disability profound"]),
("F78","Other mental retardation","Mental Health",["intellectual disability NEC"]),
("F79","Unspecified mental retardation","Mental Health",["intellectual disability NOS"]),
("F80","Speech/language disorders","Mental Health",["speech delay","language delay"]),
("F81","Learning disorders","Mental Health",["dyslexia","dyscalculia","learning disability"]),
("F82","Developmental coordination","Mental Health",["dyspraxia"]),
("F83","Mixed developmental disorder","Mental Health",["developmental delay"]),
("F84","Pervasive developmental disorders","Mental Health",["autism","ASD","Asperger","autismo"]),
("F88","Other developmental disorders","Mental Health",["developmental disorder NOS"]),
("F89","Developmental disorder NOS","Mental Health",["developmental delay NOS"]),
("F90","ADHD","Mental Health",["ADHD","attention deficit","hyperactivity","TDAH"]),
("F91","Conduct disorders","Mental Health",["conduct disorder","behavioral disorder"]),
("F92","Mixed conduct/emotional","Mental Health",["emotional disorder"]),
("F93","Emotional disorders childhood","Mental Health",["separation anxiety"]),
("F94","Social functioning disorders","Mental Health",["selective mutism"]),
("F95","Tic disorders","Mental Health",["Tourette","tourette syndrome","tics"]),
("F98","Other childhood behavioral","Mental Health",["enuresis","encopresis","stuttering"]),
("F99","Mental disorder NOS","Mental Health",["mental illness NOS"]),

("G00","Bacterial meningitis","Neurology",["bacterial meningitis","meningitis bacteriana"]),
("G01","Meningitis in bacterial disease","Neurology",["meningitis"]),
("G02","Meningitis in other diseases","Neurology",["meningitis NEC"]),
("G03","Meningitis due to other causes","Neurology",["meningitis NOS"]),
("G04","Encephalitis/myelitis","Neurology",["encephalitis","meningoencephalitis"]),
("G06","Intracranial abscess","Neurology",["brain abscess","intracranial abscess"]),
("G08","Intracranial phlebitis","Neurology",["cerebral thrombophlebitis"]),
("G09","CNS inflammatory sequelae","Neurology",["post-inflammatory CNS"]),
("G10","Huntington disease","Neurology",["Huntington chorea","Huntington"]),
("G11","Hereditary ataxia","Neurology",["Friedreich ataxia","ataxia","cerebellar ataxia"]),
("G12","Spinal muscular atrophy","Neurology",["SMA","ALS","amyotrophic lateral sclerosis"]),
("G20","Parkinson disease","Neurology",["Parkinson","parkinsonismo","Parkinson disease"]),
("G21","Secondary parkinsonism","Neurology",["drug-induced parkinsonism"]),
("G23","Other basal ganglia diseases","Neurology",["progressive supranuclear palsy","PSP"]),
("G24","Dystonia","Neurology",["dystonia","cervical dystonia","torticollis"]),
("G25","Other extrapyramidal disorders","Neurology",["tremor","restless legs","RLS","blepharospasm"]),
("G30","Alzheimer disease","Neurology",["Alzheimer","Alzheimer disease"]),
("G31","Other degenerative nervous system","Neurology",["frontotemporal dementia","DLB"]),
("G35","Multiple sclerosis","Neurology",["MS","multiple sclerosis","esclerosis multiple"]),
("G36","Other demyelinating CNS","Neurology",["neuromyelitis optica","Devic"]),
("G37","Other demyelinating disease","Neurology",["demyelination NOS"]),
("G40","Epilepsy","Neurology",["seizures","epilepsy","convulsions","epilepsia"]),
("G41","Status epilepticus","Neurology",["status epilepticus","estado epileptico"]),
("G43","Migraine","Neurology",["migraine","migrana","migraine headache"]),
("G44","Other headache syndromes","Neurology",["tension headache","cluster headache"]),
("G45","Transient cerebral ischemic attacks","Neurology",["TIA","transient ischemic attack"]),
("G46","Cerebrovascular syndromes","Neurology",["cerebrovascular syndrome"]),
("G47","Sleep disorders","Neurology",["sleep apnea","insomnia","narcolepsy","sleep disorder"]),
("G50","Trigeminal nerve disorders","Neurology",["trigeminal neuralgia","tic douloureux"]),
("G51","Facial nerve disorders","Neurology",["Bell palsy","facial nerve palsy","paralisis facial"]),
("G54","Nerve root/plexus disorders","Neurology",["cervical radiculopathy","sciatica","hernia discal"]),
("G56","Mononeuropathy upper limb","Neurology",["carpal tunnel syndrome","CTS"]),
("G57","Mononeuropathy lower limb","Neurology",["tarsal tunnel syndrome","peroneal palsy"]),
("G58","Other mononeuropathies","Neurology",["mononeuritis","mononeuropathy NOS"]),
("G60","Hereditary neuropathy","Neurology",["Charcot-Marie-Tooth","CMT"]),
("G61","Inflammatory polyneuropathy","Neurology",["Guillain-Barre","GBS"]),
("G62","Other polyneuropathies","Neurology",["peripheral neuropathy","diabetic neuropathy"]),
("G63","Polyneuropathy in disease","Neurology",["alcoholic neuropathy"]),
("G64","Other peripheral nervous system","Neurology",["peripheral neuropathy NOS"]),
("G70","Myasthenia gravis","Neurology",["MG","myasthenia gravis","miastenia gravis"]),
("G71","Muscular dystrophies","Neurology",["Duchenne MD","muscular dystrophy","Becker MD"]),
("G72","Other myopathies","Neurology",["myopathy","inflammatory myopathy"]),
("G80","Cerebral palsy","Neurology",["CP","cerebral palsy","paralisis cerebral"]),
("G81","Hemiplegia","Neurology",["hemiplegia","hemiparesis"]),
("G82","Paraplegia/tetraplegia","Neurology",["paraplegia","quadriplegia","paraplejia"]),
("G83","Other paralytic syndromes","Neurology",["monoplegia","paresis"]),
("G90","Autonomic nervous system disorders","Neurology",["dysautonomia","POTS"]),
("G91","Hydrocephalus","Neurology",["hydrocephalus","hidrocefalia","NPH"]),
("G92","Toxic encephalopathy","Neurology",["toxic encephalopathy"]),
("G93","Other brain disorders","Neurology",["brain edema","chronic fatigue syndrome","ME/CFS"]),
("G95","Spinal cord diseases","Neurology",["myelopathy","spinal cord compression"]),
("G96","CNS disorders NEC","Neurology",["CNS disorder NOS"]),
("G97","Post-procedural nervous system","Neurology",["post-lumbar puncture headache"]),
("G98","Nervous system disorder NEC","Neurology",["nervous system disorder NOS"]),
]

# ====== LOINC DATA ======
LOINC = [
("718-7","Hemoglobin [Mass/volume] in Blood","Hematology",["Hgb","HB","Hemoglobina"]),
("4544-3","Hematocrit [Volume fraction] of Blood","Hematology",["HCT","Hematocrito"]),
("6690-2","Leukocytes [#/volume] in Blood","Hematology",["WBC","White blood cells","Leucocitos"]),
("777-3","Platelets [#/volume] in Blood","Hematology",["PLT","Plaquetas","Thrombocytes"]),
("789-8","Erythrocytes [#/volume] in Blood","Hematology",["RBC","Red blood cells","Eritrocitos"]),
("785-6","MCV [Volume] in Blood","Hematology",["Mean corpuscular volume","VCM"]),
("787-2","MCH [Mass] in Blood","Hematology",["Mean corpuscular hemoglobin","HCM"]),
("786-4","MCHC [Mass/volume] in Blood","Hematology",["MCHC","CHCM"]),
("778-1","RDW [Ratio] in Blood","Hematology",["RDW","ADE","Red cell distribution width"]),
("26464-8","Leukocytes [#/volume] in Blood by Automated","Hematology",["WBC automated","Leucocitos automatico"]),
("5905-5","Neutrophils/100 leukocytes in Blood","Hematology",["Neutrophil percent","Neutrofilos"]),
("26499-4","Lymphocytes/100 leukocytes in Blood","Hematology",["Lymphocyte percent","Linfocitos"]),
("5903-0","Monocytes/100 leukocytes in Blood","Hematology",["Monocyte percent","Monocitos"]),
("26485-3","Basophils/100 leukocytes in Blood","Hematology",["Basophil percent","Basofilos"]),
("26477-0","Eosinophils/100 leukocytes in Blood","Hematology",["Eosinophil percent","Eosinofilos"]),
("2345-7","Glucose [Mass/volume] in Serum/Plasma","Chemistry",["Glucosa","Blood sugar","Glucemia"]),
("4548-4","HbA1c/Hemoglobin.total in Blood","Chemistry",["A1C","Hemoglobin A1c","Hemoglobina glicosilada"]),
("2160-0","Creatinine [Mass/volume] in Serum/Plasma","Chemistry",["Cre","Creatinina","Creat"]),
("3094-0","Urea nitrogen [Mass/volume] in Serum/Plasma","Chemistry",["BUN","Blood urea nitrogen","Urea"]),
("2951-2","Sodium [Moles/volume] in Serum/Plasma","Chemistry",["Na","Sodio"]),
("2823-3","Potassium [Moles/volume] in Serum/Plasma","Chemistry",["K","Potasio","Kalium"]),
("2075-0","Chloride [Moles/volume] in Serum/Plasma","Chemistry",["Cl","Cloro","Chloride"]),
("2028-9","Carbon dioxide [Moles/volume] in Serum/Plasma","Chemistry",["CO2","Bicarbonate","Bicarbonato"]),
("1920-8","Aspartate aminotransferase [Enzymatic activity]","Chemistry",["AST","SGOT","TGO","Aspartato aminotransferasa"]),
("1742-6","Alanine aminotransferase [Enzymatic activity]","Chemistry",["ALT","SGPT","TGP","Alanina aminotransferasa"]),
("6768-6","Alkaline phosphatase [Enzymatic activity]","Chemistry",["ALP","Alk Phos","Fosfatasa alcalina"]),
("2324-2","GGT [Enzymatic activity]","Chemistry",["GGT","Gamma GT","Gammaglutamil transferasa"]),
("1975-2","Bilirubin.total [Mass/volume]","Chemistry",["Total bilirubin","Bilirrubina total"]),
("1968-7","Bilirubin.direct [Mass/volume]","Chemistry",["Direct bilirubin","Bilirrubina directa"]),
("3097-3","Uric acid [Mass/volume] in Serum/Plasma","Chemistry",["Urate","Acido urico","Uricemia"]),
("2093-3","Cholesterol [Mass/volume] in Serum/Plasma","Lipids",["Total cholesterol","Colesterol total"]),
("2571-8","Triglycerides [Mass/volume] in Serum/Plasma","Lipids",["Trigliceridos","TG"]),
("13457-7","LDL Cholesterol [Mass/volume]","Lipids",["LDL","Colesterol malo","LDL-C"]),
("2085-9","HDL Cholesterol [Mass/volume]","Lipids",["HDL","Colesterol bueno","HDL-C"]),
("38483-4","Creatinine [Mass/volume] in Blood","Renal",["Creatinine blood","Creatinina en sangre"]),
("35667-4","EGFR [Volume/Time] in Serum/Plasma","Renal",["Estimated GFR","TFGe","Filtracion glomerular"]),
("14959-1","Microalbumin [Mass/volume] in Urine","Renal",["Urine albumin","Microalbuminuria"]),
("2888-6","Protein [Mass/volume] in Urine","Renal",["Urine protein","Proteinuria","Proteinas en orina"]),
("5802-4","Creatinine [Mass/volume] in Urine","Renal",["Urine creatinine","Creatinina en orina"]),
("3016-3","TSH [Units/volume] in Serum/Plasma","Thyroid",["Thyrotropin","TSH","Tirotropina"]),
("3026-2","Free T4 [Mass/volume] in Serum/Plasma","Thyroid",["Free thyroxine","T4 libre"]),
("3051-0","T3 Uptake [Ratio] in Serum","Thyroid",["T3 uptake","Captacion T3"]),
("2276-4","Ferritin [Mass/volume] in Serum/Plasma","Iron",["Ferritina","Ferritin"]),
("2508-8","Iron [Mass/volume] in Serum/Plasma","Iron",["Serum iron","Hierro serico"]),
("30350-3","Transferrin [Mass/volume] in Serum/Plasma","Iron",["Transferrina","TIBC"]),
("2500-5","TIBC [Mass/volume] in Serum/Plasma","Iron",["Total iron binding capacity","CTFH"]),
("6301-6","INR in Blood","Coagulation",["INR","International normalized ratio"]),
("5902-2","Prothrombin time [Time] in Blood","Coagulation",["PT","Protime","Tiempo protrombina"]),
("19123-9","aPTT [Time] in Blood","Coagulation",["PTT","TTPa","Partial thromboplastin"]),
("48065-7","D-dimer DDU [Mass/volume]","Coagulation",["D-dimer","Dimero D"]),
("3255-7","Fibrinogen [Mass/volume]","Coagulation",["Fibrinogen","Fibrinogeno"]),
("2132-9","Vitamin B12 [Mass/volume] in Serum/Plasma","Vitamins",["Cobalamin","B12","Vitamina B12"]),
("1824-9","25-Hydroxyvitamin D [Mass/volume] in Serum/Plasma","Vitamins",["Vitamin D","25-OH D","Vitamina D"]),
("14733-2","Folate [Mass/volume] in Serum/Plasma","Vitamins",["Folic acid","Acido folico","Folato"]),
("8867-4","Heart rate [Rate]","Vitals",["Pulse","Heart rate","Frecuencia cardiaca"]),
("2710-2","Oxygen saturation [Fraction] in Arterial blood","Vitals",["SpO2","Saturacion oxigeno"]),
("8480-6","Systolic blood pressure [Pressure]","Vitals",["SBP","Presion sistolica"]),
("8462-4","Diastolic blood pressure [Pressure]","Vitals",["DBP","Presion diastolica"]),
("8310-7","Body temperature [Temperature]","Vitals",["Temperature","Temperatura corporal"]),
("1988-8","C-reactive protein [Mass/volume] in Serum","Inflammation",["CRP","Proteina C reactiva","PCR"]),
("33914-3","Procalcitonin [Mass/volume] in Serum","Inflammation",["PCT","Procalcitonina"]),
("34714-6","Troponin I.cardiac [Mass/volume] in Serum","Cardiac",["Troponin","cTnI","Troponina I"]),
("33204-9","B-type natriuretic peptide [Mass/volume] in Serum","Cardiac",["BNP","Peptido natriuretico"]),
("107567-8","NT-proBNP [Mass/volume] in Serum","Cardiac",["ProBNP","NT-proBNP"]),
("57698-2","Hemoglobin A1c [IFCC] in Blood","Diabetes",["HbA1c IFCC","Hemoglobina glicosilada IFCC"]),
]

# ====== RXNORM DATA ======
RXNORM = [
("6809","Metformin","Antidiabetic",["Glucophage","Diaformin","Metformina"]),
("5487","Glipizide","Antidiabetic",["Glucotrol","Glipizida"]),
("29046","Lisinopril","ACE Inhibitor",["Prinivil","Zestril","Lisinoprila"]),
("52175","Losartan","ARB",["Cozaar","Losartan"]),
("17767","Amlodipine","Calcium Channel Blocker",["Norvasc","Amlodipina"]),
("83367","Atorvastatin","Statin",["Lipitor","Atorvastatina"]),
("321167","Rosuvastatin","Statin",["Crestor","Rosuvastatina"]),
("855332","Warfarin","Anticoagulant",["Coumadin","Warfarina","Marevan"]),
("1191","Aspirin","Antiplatelet",["ASA","Acetylsalicylic acid","Aspirina"]),
("333965","Clopidogrel","Antiplatelet",["Plavix","Clopidogrela"]),
("2360","Simvastatin","Statin",["Zocor","Simvastatina"]),
("263187","Carvedilol","Beta Blocker",["Coreg","Carvedilol"]),
("33157","Metoprolol Tartrate","Beta Blocker",["Lopressor","Metoprolol"]),
("8859","Metoprolol Succinate","Beta Blocker",["Toprol XL","Metoprolol ER"]),
("314076","Atenolol","Beta Blocker",["Tenormin","Atenolol"]),
("161","HCTZ","Thiazide Diuretic",["Hydrochlorothiazide","Hidroclorotiazida"]),
("316155","Furosemide","Loop Diuretic",["Lasix","Furosemida"]),
("324047","Spironolactone","Diuretic",["Aldactone","Espironolactona"]),
("33254","Digoxin","Cardiac Glycoside",["Lanoxin","Digoxina"]),
("219247","Nitroglycerin","Vasodilator",["Nitrostat","Nitroglicerina"]),
("146565","Apixaban","DOAC",["Eliquis","Apixaban"]),
("67312","Rivaroxaban","DOAC",["Xarelto","Rivaroxaban"]),
("30805","Dabigatran","DOAC",["Pradaxa","Dabigatran"]),
("236666","Enalapril","ACE Inhibitor",["Vasotec","Enalaprila"]),
("24559","Ramipril","ACE Inhibitor",["Altace","Ramiprila"]),
("60873","Valsartan","ARB",["Diovan","Valsartan"]),
("371534","Telmisartan","ARB",["Micardis","Telmisartan"]),
("403134","Irbesartan","ARB",["Avapro","Irbesartan"]),
("8667","Levothyroxine","Thyroid Hormone",["Synthroid","Levotiroxina","Euthyrox"]),
("36567","Sertraline","SSRI",["Zoloft","Sertralina"]),
("312938","Fluoxetine","SSRI",["Prozac","Fluoxetina"]),
("32937","Alprazolam","Benzodiazepine",["Xanax","Alprazolam"]),
("1720977","Escitalopram","SSRI",["Lexapro","Escitalopram"]),
("24588","Citalopram","SSRI",["Celexa","Citalopram"]),
("10733","Paroxetine","SSRI",["Paxil","Paroxetina"]),
("4460","Duloxetine","SNRI",["Cymbalta","Duloxetina"]),
("42234","Venlafaxine","SNRI",["Effexor","Venlafaxina"]),
("5448","Bupropion","NDRI",["Wellbutrin","Bupropion"]),
("203152","Mirtazapine","NaSSA",["Remeron","Mirtazapina"]),
("2412","Clonazepam","Benzodiazepine",["Klonopin","Clonazepam"]),
("30131","Lorazepam","Benzodiazepine",["Ativan","Lorazepam"]),
("6676","Diazepam","Benzodiazepine",["Valium","Diazepam"]),
("38053","Olanzapine","Atypical Antipsychotic",["Zyprexa","Olanzapina"]),
("1309","Risperidone","Atypical Antipsychotic",["Risperdal","Risperidona"]),
("69231","Quetiapine","Atypical Antipsychotic",["Seroquel","Quetiapina"]),
("61429","Aripiprazole","Atypical Antipsychotic",["Abilify","Aripiprazol"]),
("5025","Haloperidol","Antipsychotic",["Haldol","Haloperidol"]),
("3922","Lithium","Mood Stabilizer",["Lithobid","Litio","Lithium carbonate"]),
("56760","Valproic Acid","Anticonvulsant",["Depakote","Valproate","Acido valproico"]),
("3075","Carbamazepine","Anticonvulsant",["Tegretol","Carbamazepina"]),
("200045","Lamotrigine","Anticonvulsant",["Lamictal","Lamotrigina"]),
("17199","Gabapentin","Anticonvulsant",["Neurontin","Gabapentina"]),
("2168","Pregabalin","Anticonvulsant",["Lyrica","Pregabalina"]),
("37422","Levetiracetam","Anticonvulsant",["Keppra","Levetiracetam"]),
("8853","Phenytoin","Anticonvulsant",["Dilantin","Fenitoina"]),
("35619","Topiramate","Anticonvulsant",["Topamax","Topiramato"]),
("2682","Amitriptyline","TCA",["Elavil","Amitriptilina"]),
("12909","Methylphenidate","Stimulant",["Ritalin","Metilfenidato","Concerta"]),
("26722","Dextroamphetamine","Stimulant",["Adderall","Dextraanfetamina"]),
("5640","Ibuprofen","NSAID",["Motrin","Advil","Ibuprofeno"]),
("8123","Naproxen","NSAID",["Aleve","Naproxeno","Naprosyn"]),
("4095","Celecoxib","COX-2 Inhibitor",["Celebrex","Celecoxib"]),
("5722","Prednisone","Corticosteroid",["Prednisona","Deltasone"]),
("11141","Methylprednisolone","Corticosteroid",["Medrol","Solu-Medrol","Metilprednisolona"]),
("3033","Dexamethasone","Corticosteroid",["Decadron","Dexametasona"]),
("825","Morphine","Opioid",["MS Contin","Morfina","MST"]),
("7034","Oxycodone","Opioid",["OxyContin","Oxycodona","Oxicodona"]),
("20827","Hydromorphone","Opioid",["Dilaudid","Hidromorfona"]),
("6360","Codeine","Opioid",["Codeina","Methylmorphine"]),
("8163","Fentanyl","Opioid",["Duragesic","Fentanilo"]),
("5838","Tramadol","Opioid",["Ultram","Tramadol"]),
("31005","Methadone","Opioid",["Methadose","Metadona","Dolophine"]),
("259","Buprenorphine","Opioid Agonist",["Subutex","Suboxone","Buprenorfina"]),
("16155","Naloxone","Opioid Antagonist",["Narcan","Naloxona"]),
("435","Albuterol","Beta Agonist",["Ventolin","Salbutamol","Proair"]),
("197530","Fluticasone","Inhaled Corticosteroid",["Flovent","Fluticasona","Advair"]),
("73720","Budesonide","Inhaled Corticosteroid",["Pulmicort","Budesonida"]),
("201250","Cetirizine","Antihistamine",["Zyrtec","Cetirizina"]),
("26225","Loratadine","Antihistamine",["Claritin","Loratadina"]),
("2519","Diphenhydramine","Antihistamine",["Benadryl","Difenhidramina"]),
("6537","Fexofenadine","Antihistamine",["Allegra","Fexofenadina"]),
("1200","Montelukast","Leukotriene Antagonist",["Singulair","Montelukast"]),
("53147,"Tiotropium","Anticholinergic Inhaler",["Spiriva","Tiotropio"]),
("83020","Ipratropium","Anticholinergic Inhaler",["Atrovent","Ipratropio"]),
("7646","Omeprazole","PPI",["Prilosec","Omeprazol"]),
("40790","Pantoprazole","PPI",["Protonix","Pantoprazol"]),
("5605","Esomeprazole","PPI",["Nexium","Esomeprazol"]),
("34892","Lansoprazole","PPI",["Prevacid","Lansoprazol"]),
("8050","Ranitidine","H2 Blocker",["Zantac","Ranitidina"]),
("421254","Famotidine","H2 Blocker",["Pepcid","Famotidina"]),
("1292","Ondansetron","Antiemetic",["Zofran","Ondansetron"]),
("24885","Metoclopramide","Prokinetic",["Reglan","Metoclopramida"]),
("16837","Amoxicillin","Penicillin Antibiotic",["Amoxil","Amoxicilina"]),
("11234","Cephalexin","Cephalosporin",["Keflex","Cefalexina"]),
("4377","Ciprofloxacin","Fluoroquinolone",["Cipro","Ciprofloxacina"]),
("4981","Levofloxacin","Fluoroquinolone",["Levaquin","Levofloxacino"]),
("7207","Azithromycin","Macrolide",["Zithromax","Azitromicina"]),
("5372","Erythromycin","Macrolide",["Eryc","Eritromicina"]),
("14314","Clarithromycin","Macrolide",["Biaxin","Claritromicina"]),
("7819","Doxycycline","Tetracycline",["Vibramycin","Doxiciclina"]),
("13679","Metronidazole","Nitroimidazole",["Flagyl","Metronidazol"]),
("3260","Clindamycin","Lincosamide",["Cleocin","Clindamicina"]),
("24958","Sulfamethoxazole/Trimethoprim","Sulfonamide",["Bactrim","Septra","TMP-SMX"]),
("134965","Nitrofurantoin","Urinary Antibiotic",["Macrodantin","Nitrofurantoina"]),
("11355","Vancomycin","Glycopeptide",["Vancocin","Vancomicina"]),
("18765","Prednisolone","Corticosteroid",["Prednisolona","Orapred"]),
("9233","Hydrocortisone","Corticosteroid",["Cortisol","Hidrocortisona"]),
("36309","Allopurinol","Xanthine Oxidase Inhibitor",["Zyloprim","Alopurinol"]),
("1881","Colchicine","Antigout",["Colcrys","Colchicina"]),
("2152","Bisoprolol","Beta Blocker",["Zebeta","Bisoprolol"]),
("21842","Propranolol","Beta Blocker",["Inderal","Propranolol"]),
("28422","Diltiazem","Calcium Channel Blocker",["Cardizem","Diltiazem"]),
("3589","Nifedipine","Calcium Channel Blocker",["Procardia","Nifedipina"]),
("221391","Verapamil","Calcium Channel Blocker",["Calan","Verapamilo","Verapamil"]),
("23899","Clonidine","Alpha Agonist",["Catapres","Clonidina"]),
("3653","Prazosin","Alpha Blocker",["Minipress","Prazosina"]),
("8910","Doxazosin","Alpha Blocker",["Cardura","Doxazosina"]),
("2454","Terazosin","Alpha Blocker",["Hytrin","Terazosina"]),
("9471","Finasteride","5-Alpha Reductase Inhibitor",["Proscar","Finasterida","Propecia"]),
("6817","Tamsulosin","Alpha Blocker",["Flomax","Tamsulosina"]),
("32549","Sildenafil","PDE5 Inhibitor",["Viagra","Sildenafilo","Revatio"]),
("16231","Tadalafil","PDE5 Inhibitor",["Cialis","Tadalafilo"]),
("5046","Vardenafil","PDE5 Inhibitor",["Levitra","Vardenafilo"]),
("875","Insulin Glargine","Insulin",["Lantus","Insulina glargina","Toujeo"]),
("200141","Insulin Lispro","Insulin",["Humalog","Insulina lispro"]),
("54693","Insulin Aspart","Insulin",["Novolog","Insulina aspart"]),
("16068","Insulin Detemir","Insulin",["Levemir","Insulina detemir"]),
("226","Insulin Regular","Insulin",["Humulin R","Novolin R","Insulina regular"]),
("18552","Insulin NPH","Insulin",["Humulin N","Novolin N","Insulina NPH"]),
("3622","Pioglitazone","Thiazolidinedione",["Actos","Pioglitazona"]),
("3616","Rosiglitazone","Thiazolidinedione",["Avandia","Rosiglitazona"]),
("24560","Sitagliptin","DPP-4 Inhibitor",["Januvia","Sitagliptina"]),
("36981","Saxagliptin","DPP-4 Inhibitor",["Onglyza","Saxagliptina"]),
("12578","Linagliptin","DPP-4 Inhibitor",["Tradjenta","Linagliptina"]),
("466138","Empagliflozin","SGLT2 Inhibitor",["Jardiance","Empagliflozina"]),
("157949","Dapagliflozin","SGLT2 Inhibitor",["Farxiga","Dapagliflozina"]),
("17053","Canagliflozin","SGLT2 Inhibitor",["Invokana","Canagliflozina"]),
("8435","Liraglutide","GLP-1 Agonist",["Victoza","Saxenda","Liraglutida"]),
("159325","Semaglutide","GLP-1 Agonist",["Ozempic","Wegovy","Rybelsus","Semaglutida"]),
("248688","Dulaglutide","GLP-1 Agonist",["Trulicity","Dulaglutida"]),
("5939","Acetaminophen","Analgesic",["Tylenol","Paracetamol","Acetaminofeno"]),
("5051","Cyclobenzaprine","Muscle Relaxant",["Flexeril","Ciclobenzaprina"]),
("510","Baclofen","Muscle Relaxant",["Lioresal","Baclofeno"]),
("6937","Methocarbamol","Muscle Relaxant",["Robaxin","Metocarbamol"]),
("621","Tizanidine","Muscle Relaxant",["Zanaflex","Tizanidina"]),
("519","Zolpidem","Sedative",["Ambien","Zolpidem"]),
("28883","Eszopiclone","Sedative",["Lunesta","Eszopiclona"]),
("2585","Temazepam","Benzodiazepine",["Restoril","Temazepam"]),
("1437","Midazolam","Benzodiazepine",["Versed","Midazolam"]),
]
print(f'RxNorm entries: {len(RXNORM)}')

# ====== SNOMED CT DATA ======
SNOMED = [
("73211009","Diabetes mellitus type 2","Endocrine Disorder",["T2DM","type 2 diabetes","diabetes tipo 2"]),
("46635009","Diabetes mellitus type 1","Endocrine Disorder",["T1DM","type 1 diabetes","diabetes tipo 1"]),
("44054006","Type 2 diabetes with foot ulcer","Endocrine Disorder",["diabetic foot","pie diabetico"]),
("59621000","Essential hypertension","Cardiovascular",["hypertension","high BP","hipertension"]),
("399304003","Sustained hypertension","Cardiovascular",["chronic hypertension","hipertension cronica"]),
("53741008","Congestive heart failure","Cardiovascular",["CHF","heart failure","insuficiencia cardiaca"]),
("414545008","Ischemic heart disease","Cardiovascular",["coronary disease","cardiopatia isquemica"]),
("194828000","Angina pectoris","Cardiovascular",["angina","chest pain"]),
("57054005","Acute myocardial infarction","Cardiovascular",["heart attack","MI","infarto"]),
("195967001","Asthma","Respiratory",["bronchial asthma","asma"]),
("13645005","COPD","Respiratory",["chronic obstructive pulmonary disease","EPOC"]),
("233604007","Pneumonia","Respiratory",["lung infection","pneumonia"]),
("10509002","Acute bronchitis","Respiratory",["bronchitis","bronquitis"]),
("49727002","Chronic sinusitis","Respiratory",["sinus infection","sinusitis cronica"]),
("31387002","Fracture of forearm","Musculoskeletal",["radial fracture","broken arm"]),
("71620000","Fracture of femur","Musculoskeletal",["hip fracture","femur fracture"]),
("15773000","Torus fracture of radius","Musculoskeletal",["buckle fracture","greenstick"]),
("239873009","Osteoarthritis of knee","Musculoskeletal",["knee OA","artrosis rodilla"]),
("396275006","Osteoarthritis of hip","Musculoskeletal",["hip OA","coxarthrosis"]),
("201820007","Rheumatoid arthritis","Musculoskeletal",["RA","artritis reumatoide"]),
("26929004","Alzheimer disease","Neurologic",["Alzheimer dementia","EA","Alzheimer"]),
("54150009","Multiple sclerosis","Neurologic",["MS","esclerosis multiple"]),
("56727007","Cerebral palsy","Neurologic",["spastic CP","paralisis cerebral"]),
("230207008","Migraine without aura","Neurologic",["common migraine","migrana"]),
("7323001","Migraine with aura","Neurologic",["classic migraine","migrana con aura"]),
("84387000","Parkinson disease","Neurologic",["Parkinson","parkinsonismo"]),
("19298008","Epilepsy","Neurologic",["seizure disorder","convulsive disorder"]),
("416330003","Cerebrovascular accident","Neurologic",["stroke","CVA","ACV"]),
("230690007","Major depressive disorder","Mental Health",["MDD","depression","depresion mayor"]),
("13746004","Bipolar disorder","Mental Health",["manic depression","trastorno bipolar"]),
("58214004","Schizophrenia","Mental Health",["schizophrenia","esquizofrenia"]),
("191736004","Generalized anxiety disorder","Mental Health",["GAD","anxiety disorder","ansiedad"]),
("81308009","Post-traumatic stress disorder","Mental Health",["PTSD","trauma","estres post-traumatico"]),
("274951002","Acute upper respiratory infection","Infectious",["URI","common cold","resfriado"]),
("6142004","Influenza","Infectious",["flu","gripe","influenza"]),
("18624000","Urinary tract infection","Infectious",["UTI","cystitis","ITU"]),
("40748000","Chronic kidney disease","Renal",["CKD","renal failure","ERC"]),
("90688005","Acute renal failure","Renal",["AKI","acute kidney injury","IRA"]),
("46481004","Benign prostatic hyperplasia","Urologic",["BPH","prostate enlargement","HBP"]),
("72892002","Normal pregnancy","OB/GYN",["pregnancy","gestation","embarazo"]),
("363171000","Preeclampsia","OB/GYN",["pregnancy-induced hypertension"]),
("35489007","Depressive disorder in childbirth","OB/GYN",["postpartum depression"]),
("289184003","Anemia in pregnancy","OB/GYN",["anemia gestacional"]),
("3424008","Iron deficiency anemia","Hematologic",["microcytic anemia","anemia ferropenica"]),
("127295002","Acute appendicitis","Gastrointestinal",["appendicitis","apendicitis"]),
("266571003","Diverticulitis","Gastrointestinal",["diverticular disease"]),
("3738000","Hyperlipidemia","Metabolic",["high cholesterol","hiperlipidemia"]),
("440344006","Gastroesophageal reflux disease","Gastrointestinal",["GERD","reflux","reflujo"]),
("19660004","Gastritis","Gastrointestinal",["gastric inflammation","gastritis"]),
("89765005","Peptic ulcer disease","Gastrointestinal",["duodenal ulcer","gastric ulcer","ulcera"]),
("14760008","Benign neoplasm of skin","Dermatologic",["skin growth","nevus","lunar"]),
("254137008","Contact dermatitis","Dermatologic",["allergic rash","contact dermatitis"]),
("200936003","Atopic dermatitis","Dermatologic",["eczema","dermatitis atopica"]),
("924000","Early stage pressure ulcer","Dermatologic",["bed sore","pressure injury"]),
("34014006","Viral hepatitis type C","Infectious",["Hep C","hepatitis C","HCV"]),
("50711007","Viral hepatitis type B","Infectious",["Hep B","hepatitis B","HBV"]),
("18802000","Chronic hepatitis C","Infectious",["chronic HCV"]),
("722444007","COVID-19","Infectious",["coronavirus","SARS-CoV-2","COVID"]),
]
print(f'SNOMED entries: {len(SNOMED)}')

# =====================
# EXECUTION
# =====================
print('Building ICD-10...')
r1 = build('icd10', ICD10)
save('icd10', r1)

print('Building LOINC...')
r2 = build('loinc', LOINC)
save('loinc', r2)

print('Building RxNorm...')
r3 = build('rxnorm', RXNORM)
save('rxnorm', r3)

print('Building SNOMED CT...')
r4 = build('snomed', SNOMED)
save('snomed', r4)

print('Done!')
