#!/usr/bin/env python3
"""Generate all 4 medical standards JSON files for OrionHealth."""
import json, os, re

OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "medical-standards")
os.makedirs(OUT_DIR, exist_ok=True)

META = {
    "icd10": {"standard":"ICD-10","version":"2024-1","lastUpdated":"2026-05-02","source":"WHO","sourceUrl":"https://icd.who.int/browse10/2019/en","license":"WHO ICD-10 License","wikipediaBase":"https://en.wikipedia.org/wiki/List_of_ICD-10_codes","totalCount":0},
    "loinc": {"standard":"LOINC","version":"2.74","lastUpdated":"2026-03-01","source":"Regenstrief Institute","sourceUrl":"https://loinc.org/","license":"LOINC License","wikipediaBase":"https://en.wikipedia.org/wiki/LOINC","totalCount":0},
    "rxnorm": {"standard":"RxNorm","version":"2024-03-04","lastUpdated":"2026-05-02","source":"NLM RxNorm","sourceUrl":"https://www.nlm.nih.gov/research/umls/rxnorm/","license":"UMLS License","wikipediaBase":"","totalCount":0},
    "snomed": {"standard":"SNOMED CT","version":"2024-07-31","lastUpdated":"2026-05-02","source":"SNOMED International","sourceUrl":"https://www.snomed.org/","license":"SNOMED CT License Required","wikipediaBase":"","totalCount":0},
}

def build(key, entries):
    meta = META[key].copy()
    data = []
    for e in entries:
        code, name, cat, terms = e[0], e[1], e[2], e[3]
        obj = {"code": code, "displayName": name, "category": cat}
        if isinstance(terms, list):
            obj["searchTerms"] = terms
        elif isinstance(terms, str):
            obj["searchTerms"] = [t.strip() for t in terms.split(",")]
        data.append(obj)
    meta["totalCount"] = len(data)
    return {"metadata": meta, "data": data}

def save(key, result):
    path = os.path.join(OUT_DIR, f"{key}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)
    size = os.path.getsize(path)
    print(f"Written {key}.json: {result['metadata']['totalCount']} entries, {size:,} bytes, valid JSON: {os.path.getsize(path) > 100}")
    return size

# ===== DATA =====

ICD10 = [
("A00","Cholera","Infectious",["cholera","Vibrio cholerae","colera"]),
("A01","Typhoid and paratyphoid fevers","Infectious",["typhoid","Salmonella typhi","fiebre tifoidea"]),
("A02","Other salmonella infections","Infectious",["salmonellosis","Salmonella"]),
("A03","Shigellosis","Infectious",["shigellosis","bacillary dysentery","disenteria bacilar"]),
("A04","Other bacterial intestinal infections","Infectious",["E. coli enteritis","Campylobacter"]),
("A05","Other bacterial foodborne intoxications","Infectious",["food poisoning","botulism"]),
("A06","Amebiasis","Infectious",["amebiasis","Entamoeba histolytica"]),
("A07","Other protozoal intestinal diseases","Infectious",["giardiasis","cryptosporidiosis"]),
("A08","Viral intestinal infections","Infectious",["rotavirus","norovirus","gastroenteritis viral"]),
("A09","Infectious gastroenteritis/colitis","Infectious",["infectious diarrhea","gastroenteritis"]),
("A15","Respiratory tuberculosis","Infectious",["pulmonary TB","TBC"]),
("A16","Respiratory TB not confirmed","Infectious",["tuberculosis","TB"]),
("A17","TB of nervous system","Infectious",["tuberculous meningitis","meningitis tuberculosa"]),
("A18","TB of other organs","Infectious",["extrapulmonary TB","TB lymphadenitis"]),
("A19","Miliary tuberculosis","Infectious",["disseminated TB","tuberculosis miliar"]),
("A20","Plague","Infectious",["Yersinia pestis","bubonic plague","peste"]),
("A21","Tularemia","Infectious",["rabbit fever","Francisella tularensis"]),
("A22","Anthrax","Infectious",["Bacillus anthracis","carbunco"]),
("A23","Brucellosis","Infectious",["undulant fever","Brucella","fiebre de Malta"]),
("A27","Leptospirosis","Infectious",["Weil disease","Leptospira"]),
("A30","Leprosy [Hansen disease]","Infectious",["Hansen disease","leprosy","lepra"]),
("A31","Other mycobacterial infection","Infectious",["NTM","Mycobacterium avium"]),
("A32","Listeriosis","Infectious",["Listeria monocytogenes"]),
("A35","Other tetanus","Infectious",["tetanus","lockjaw","tetanos"]),
("A36","Diphtheria","Infectious",["Corynebacterium diphtheriae","difteria"]),
("A37","Whooping cough","Infectious",["pertussis","tos ferina","Bordetella"]),
("A38","Scarlet fever","Infectious",["scarlatina","fiebre escarlata"]),
("A39","Meningococcal infection","Infectious",["meningococcal meningitis","Neisseria"]),
("A40","Streptococcal sepsis","Infectious",["Group B strep","Streptococcus"]),
("A41","Other sepsis","Infectious",["septicemia","sepsis bacteriana"]),
("A46","Erysipelas","Infectious",["erysipelas","erisipela"]),
("A49","Bacterial infection unspecified","Infectious",["bacterial infection NOS"]),
("A50","Congenital syphilis","Infectious",["congenital syphilis","Treponema pallidum"]),
("A51","Early syphilis","Infectious",["primary syphilis","chancre"]),
("A52","Late syphilis","Infectious",["tertiary syphilis","neurosyphilis"]),
("A53","Syphilis unspecified","Infectious",["syphilis","sifilis"]),
("A54","Gonococcal infection","Infectious",["gonorrhea","gonorrea"]),
("A55","Chlamydial lymphogranuloma","Infectious",["LGV","lymphogranuloma venereum"]),
("A56","Other chlamydial STD","Infectious",["Chlamydia trachomatis","clamidia"]),
("A59","Trichomoniasis","Infectious",["Trichomonas vaginalis","tricomoniasis"]),
("A60","Anogenital herpesviral infection","Infectious",["genital herpes","HSV-2","herpes genital"]),
("A64","Unspecified STD","Infectious",["STD NOS","ETS","ITS"]),
("A69","Other spirochetal infections","Infectious",["Lyme disease","Borrelia burgdorferi"]),
("A71","Trachoma","Infectious",["trachoma"]),
("A75","Typhus fever","Infectious",["Rickettsia prowazekii","typhus","tifo"]),
("A77","Spotted fever [tick-borne]","Infectious",["Rocky Mountain spotted fever"]),
("A78","Q fever","Infectious",["Coxiella burnetii"]),
("A79","Other rickettsioses","Infectious",["ehrlichiosis","anaplasmosis"]),
("A80","Acute poliomyelitis","Infectious",["polio","poliomielitis"]),
("A81","Atypical virus CNS infections","Infectious",["CJD","prion disease","Kuru"]),
("A82","Rabies","Infectious",["hydrophobia","lyssavirus","rabia"]),
("A83","Mosquito-borne viral encephalitis","Infectious",["Japanese encephalitis","West Nile"]),
("A84","Tick-borne viral encephalitis","Infectious",["TBE","FSME"]),
("A86","Unspecified viral encephalitis","Infectious",["viral encephalitis","encefalitis viral"]),
("A87","Viral meningitis","Infectious",["aseptic meningitis","meningitis viral"]),
("A90","Dengue fever","Infectious",["dengue","breakbone fever","dengue clasico"]),
("A91","Dengue hemorrhagic fever","Infectious",["DHF","dengue hemorragico"]),
("A92","Other mosquito-borne viral fevers","Infectious",["Chikungunya","Zika virus"]),
("A95","Yellow fever","Infectious",["yellow jack","fiebre amarilla"]),
("A96","Arenaviral hemorrhagic fever","Infectious",["Lassa fever","Junin virus"]),
("A98","Other viral hemorrhagic fevers","Infectious",["Ebola","Marburg","Crimean-Congo HF"]),
("A99","Viral hemorrhagic fever unspecified","Infectious",["Viral HF NOS","VHF"]),
("B00","Herpesviral infections","Infectious",["HSV","cold sores","herpes labial"]),
("B01","Varicella [chickenpox]","Infectious",["chickenpox","varicela"]),
("B02","Zoster [herpes zoster]","Infectious",["shingles","culebrilla"]),
("B05","Measles","Infectious",["rubeola","measles","sarampion"]),
("B06","Rubella","Infectious",["German measles","rubeola"]),
("B07","Viral warts","Infectious",["HPV warts","verruca","verrugas"]),
("B08","Other viral skin infections","Infectious",["Molluscum contagiosum"]),
("B15","Acute hepatitis A","Infectious",["HAV","hepatitis A"]),
("B16","Acute hepatitis B","Infectious",["HBV","hepatitis B"]),
("B17","Other acute viral hepatitis","Infectious",["hepatitis C","HCV","hepatitis E"]),
("B18","Chronic viral hepatitis","Infectious",["chronic hepatitis B","chronic hepatitis C"]),
("B19","Unspecified viral hepatitis","Infectious",["viral hepatitis NOS"]),
("B20","HIV disease","Infectious",["AIDS","HIV","VIH","SIDA"]),
("B24","Unspecified HIV infection","Infectious",["HIV infection NOS"]),
("B25","Cytomegaloviral disease","Infectious",["CMV","cytomegalovirus","citomegalovirus"]),
("B26","Mumps","Infectious",["parotitis","parotiditis","paperas"]),
("B27","Infectious mononucleosis","Infectious",["EBV","Epstein-Barr","mono"]),
("B30","Viral conjunctivitis","Infectious",["pink eye","conjunctivitis viral"]),
("B34","Viral infection unspecified","Infectious",["viral infection NOS"]),
("B35","Dermatophytosis","Infectious",["ringworm","tinea","tina"]),
("B36","Other superficial mycoses","Infectious",["pityriasis versicolor"]),
("B37","Candidiasis","Infectious",["yeast infection","Candida","thrush","candidiasis"]),
("B38","Coccidioidomycosis","Infectious",["Valley fever","Coccidioides"]),
("B39","Histoplasmosis","Infectious",["Histoplasma capsulatum"]),
("B40","Blastomycosis","Infectious",["Blastomyces dermatitidis"]),
("B44","Aspergillosis","Infectious",["Aspergillus","ABPA","aspergilosis"]),
("B45","Cryptococcosis","Infectious",["Cryptococcus neoformans"]),
("B46","Zygomycosis","Infectious",["mucormycosis"]),
("B48","Other mycoses NEC","Infectious",["Pneumocystis jirovecii","PCP"]),
("B49","Unspecified mycosis","Infectious",["fungal infection NOS","micosis"]),
("B50","Plasmodium falciparum malaria","Infectious",["cerebral malaria","paludismo"]),
("B51","Plasmodium vivax malaria","Infectious",["vivax malaria"]),
("B52","Plasmodium malariae malaria","Infectious",["quartan malaria"]),
("B53","Other malaria","Infectious",["mixed malaria","malaria mixta"]),
("B54","Unspecified malaria","Infectious",["malaria NOS","paludismo"]),
("B55","Leishmaniasis","Infectious",["kala-azar","visceral leishmaniasis"]),
("B56","African trypanosomiasis","Infectious",["sleeping sickness","Trypanosoma"]),
("B57","Chagas disease","Infectious",["American trypanosomiasis","Trypanosoma cruzi"]),
("B58","Toxoplasmosis","Infectious",["Toxoplasma gondii","toxoplasmosis"]),
("B59","Pneumocystosis","Infectious",["Pneumocystis pneumonia","PCP"]),
("B65","Schistosomiasis","Infectious",["bilharzia","Schistosoma"]),
("B67","Echinococcosis","Infectious",["hydatid disease","quiste hidatidico"]),
("B68","Taeniasis","Infectious",["tapeworm","Taenia","teniasis"]),
("B69","Cysticercosis","Infectious",["neurocysticercosis","cisticercosis"]),
("B73","Onchocerciasis","Infectious",["river blindness","Onchocerca"]),
("B74","Filariasis","Infectious",["lymphatic filariasis","elephantiasis"]),
("B75","Trichinellosis","Infectious",["trichinosis","triquinosis"]),
("B76","Hookworm diseases","Infectious",["ancylostomiasis"]),
("B77","Ascariasis","Infectious",["roundworm","Ascaris lumbricoides"]),
("B78","Strongyloidiasis","Infectious",["Strongyloides stercoralis"]),
("B80","Enterobiasis","Infectious",["pinworm","oxiuriasis"]),
("B82","Unspecified intestinal parasitism","Infectious",["parasitosis intestinal"]),
("B85","Pediculosis and phthiriasis","Infectious",["lice","head lice","piojos"]),
("B86","Scabies","Infectious",["Sarcoptes scabiei","scabies","sarna"]),
("B89","Unspecified parasitic disease","Infectious",["parasitosis NOS"]),
("B90","Sequelae of tuberculosis","Infectious",["TB sequelae"]),
("B91","Sequelae of poliomyelitis","Infectious",["post-polio syndrome"]),
("B94","Sequelae of infectious diseases","Infectious",["post-infectious sequelae"]),
("B95","Strep/staph as cause","Infectious",["Strep","Staph aureus"]),
("B96","Other bacterial agents","Infectious",["E. coli","Pseudomonas","H. influenzae"]),
("B97","Viral agents as cause","Infectious",["RSV","Adenovirus","Influenza"]),
("B99","Other infectious diseases","Infectious",["infectious disease NOS"]),
("C00","Malig neoplasm lip","Neoplasms",["lip cancer","cancer de labio"]),
("C01","Malig neoplasm base of tongue","Neoplasms",["tongue cancer"]),
("C02","Malig neoplasm tongue NEC","Neoplasms",["oral tongue cancer"]),
("C03","Malig neoplasm gum","Neoplasms",["gingival cancer"]),
("C04","Malig neoplasm floor of mouth","Neoplasms",["oral cancer"]),
("C05","Malig neoplasm palate","Neoplasms",["palatal cancer"]),
("C06","Malig neoplasm mouth NEC","Neoplasms",["buccal mucosa cancer"]),
("C07","Malig neoplasm parotid","Neoplasms",["parotid cancer"]),
("C08","Malig neoplasm salivary NEC","Neoplasms",["salivary gland cancer"]),
("C09","Malig neoplasm tonsil","Neoplasms",["tonsillar cancer"]),
("C10","Malig neoplasm oropharynx","Neoplasms",["oropharyngeal cancer"]),
("C11","Malig neoplasm nasopharynx","Neoplasms",["nasopharyngeal cancer","NPC"]),
("C12","Malig neoplasm pyriform sinus","Neoplasms",["hypopharyngeal cancer"]),
("C13","Malig neoplasm hypopharynx","Neoplasms",["hypopharyngeal cancer"]),
("C14","Mal neoplasm lip/oral/pharynx","Neoplasms",["head and neck cancer"]),
("C15","Malig neoplasm esophagus","Neoplasms",["esophageal cancer"]),
("C16","Malig neoplasm stomach","Neoplasms",["gastric cancer","stomach cancer"]),
("C17","Malig neoplasm small intestine","Neoplasms",["small bowel cancer"]),
("C18","Malig neoplasm colon","Neoplasms",["colon cancer","colorectal cancer"]),
("C19","Malig neoplasm rectosigmoid","Neoplasms",["rectosigmoid cancer"]),
("C20","Malig neoplasm rectum","Neoplasms",["rectal cancer"]),
("C21","Malig neoplasm anus","Neoplasms",["anal cancer"]),
("C22","Malig neoplasm liver","Neoplasms",["hepatocellular carcinoma","HCC"]),
("C23","Malig neoplasm gallbladder","Neoplasms",["gallbladder cancer"]),
("C24","Malig neoplasm biliary tract","Neoplasms",["cholangiocarcinoma"]),
("C25","Malig neoplasm pancreas","Neoplasms",["pancreatic cancer"]),
("C30","Malig neoplasm nasal cavity","Neoplasms",["nasal cancer"]),
("C31","Malig neoplasm sinuses","Neoplasms",["sinus cancer"]),
("C32","Malig neoplasm larynx","Neoplasms",["laryngeal cancer","cancer de laringe"]),
("C33","Malig neoplasm trachea","Neoplasms",["tracheal cancer"]),
("C34","Malig neoplasm bronchus/lung","Neoplasms",["lung cancer","NSCLC","SCLC"]),
("C37","Malig neoplasm thymus","Neoplasms",["thymoma","thymic cancer"]),
("C38","Mal neoplasm heart/mediastinum","Neoplasms",["mediastinal cancer"]),
("C40","Malig neoplasm bone/cartilage","Neoplasms",["bone cancer","osteosarcoma"]),
("C41","Malig neoplasm bone NEC","Neoplasms",["chondrosarcoma"]),
("C43","Malignant melanoma skin","Neoplasms",["melanoma","melanoma maligno"]),
("C44","Other malig skin neoplasm","Neoplasms",["BCC","SCC skin"]),
("C45","Mesothelioma","Neoplasms",["malignant mesothelioma","pleural"]),
("C46","Kaposi sarcoma","Neoplasms",["KS","Kaposi"]),
("C47","Mal neoplasm peripheral nerves","Neoplasms",["neurofibrosarcoma"]),
("C48","Mal neoplasm retroperitoneum","Neoplasms",["retroperitoneal cancer"]),
("C49","Mal neoplasm connective/soft tissue","Neoplasms",["sarcoma","soft tissue sarcoma"]),
("C50","Malig neoplasm breast","Neoplasms",["breast cancer","cancer de mama"]),
("C51","Malig neoplasm vulva","Neoplasms",["vulvar cancer"]),
("C52","Malig neoplasm vagina","Neoplasms",["vaginal cancer"]),
("C53","Malig neoplasm cervix","Neoplasms",["cervical cancer"]),
("C54","Malig neoplasm corpus uteri","Neoplasms",["endometrial cancer"]),
("C55","Malig neoplasm uterus NOS","Neoplasms",["uterine cancer NOS"]),
("C56","Malig neoplasm ovary","Neoplasms",["ovarian cancer"]),
("C57","Mal neoplasm female genital NEC","Neoplasms",["fallopian tube cancer"]),
("C58","Malig neoplasm placenta","Neoplasms",["choriocarcinoma"]),
("C60","Malig neoplasm penis","Neoplasms",["penile cancer"]),
("C61","Malig neoplasm prostate","Neoplasms",["prostate cancer"]),
("C62","Malig neoplasm testis","Neoplasms",["testicular cancer","germ cell"]),
("C63","Mal neoplasm male genital NEC","Neoplasms",["male genital cancer NOS"]),
("C64","Malig neoplasm kidney","Neoplasms",["renal cell carcinoma","RCC"]),
("C65","Malig neoplasm renal pelvis","Neoplasms",["transitional cell renal"]),
("C66","Malig neoplasm ureter","Neoplasms",["ureteral cancer"]),
("C67","Malig neoplasm bladder","Neoplasms",["bladder cancer","urothelial"]),
("C68","Mal neoplasm urinary NEC","Neoplasms",["urethral cancer"]),
("C69","Malig neoplasm eye","Neoplasms",["ocular cancer","retinoblastoma"]),
("C70","Malig neoplasm meninges","Neoplasms",["malignant meningioma"]),
("C71","Malig neoplasm brain","Neoplasms",["brain cancer","glioma","glioblastoma"]),
("C72","Mal neoplasm spinal cord/CNS","Neoplasms",["spinal cord tumor"]),
("C73","Malig neoplasm thyroid","Neoplasms",["thyroid cancer","papillary thyroid"]),
("C74","Malig neoplasm adrenal","Neoplasms",["adrenal cancer","pheochromocytoma"]),
("C75","Mal neoplasm endocrine NEC","Neoplasms",["pituitary tumor"]),
("C76","Mal neoplasm ill-defined","Neoplasms",["metastatic NOS"]),
("C77","Secondary neoplasm lymph nodes","Neoplasms",["lymph node metastasis"]),
("C78","Secondary neoplasm resp/digest","Neoplasms",["metastatic lung","metastatic liver"]),
("C79","Secondary neoplasm other sites","Neoplasms",["bone metastasis","brain metastasis"]),
("C80","Mal neoplasm unspecified","Neoplasms",["cancer NOS"]),
("C81","Hodgkin lymphoma","Neoplasms",["Hodgkin disease","HL"]),
("C82","Follicular lymphoma","Neoplasms",["FL","follicular lymphoma"]),
("C83","Non-follicular lymphoma","Neoplasms",["DLBCL","diffuse large B-cell"]),
("C84","Mature T/NK-cell lymphomas","Neoplasms",["T-cell lymphoma"]),
("C85","Other NHL types","Neoplasms",["non-Hodgkin lymphoma NOS"]),
("C88","Malig immunoproliferative","Neoplasms",["Waldenstrom macroglobulinemia"]),
("C90","Multiple myeloma","Neoplasms",["myeloma","plasma cell myeloma"]),
("C91","Lymphoid leukemia","Neoplasms",["ALL","CLL"]),
("C92","Myeloid leukemia","Neoplasms",["AML","CML"]),
("C93","Monocytic leukemia","Neoplasms",["AMoL"]),
("C95","Leukemia unspecified","Neoplasms",["leukemia NOS"]),
("D00","CIS oral/esophagus/stomach","Neoplasms",["CIS oral","carcinoma in situ"]),
("D01","CIS other digestive","Neoplasms",["CIS digestive"]),
("D02","CIS respiratory","Neoplasms",["CIS lung"]),
("D03","Melanoma in situ","Neoplasms",["melanoma in situ"]),
("D04","CIS skin","Neoplasms",["SCC in situ","Bowen disease"]),
("D05","CIS breast","Neoplasms",["DCIS","LCIS","breast CIS"]),
("D06","CIS cervix","Neoplasms",["CIN III","cervical CIS"]),
("D09","CIS other sites","Neoplasms",["CIS NOS"]),
("D10","Benign neoplasm mouth/pharynx","Neoplasms",["benign oral tumor"]),
("D11","Benign neoplasm salivary","Neoplasms",["salivary adenoma"]),
("D12","Benign neoplasm colon/rectum","Neoplasms",["colonic polyp","adenomatous polyp"]),
("D13","Benign neoplasm other digestive","Neoplasms",["benign gastric tumor"]),
("D14","Benign neoplasm respiratory","Neoplasms",["lung hamartoma"]),
("D15","Benign neoplasm intrathoracic","Neoplasms",["mediastinal adenoma"]),
("D16","Benign neoplasm bone/cartilage","Neoplasms",["osteoma"]),
("D17","Benign lipomatous neoplasm","Neoplasms",["lipoma"]),
("D18","Hemangioma","Neoplasms",["hemangioma","angioma"]),
("D19","Benign mesothelial tissue","Neoplasms",["mesothelial cyst"]),
("D20","Benign peritoneum","Neoplasms",["retroperitoneal cyst"]),
("D21","Other benign connective tissue","Neoplasms",["fibroma","desmoid"]),
("D22","Melanocytic nevi","Neoplasms",["nevus","mole","lunar"]),
("D23","Other benign skin neoplasms","Neoplasms",["seborrheic keratosis","skin tag"]),
("D24","Benign neoplasm breast","Neoplasms",["fibroadenoma"]),
("D25","Leiomyoma of uterus","Neoplasms",["fibroids","miomas","uterine fibroids"]),
("D26","Other benign uterine","Neoplasms",["endometrial polyp"]),
("D27","Benign neoplasm ovary","Neoplasms",["ovarian cystadenoma"]),
("D28","Benign neoplasm female genital NEC","Neoplasms",["vaginal adenosis"]),
("D29","Benign neoplasm male genital","Neoplasms",["BPH","benign prostatic hyperplasia"]),
("D30","Benign neoplasm urinary","Neoplasms",["renal angiomyolipoma"]),
("D31","Benign neoplasm eye","Neoplasms",["choroidal nevus"]),
("D32","Benign neoplasm meninges","Neoplasms",["meningioma"]),
("D33","Benign neoplasm brain/CNS","Neoplasms",["benign brain tumor"]),
("D34","Benign neoplasm thyroid","Neoplasms",["thyroid adenoma","thyroid nodule"]),
("D35","Benign neoplasm endocrine NEC","Neoplasms",["pituitary adenoma"]),
("D36","Benign neoplasm unspecified","Neoplasms",["benign neoplasm NOS"]),
("D37","Neoplasm uncertain oral/digestive","Neoplasms",["gastric GIST"]),
("D38","Neoplasm uncertain respiratory","Neoplasms",["lung neoplasm uncertain"]),
("D39","Neoplasm uncertain female genital","Neoplasms",["ovarian borderline tumor"]),
("D40","Neoplasm uncertain male genital","Neoplasms",["prostate PIN"]),
("D41","Neoplasm uncertain urinary","Neoplasms",["bladder neoplasm uncertain"]),
("D42","Neoplasm uncertain meninges","Neoplasms",["atypical meningioma"]),
("D43","Neoplasm uncertain brain/CNS","Neoplasms",["low grade glioma"]),
("D44","Neoplasm uncertain endocrine","Neoplasms",["adrenal incidentaloma"]),
("D45","Polycythemia vera","Neoplasms",["PV","polycythemia vera"]),
("D46","Myelodysplastic syndromes","Neoplasms",["MDS","preleukemia"]),
("D47","Other lymphoid uncertain","Neoplasms",["MGUS","monoclonal gammopathy"]),
("D48","Neoplasm uncertain other","Neoplasms",["neoplasm uncertain NOS"]),
("D50","Iron deficiency anemia","Blood & Immune",["IDA","anemia ferropenica"]),
("D51","B12 deficiency anemia","Blood & Immune",["pernicious anemia"]),
("D52","Folate deficiency anemia","Blood & Immune",["folic acid deficiency"]),
("D53","Other nutritional anemias","Blood & Immune",["nutritional anemia NOS"]),
("D55","Anemia from enzyme disorders","Blood & Immune",["G6PD deficiency anemia"]),
("D56","Thalassemia","Blood & Immune",["beta thalassemia","Cooley anemia","talasemia"]),
("D57","Sickle cell disorders","Blood & Immune",["SCD","sickle cell disease","anemia falciforme"]),
("D58","Other hereditary hemolytic","Blood & Immune",["hereditary spherocytosis"]),
("D59","Acquired hemolytic anemia","Blood & Immune",["AIHA","autoimmune hemolytic"]),
("D60","Acquired pure red cell aplasia","Blood & Immune",["PRCA"]),
("D61","Aplastic anemias","Blood & Immune",["aplastic anemia","anemia aplasica"]),
("D62","Acute posthemorrhagic anemia","Blood & Immune",["acute blood loss anemia"]),
("D63","Anemia in chronic diseases","Blood & Immune",["anemia of chronic disease"]),
("D64","Other anemias","Blood & Immune",["anemia NOS"]),
("D65","DIC","Blood & Immune",["disseminated intravascular coagulation"]),
("D66","Factor VIII deficiency","Blood & Immune",["hemophilia A"]),
("D67","Factor IX deficiency","Blood & Immune",["hemophilia B"]),
("D68","Other coagulation defects","Blood & Immune",["Von Willebrand disease","VWD"]),
("D69","Purpura and hemorrhagic","Blood & Immune",["ITP","immune thrombocytopenia"]),
("D70","Neutropenia","Blood & Immune",["agranulocytosis"]),
("D71","Neutrophil disorders","Blood & Immune",["Chediak-Higashi"]),
("D72","WBC disorders NEC","Blood & Immune",["leukocytosis","eosinophilia"]),
("D73","Spleen diseases","Blood & Immune",["splenomegaly"]),
("D75","Blood-forming organ NEC","Blood & Immune",["myelofibrosis"]),
("D80","Immunodeficiency antibody","Blood & Immune",["hypogammaglobulinemia"]),
("D81","Combined immunodeficiencies","Blood & Immune",["SCID"]),
("D86","Sarcoidosis","Blood & Immune",["sarcoid","sarcoidosis"]),
("D89","Immune disorders NEC","Blood & Immune",["immune disorder NOS"]),
("E00","Congenital iodine deficiency","Endocrine",["congenital hypothyroidism","cretenismo"]),
("E01","Iodine deficiency disorders","Endocrine",["goiter","bocio","iodine deficiency"]),
("E03","Other hypothyroidism","Endocrine",["hypothyroidism","hipotiroidismo"]),
("E04","Nontoxic goiter","Endocrine",["goiter","bocio","thyroid nodule"]),
("E05","Thyrotoxicosis","Endocrine",["hyperthyroidism","tirotoxicosis"]),
("E06","Thyroiditis","Endocrine",["Hashimoto thyroiditis"]),
("E07","Thyroid disorders NEC","Endocrine",["thyroid disorder NOS"]),
("E10","Type 1 diabetes","Endocrine",["DM1","diabetes tipo 1","juvenile diabetes"]),
("E11","Type 2 diabetes","Endocrine",["DM2","diabetes tipo 2"]),
("E12","Malnutrition-related diabetes","Endocrine",["tropical diabetes"]),
("E13","Other specified diabetes","Endocrine",["secondary diabetes","steroid induced"]),
("E14","Unspecified diabetes","Endocrine",["diabetes NOS"]),
("E15","Hypoglycemic coma","Endocrine",["hypoglycemic coma"]),
("E16","Pancreatic endocrine NEC","Endocrine",["hypoglycemia NOS"]),
("E20","Hypoparathyroidism","Endocrine",["low PTH"]),
("E21","Hyperparathyroidism","Endocrine",["high PTH"]),
("E22","Pituitary hyperfunction","Endocrine",["acromegaly","Cushing disease"]),
("E23","Pituitary hypofunction","Endocrine",["hypopituitarism"]),
("E24","Cushing syndrome","Endocrine",["hypercortisolism","Cushing"]),
("E25","Adrenogenital disorders","Endocrine",["CAH","congenital adrenal hyperplasia"]),
("E26","Hyperaldosteronism","Endocrine",["Conn syndrome"]),
("E27","Other adrenal disorders","Endocrine",["Addison disease","adrenal insufficiency"]),
("E28","Ovarian dysfunction","Endocrine",["PCOS","polycystic ovarian syndrome"]),
("E29","Testicular dysfunction","Endocrine",["hypogonadism","testosterone deficiency"]),
("E30","Pubertal disorders","Endocrine",["precocious puberty"]),
("E31","Polyglandular dysfunction","Endocrine",["autoimmune polyendocrine syndrome"]),
("E34","Endocrine disorders NEC","Endocrine",["short stature"]),
("E40","Kwashiorkor","Endocrine",["protein deficiency","Kwashiorkor"]),
("E41","Nutritional marasmus","Endocrine",["calorie deficiency","marasmus"]),
("E43","Severe protein-energy malnutrition","Endocrine",["severe malnutrition","PEM"]),
("E44","Moderate PEM","Endocrine",["moderate malnutrition"]),
("E46","Unspecified PEM","Endocrine",["malnutrition NOS"]),
("E50","Vitamin A deficiency","Endocrine",["night blindness","xerophthalmia","Vitamin A"]),
("E51","Thiamine deficiency","Endocrine",["beriberi","thiamine","Vitamin B1"]),
("E52","Niacin deficiency","Endocrine",["pellagra","niacin","Vitamin B3"]),
("E53","Other B vitamin deficiencies","Endocrine",["B12 deficiency","biotin","B vitamins"]),
("E54","Ascorbic acid deficiency","Endocrine",["scurvy","Vitamin C deficiency"]),
("E55","Vitamin D deficiency","Endocrine",["hypovitaminosis D","rickets","Vitamin D"]),
("E56","Other vitamin deficiencies","Endocrine",["Vitamin E deficiency","Vitamin K deficiency"]),


("E58","Dietary calcium deficiency","Endocrine",["calcium deficiency"]),
