#!/usr/bin/env python3
"""
Generate expanded ICD-10-CM database with 300+ real codes from WHO ICD-10
Categorizes codes by their official WHO chapter (I-XXII)
"""
import json

def build_icd10():
    data = []

    # ========== Chapter I: A00-B99 — Infectious and Parasitic ==========
    ch1_infectious = [
        ("A00", "Cholera"),
        ("A01", "Typhoid and paratyphoid fevers"),
        ("A02", "Other salmonella infections"),
        ("A03", "Shigellosis"),
        ("A04", "Other bacterial intestinal infections"),
        ("A05", "Other bacterial foodborne intoxications"),
        ("A06", "Amebiasis"),
        ("A07", "Other protozoal intestinal diseases"),
        ("A08", "Viral and other specified intestinal infections"),
        ("A09", "Other gastroenteritis and colitis of infectious origin"),
        ("A15", "Respiratory tuberculosis"),
        ("A16", "Respiratory tuberculosis, not confirmed"),
        ("A17", "Tuberculosis of nervous system"),
        ("A18", "Tuberculosis of other organs"),
        ("A19", "Miliary tuberculosis"),
        ("A20", "Plague"),
        ("A21", "Tularemia"),
        ("A22", "Anthrax"),
        ("A23", "Brucellosis"),
        ("A27", "Leptospirosis"),
        ("A30", "Leprosy [Hansen disease]"),
        ("A31", "Infection due to other mycobacteria"),
        ("A32", "Listeriosis"),
        ("A35", "Other tetanus"),
        ("A36", "Diphtheria"),
        ("A37", "Whooping cough [pertussis]"),
        ("A38", "Scarlet fever"),
        ("A39", "Meningococcal infection"),
        ("A40", "Streptococcal sepsis"),
        ("A41", "Other sepsis"),
        ("A46", "Erysipelas"),
        ("A48", "Other bacterial diseases, NEC"),
        ("A49", "Bacterial infection of unspecified site"),
        ("A50", "Congenital syphilis"),
        ("A51", "Early syphilis"),
        ("A52", "Late syphilis"),
        ("A53", "Other and unspecified syphilis"),
        ("A54", "Gonococcal infection"),
        ("A55", "Chlamydial lymphogranuloma"),
        ("A56", "Other sexually transmitted chlamydial diseases"),
        ("A57", "Chancroid"),
        ("A59", "Trichomoniasis"),
        ("A60", "Anogenital herpesviral infection"),
        ("A63", "Other predominantly STDs"),
        ("A64", "Unspecified sexually transmitted disease"),
        ("A69", "Other spirochetal infections"),
        ("A70", "Chlamydia psittaci infection"),
        ("A71", "Trachoma"),
        ("A74", "Other diseases caused by chlamydiae"),
        ("A75", "Typhus fever"),
        ("A77", "Spotted fever [tick-borne rickettsioses]"),
        ("A78", "Q fever"),
        ("A79", "Other rickettsioses"),
        ("A80", "Acute poliomyelitis"),
        ("A81", "Atypical virus infections of CNS"),
        ("A82", "Rabies"),
        ("A83", "Mosquito-borne viral encephalitis"),
        ("A84", "Tick-borne viral encephalitis"),
        ("A85", "Other viral encephalitis, NEC"),
        ("A86", "Unspecified viral encephalitis"),
        ("A87", "Viral meningitis"),
        ("A90", "Dengue fever [classical dengue]"),
        ("A91", "Dengue hemorrhagic fever"),
        ("A92", "Other mosquito-borne viral fevers"),
        ("A93", "Other arthropod-borne viral fevers"),
        ("A95", "Yellow fever"),
        ("A96", "Arenaviral hemorrhagic fever"),
        ("A98", "Other viral hemorrhagic fevers"),
        ("A99", "Unspecified viral hemorrhagic fever"),
        ("B00", "Herpesviral [herpes simplex] infections"),
        ("B01", "Varicella [chickenpox]"),
        ("B02", "Zoster [herpes zoster]"),
        ("B05", "Measles"),
        ("B06", "Rubella"),
        ("B07", "Viral warts"),
        ("B08", "Other viral infections with skin lesions"),
        ("B09", "Unspecified viral infection with skin lesions"),
        ("B15", "Acute hepatitis A"),
        ("B16", "Acute hepatitis B"),
        ("B17", "Other acute viral hepatitis"),
        ("B18", "Chronic viral hepatitis"),
        ("B19", "Unspecified viral hepatitis"),
        ("B20", "Human immunodeficiency virus [HIV] disease"),
        ("B24", "Unspecified HIV infection"),
        ("B25", "Cytomegaloviral disease"),
        ("B26", "Mumps"),
        ("B27", "Infectious mononucleosis"),
        ("B30", "Viral conjunctivitis"),
        ("B34", "Viral infection of unspecified site"),
        ("B35", "Dermatophytosis"),
        ("B36", "Other superficial mycoses"),
        ("B37", "Candidiasis"),
        ("B38", "Coccidioidomycosis"),
        ("B39", "Histoplasmosis"),
        ("B40", "Blastomycosis"),
        ("B41", "Paracoccidioidomycosis"),
        ("B42", "Sporotrichosis"),
        ("B44", "Aspergillosis"),
        ("B45", "Cryptococcosis"),
        ("B46", "Zygomycosis"),
        ("B48", "Other mycoses, NEC"),
        ("B49", "Unspecified mycosis"),
        ("B50", "Plasmodium falciparum malaria"),
        ("B51", "Plasmodium vivax malaria"),
        ("B52", "Plasmodium malariae malaria"),
        ("B53", "Other parasitologically confirmed malaria"),
        ("B54", "Unspecified malaria"),
        ("B55", "Leishmaniasis"),
        ("B56", "African trypanosomiasis"),
        ("B57", "Chagas disease"),
        ("B58", "Toxoplasmosis"),
        ("B59", "Pneumocystosis"),
        ("B60", "Other protozoal diseases, NEC"),
        ("B64", "Unspecified protozoal disease"),
        ("B65", "Schistosomiasis [bilharziasis]"),
        ("B66", "Other fluke infections"),
        ("B67", "Echinococcosis"),
        ("B68", "Taeniasis"),
        ("B69", "Cysticercosis"),
        ("B70", "Diphyllobothriasis and sparganosis"),
        ("B71", "Other cestode infections"),
        ("B72", "Dracunculiasis"),
        ("B73", "Onchocerciasis"),
        ("B74", "Filariasis"),
        ("B75", "Trichinellosis"),
        ("B76", "Hookworm diseases"),
        ("B77", "Ascariasis"),
        ("B78", "Strongyloidiasis"),
        ("B79", "Trichuriasis"),
        ("B80", "Enterobiasis"),
        ("B81", "Other intestinal helminthiases"),
        ("B82", "Unspecified intestinal parasitism"),
        ("B83", "Other helminthiases"),
        ("B85", "Pediculosis and phthiriasis"),
        ("B86", "Scabies"),
        ("B87", "Myiasis"),
        ("B88", "Other infestations"),
        ("B89", "Unspecified parasitic disease"),
        ("B90", "Sequelae of tuberculosis"),
        ("B91", "Sequelae of poliomyelitis"),
        ("B94", "Sequelae of other infectious diseases"),
        ("B95", "Streptococcus/staphylococcus as cause"),
        ("B96", "Other bacterial agents as cause"),
        ("B97", "Viral agents as cause of diseases"),
        ("B99", "Other and unspecified infectious diseases"),
    ]
    for code, name in ch1_infectious:
        slug = name.lower().replace(" ", "_").replace(",","").replace("[","").replace("]","").replace("(","").replace(")","").replace("__","_")
        data.append({
            "code": code, "displayName": name, "category": "Infectious",
            "wikipediaUrl": f"https://en.wikipedia.org/wiki/{slug}",
            "searchTerms": [name]
        })

    # ========== Chapter II: C00-D48 — Neoplasms ==========
    neoplasms = [
        ("C00", "Malignant neoplasm of lip"), ("C01", "Malignant neoplasm of base of tongue"),
        ("C02", "Malignant neoplasm of other parts of tongue"), ("C03", "Malignant neoplasm of gum"),
        ("C04", "Malignant neoplasm of floor of mouth"), ("C05", "Malignant neoplasm of palate"),
        ("C06", "Malignant neoplasm of other parts of mouth"), ("C07", "Malignant neoplasm of parotid gland"),
        ("C08", "Malignant neoplasm of other salivary glands"), ("C09", "Malignant neoplasm of tonsil"),
        ("C10", "Malignant neoplasm of oropharynx"), ("C11", "Malignant neoplasm of nasopharynx"),
        ("C12", "Malignant neoplasm of pyriform sinus"), ("C13", "Malignant neoplasm of hypopharynx"),
        ("C14", "Malignant neoplasm of other lip/oral cavity/pharynx"), ("C15", "Malignant neoplasm of esophagus"),
        ("C16", "Malignant neoplasm of stomach"), ("C17", "Malignant neoplasm of small intestine"),
        ("C18", "Malignant neoplasm of colon"), ("C19", "Malignant neoplasm of rectosigmoid junction"),
        ("C20", "Malignant neoplasm of rectum"), ("C21", "Malignant neoplasm of anus and anal canal"),
        ("C22", "Malignant neoplasm of liver and intrahepatic bile ducts"), ("C23", "Malignant neoplasm of gallbladder"),
        ("C24", "Malignant neoplasm of other parts of biliary tract"), ("C25", "Malignant neoplasm of pancreas"),
        ("C26", "Malignant neoplasm of other digestive organs"), ("C30", "Malignant neoplasm of nasal cavity"),
        ("C31", "Malignant neoplasm of accessory sinuses"), ("C32", "Malignant neoplasm of larynx"),
        ("C33", "Malignant neoplasm of trachea"), ("C34", "Malignant neoplasm of bronchus and lung"),
        ("C37", "Malignant neoplasm of thymus"), ("C38", "Malignant neoplasm of heart/mediastinum/pleura"),
        ("C39", "Malignant neoplasm of other respiratory sites"), ("C40", "Malignant neoplasm of bone and articular cartilage"),
        ("C41", "Malignant neoplasm of other bone/cartilage"), ("C43", "Malignant melanoma of skin"),
        ("C44", "Other malignant neoplasms of skin"), ("C45", "Mesothelioma"),
        ("C46", "Kaposi sarcoma"), ("C47", "Malignant neoplasm of peripheral nerves"),
        ("C48", "Malignant neoplasm of retroperitoneum and peritoneum"), ("C49", "Malignant neoplasm of connective/soft tissue"),
        ("C50", "Malignant neoplasm of breast"), ("C51", "Malignant neoplasm of vulva"),
        ("C52", "Malignant neoplasm of vagina"), ("C53", "Malignant neoplasm of cervix uteri"),
        ("C54", "Malignant neoplasm of corpus uteri"), ("C55", "Malignant neoplasm of uterus, unspecified"),
        ("C56", "Malignant neoplasm of ovary"), ("C57", "Malignant neoplasm of other female genital organs"),
        ("C58", "Malignant neoplasm of placenta"), ("C60", "Malignant neoplasm of penis"),
        ("C61", "Malignant neoplasm of prostate"), ("C62", "Malignant neoplasm of testis"),
        ("C63", "Malignant neoplasm of other male genital organs"), ("C64", "Malignant neoplasm of kidney except renal pelvis"),
        ("C65", "Malignant neoplasm of renal pelvis"), ("C66", "Malignant neoplasm of ureter"),
        ("C67", "Malignant neoplasm of bladder"), ("C68", "Malignant neoplasm of other urinary organs"),
        ("C69", "Malignant neoplasm of eye and adnexa"), ("C70", "Malignant neoplasm of meninges"),
        ("C71", "Malignant neoplasm of brain"), ("C72", "Malignant neoplasm of spinal cord and CNS"),
        ("C73", "Malignant neoplasm of thyroid gland"), ("C74", "Malignant neoplasm of adrenal gland"),
        ("C75", "Malignant neoplasm of other endocrine glands"), ("C76", "Malignant neoplasm of other ill-defined sites"),
        ("C77", "Secondary malignant neoplasm of lymph nodes"), ("C78", "Secondary neoplasm of respiratory/digestive"),
        ("C79", "Secondary malignant neoplasm of other sites"), ("C80", "Malignant neoplasm without specification of site"),
        ("C81", "Hodgkin lymphoma"), ("C82", "Follicular lymphoma"),
        ("C83", "Non-follicular lymphoma"), ("C84", "Mature T/NK-cell lymphomas"),
        ("C85", "Other specified types of NHL"), ("C86", "Other T/NK-cell lymphomas"),
        ("C88", "Malignant immunoproliferative diseases"), ("C90", "Multiple myeloma and malignant plasma cell neoplasms"),
        ("C91", "Lymphoid leukemia"), ("C92", "Myeloid leukemia"),
        ("C93", "Monocytic leukemia"), ("C94", "Other leukemias of specified cell type"),
        ("C95", "Leukemia of unspecified cell type"), ("C96", "Other malignant neoplasms of lymphoid/hematopoietic"),
        ("D00", "Carcinoma in situ of oral cavity/esophagus/stomach"), ("D01", "Carcinoma in situ of other digestive organs"),
        ("D02", "Carcinoma in situ of respiratory system"), ("D03", "Melanoma in situ"),
        ("D04", "Carcinoma in situ of skin"), ("D05", "Carcinoma in situ of breast"),
        ("D06", "Carcinoma in situ of cervix uteri"), ("D07", "Carcinoma in situ of other genital organs"),
        ("D09", "Carcinoma in situ of other sites"), ("D10", "Benign neoplasm of mouth/pharynx"),
        ("D11", "Benign neoplasm of major salivary glands"), ("D12", "Benign neoplasm of colon/rectum/anus"),
        ("D13", "Benign neoplasm of other digestive system"), ("D14", "Benign neoplasm of respiratory system"),
        ("D15", "Benign neoplasm of other intrathoracic organs"), ("D16", "Benign neoplasm of bone and cartilage"),
        ("D17", "Benign lipomatous neoplasm"), ("D18", "Hemangioma of any site"),
        ("D19", "Benign neoplasm of mesothelial tissue"), ("D20", "Benign neoplasm of peritoneum/retroperitoneum"),
        ("D21", "Other benign neoplasms of connective/soft tissue"), ("D22", "Melanocytic nevi"),
        ("D23", "Other benign neoplasms of skin"), ("D24", "Benign neoplasm of breast"),
        ("D25", "Leiomyoma of uterus"), ("D26", "Other benign neoplasms of uterus"),
        ("D27", "Benign neoplasm of ovary"), ("D28", "Benign neoplasm of other female genital organs"),
        ("D29", "Benign neoplasm of male genital organs"), ("D30", "Benign neoplasm of urinary organs"),
        ("D31", "Benign neoplasm of eye and adnexa"), ("D32", "Benign neoplasm of meninges"),
        ("D33", "Benign neoplasm of brain and CNS"), ("D34", "Benign neoplasm of thyroid gland"),
        ("D35", "Benign neoplasm of other endocrine glands"), ("D36", "Benign neoplasm of other unspecified sites"),
        ("D37", "Neoplasm of uncertain behavior of oral/digestive"), ("D38", "Neoplasm uncertain of respiratory"),
        ("D39", "Neoplasm uncertain of female genital"), ("D40", "Neoplasm uncertain of male genital"),
        ("D41", "Neoplasm uncertain of urinary"), ("D42", "Neoplasm uncertain of meninges"),
        ("D43", "Neoplasm uncertain of brain and CNS"), ("D44", "Neoplasm uncertain of endocrine"),
        ("D45", "Polycythemia vera"), ("D46", "Myelodysplastic syndromes"),
        ("D47", "Other neoplasms uncertain of lymphoid/hematopoietic"), ("D48", "Neoplasm uncertain of other unspecified sites"),
    ]
    for code, name in neoplasms:
        slug = name.lower().replace(" ", "_").replace(",","").replace("/","_").replace("-","").replace("__","_")
        data.append({
            "code": code, "displayName": name, "category": "Neoplasms",
            "wikipediaUrl": f"https://en.wikipedia.org/wiki/{slug}",
            "searchTerms": [name]
        })

    # ========== Chapter III: D50-D89 — Blood ==========
    blood = [
        ("D50", "Iron deficiency anemia"), ("D51", "Vitamin B12 deficiency anemia"),
        ("D52", "Folate deficiency anemia"), ("D53", "Other nutritional anemias"),
        ("D55", "Anemia due to enzyme disorders"), ("D56", "Thalassemia"),
        ("D57", "Sickle cell disorders"), ("D58", "Other hereditary hemolytic anemias"),
        ("D59", "Acquired hemolytic anemia"), ("D60", "Acquired pure red cell aplasia"),
        ("D61", "Other aplastic anemias"), ("D62", "Acute posthemorrhagic anemia"),
        ("D63", "Anemia in chronic diseases"), ("D64", "Other anemias"),
        ("D65", "Disseminated intravascular coagulation"), ("D66", "Hereditary factor VIII deficiency"),
        ("D67", "Hereditary factor IX deficiency"), ("D68", "Other coagulation defects"),
        ("D69", "Purpura and other hemorrhagic conditions"), ("D70", "Neutropenia"),
        ("D71", "Functional disorders of neutrophils"), ("D72", "Other white blood cell disorders"),
        ("D73", "Diseases of spleen"), ("D74", "Methemoglobinemia"),
        ("D75", "Other blood-forming organ diseases"), ("D76", "Histiocytic syndromes"),
        ("D80", "Immunodeficiency with antibody defects"), ("D81", "Combined immunodeficiencies"),
        ("D82", "Immunodeficiency with other major defects"), ("D83", "Common variable immunodeficiency"),
        ("D84", "Other immunodeficiencies"), ("D86", "Sarcoidosis"),
        ("D89", "Other immune mechanism disorders"),
    ]
    for code, name in blood:
        slug = name.lower().replace(" ", "_").replace(",","").replace("/","_")
        data.append({
            "code": code, "displayName": name, "category": "Blood & Immune",
            "wikipediaUrl": f"https://en.wikipedia.org/wiki/{slug}",
            "searchTerms": [name]
        })

    # ========== Chapter IV: E00-E90 — Endocrine (preserving + adding) ==========
    endocrine = [
        ("E00", "Congenital iodine deficiency syndrome"), ("E01", "Iodine deficiency disorders"),
        ("E02", "Subclinical iodine-deficiency hypothyroidism"),
        ("E03", "Other hypothyroidism"), ("E04", "Other nontoxic goiter"),
        ("E05", "Thyrotoxicosis [hyperthyroidism]"), ("E06", "Thyroiditis"),
        ("E07", "Other thyroid disorders"), ("E10", "Type 1 diabetes mellitus"),
        ("E11", "Type 2 diabetes mellitus"), ("E12", "Malnutrition-related diabetes"),
        ("E13", "Other specified diabetes"), ("E14", "Unspecified diabetes"),
        ("E15", "Nondiabetic hypoglycemic coma"), ("E16", "Other pancreatic endocrine disorders"),
        ("E20", "Hypoparathyroidism"), ("E21", "Hyperparathyroidism"),
        ("E22", "Hyperfunction of pituitary gland"), ("E23", "Hypofunction of pituitary"),
        ("E24", "Cushing syndrome"), ("E25", "Adrenogenital disorders"),
        ("E26", "Hyperaldosteronism"), ("E27", "Other adrenal disorders"),
        ("E28", "Ovarian dysfunction"), ("E29", "Testicular dysfunction"),
        ("E30", "Pubertal disorders"), ("E31", "Polyglandular dysfunction"),
        ("E32", "Diseases of thymus"), ("E34", "Other endocrine disorders"),
        ("E40", "Kwashiorkor"), ("E41", "Nutritional marasmus"),
        ("E42", "Marasmic kwashiorkor"), ("E43", "Severe protein-energy malnutrition"),
        ("E44", "Moderate/mild protein-energy malnutrition"), ("E45", "Retarded development due to malnutrition"),
        ("E46", "Unspecified protein-energy malnutrition"), ("E50", "Vitamin A deficiency"),
        ("E51", "Thiamine deficiency"), ("E52", "Niacin deficiency [pellagra]"),
        ("E53", "Other B vitamin deficiencies"), ("E54", "Ascorbic acid deficiency"),
        ("E55", "Vitamin D deficiency"), ("E56", "Other vitamin deficiencies"),
        ("E58", "Dietary calcium deficiency"), ("E59", "Dietary selenium deficiency"),
        ("E60", "Dietary zinc deficiency"), ("E61", "Other nutrient deficiencies"),
        ("E63", "Other nutritional deficiencies"), ("E64", "Sequelae of malnutrition"),
        ("E65", "Localized adiposity"), ("E66", "Obesity"),
        ("E67", "Other hyperalimentation"), ("E68", "Sequelae of hyperalimentation"),
        ("E70", "Phenylketonuria/other amino acid disorders"), ("E71", "Branched-chain amino acid disorders"),
        ("E72", "Other amino acid metabolism disorders"), ("E73", "Lactose intolerance"),
        ("E74", "Carbohydrate metabolism disorders"), ("E75", "Sphingolipid storage disorders"),
        ("E76", "Glycosaminoglycan metabolism disorders"), ("E77", "Glycoprotein metabolism disorders"),
        ("E78", "Lipoprotein metabolism disorders"), ("E79", "Purine/pyrimidine metabolism"),
        ("E80", "Porphyrin/bilirubin metabolism"), ("E83", "Mineral metabolism disorders"),
        ("E84", "Cystic fibrosis"), ("E85", "Amyloidosis"),
        ("E86", "Volume depletion [dehydration]"), ("E87", "Fluid/electrolyte/acid-base disorders"),
        ("E88", "Other metabolic disorders"), ("E89", "Postprocedural endocrine disorders"),
        ("E90", "Nutritional/metabolic disorders in diseases"),
    ]
    for code, name in endocrine:
        slug = name.lower().replace(" ", "_").replace(",","").replace("/","_").replace("[","").replace("]","").replace("(","").replace(")","").replace("__","_").replace("___","_")
        data.append({
            "code": code, "displayName": name, "category": "Endocrine",
            "wikipediaUrl": f"https://en.wikipedia.org/wiki/{slug}",
            "searchTerms": [name]
        })

    # ========== Chapter V: F00-F99 — Mental (preserving existing + adding) ==========
    mental = [
        ("F00", "Dementia in Alzheimer disease"), ("F01", "Vascular dementia"),
        ("F02", "Dementia in other diseases"), ("F03", "Unspecified dementia"),
        ("F04", "Organic amnesic syndrome"), ("F05", "Delirium"),
        ("F06", "Other mental disorders due to brain damage"), ("F07", "Personality/behavior disorders due to brain disease"),
        ("F09", "Unspecified organic/symptomatic mental disorder"),
        ("F10", "Alcohol related disorders"), ("F11", "Opioid related disorders"),
        ("F12", "Cannabis related disorders"), ("F13", "Sedative/hypnotic related disorders"),
        ("F14", "Cocaine related disorders"), ("F15", "Other stimulant related disorders"),
        ("F16", "Hallucinogen related disorders"), ("F17", "Nicotine dependence"),
        ("F18", "Inhalant related disorders"), ("F19", "Other psychoactive substance related disorders"),
        ("F20", "Schizophrenia"), ("F21", "Schizotypal disorder"),
        ("F22", "Delusional disorders"), ("F23", "Acute/transient psychotic disorders"),
        ("F24", "Induced delusional disorder"), ("F25", "Schizoaffective disorders"),
        ("F28", "Other nonorganic psychotic disorders"), ("F29", "Unspecified nonorganic psychosis"),
        ("F30", "Manic episode"), ("F31", "Bipolar affective disorder"),
        ("F32", "Depressive episode"), ("F33", "Recurrent depressive disorder"),
        ("F34", "Persistent mood disorders"), ("F38", "Other mood disorders"),
        ("F39", "Unspecified mood disorder"), ("F40", "Phobic anxiety disorders"),
        ("F41", "Other anxiety disorders"), ("F42", "Obsessive-compulsive disorder"),
        ("F43", "Reaction to severe stress/adjustment"), ("F44", "Dissociative [conversion] disorders"),
        ("F45", "Somatoform disorders"), ("F48", "Other neurotic disorders"),
        ("F50", "Eating disorders"), ("F51", "Nonorganic sleep disorders"),
        ("F52", "Sexual dysfunction"), ("F53", "Mental disorders puerperium"),
        ("F54", "Psychological factors in physical disorders"), ("F55", "Abuse of non-dependence substances"),
        ("F59", "Unspecified behavioral syndromes"), ("F60", "Specific personality disorders"),
        ("F61", "Mixed personality disorders"), ("F62", "Enduring personality changes"),
        ("F63", "Habit and impulse disorders"), ("F64", "Gender identity disorders"),
        ("F65", "Paraphilias"), ("F66", "Psychosexual development disorders"),
        ("F68", "Other adult personality/behavior disorders"), ("F69", "Unspecified personality/behavior disorder"),
        ("F70", "Mild intellectual disability"), ("F71", "Moderate intellectual disability"),
        ("F72", "Severe intellectual disability"), ("F73", "Profound intellectual disability"),
        ("F78", "Other intellectual disability"), ("F79", "Unspecified intellectual disability"),
        ("F80", "Speech/language developmental disorders"), ("F81", "Specific developmental learning disorders"),
        ("F82", "Motor function developmental disorder"), ("F83", "Mixed specific developmental disorders"),
        ("F84", "Pervasive developmental disorders"), ("F88", "Other developmental disorders"),
        ("F89", "Unspecified developmental disorder"),
        ("F90", "Attention-deficit hyperactivity disorder"), ("F91", "Conduct disorders"),
        ("F92", "Mixed conduct/emotional disorders"), ("F93", "Emotional disorders of childhood"),
        ("F94", "Social functioning disorders of childhood"), ("F95", "Tic disorders"),
        ("F98", "Other behavioral/emotional disorders of childhood"), ("F99", "Unspecified mental disorder"),
    ]
    for code, name in mental:
        slug = name.lower().replace(" ", "_").replace(",","").replace("/","_").replace("[","").replace("]","").replace("____","_").replace("___","_").replace("__","_")
        data.append({
            "code": code, "displayName": name, "category": "Mental",
            "wikipediaUrl": f"https://en.wikipedia.org/wiki/{slug}",
            "searchTerms": [name]
        })

    # ========== Chapter VI: G00-G99 — Nervous System ==========
    nervous = [
        ("G00", "Bacterial meningitis"), ("G01", "Meningitis in bacterial diseases"),
        ("G02", "Meningitis in other infectious diseases"), ("G03", "Meningitis due to other causes"),
        ("G04", "Encephalitis, myelitis, encephalomyelitis"), ("G05", "Encephalitis in diseases classified"),
        ("G06", "Intracranial/intraspinal abscess"), ("G07", "Intracranial abscess in diseases"),
        ("G08", "Intracranial/intraspinal phlebitis"), ("G09", "CNS inflammatory disease sequelae"),
        ("G10", "Huntington disease"), ("G11", "Hereditary ataxia"),
        ("G12", "Spinal muscular atrophy"), ("G13", "Systemic atrophies in diseases"),
        ("G20", "Parkinson disease"), ("G21", "Secondary parkinsonism"),
        ("G22", "Parkinsonism in diseases classified"), ("G23", "Other basal ganglia diseases"),
        ("G24", "Dystonia"), ("G25", "Other extrapyramidal movement disorders"),
        ("G30", "Alzheimer disease"), ("G31", "Other degenerative nervous system diseases"),
        ("G32", "Degenerative nervous system in diseases"), ("G35", "Multiple sclerosis"),
        ("G36", "Other acute disseminated demyelination"), ("G37", "Other CNS demyelinating diseases"),
        ("G40", "Epilepsy"), ("G41", "Status epilepticus"),
        ("G43", "Migraine"), ("G44", "Other headache syndromes"),
        ("G45", "Transient cerebral ischemic attacks"), ("G46", "Stroke syndromes"),
        ("G47", "Sleep disorders"), ("G50", "Trigeminal nerve disorders"),
        ("G51", "Facial nerve disorders"), ("G52", "Other cranial nerve disorders"),
        ("G53", "Cranial nerve disorders in diseases"), ("G54", "Nerve root/plexus disorders"),
        ("G55", "Nerve root in diseases"), ("G56", "Upper limb mononeuropathies"),
        ("G57", "Lower limb mononeuropathies"), ("G58", "Other mononeuropathies"),
        ("G59", "Mononeuropathy in diseases"), ("G60", "Hereditary/idiopathic neuropathy"),
        ("G61", "Inflammatory polyneuropathy"), ("G62", "Other polyneuropathies"),
        ("G63", "Polyneuropathy in diseases"), ("G64", "Peripheral nervous system disorders"),
        ("G70", "Myasthenia gravis"), ("G71", "Primary muscle disorders"),
        ("G72", "Other myopathies"), ("G73", "Myopathy in diseases"),
        ("G80", "Cerebral palsy"), ("G81", "Hemiplegia"),
        ("G82", "Paraplegia and tetraplegia"), ("G83", "Other paralytic syndromes"),
        ("G90", "Autonomic nervous system disorders"), ("G91", "Hydrocephalus"),
        ("G92", "Toxic encephalopathy"), ("G93", "Other brain disorders"),
        ("G94", "Brain disorders in diseases"), ("G95", "Spinal cord diseases"),
        ("G96", "CNS disorders"), ("G97", "Postprocedural nervous system disorders"),
        ("G98", "Nervous system disorders in diseases"), ("G99", "Nervous system disorders in classified diseases"),
    ]
    for code, name in nervous:
        slug = name.lower().replace(" ", "_").replace(",","").replace("/","_").replace("[","").replace("]","").replace("____","_").replace("___","_").replace("__","_")
        data.append({
            "code": code, "displayName": name, "category": "Nervous System",
            "wikipediaUrl": f"https://en.wikipedia.org/wiki/{slug}",
            "searchTerms": [name]
        })

    # ========== Chapter IX: I00-I99 — Circulatory ==========
    circulatory = [
        ("I10", "Essential [primary] hypertension"), ("I11", "Hypertensive heart disease"),
        ("I12", "Hypertensive renal disease"), ("I13", "Hypertensive heart and renal disease"),
        ("I15", "Secondary hypertension"), ("I20", "Angina pectoris"),
        ("I21", "Acute myocardial infarction"), ("I22", "Subsequent STEMI/NSTEMI"),
        ("I23", "Complications of acute MI"), ("I24", "Other acute ischemic heart diseases"),
        ("I25", "Chronic ischemic heart disease"), ("I26", "Pulmonary embolism"),
        ("I27", "Other pulmonary heart diseases"), ("I28", "Other pulmonary vessel diseases"),
        ("I30", "Acute pericarditis"), ("I31", "Other pericardial diseases"),
        ("I32", "Pericarditis in diseases"), ("I33", "Acute/subacute endocarditis"),
        ("I34", "Mitral valve disorders"), ("I35", "Aortic valve disorders"),
        ("I36", "Tricuspid valve disorders"), ("I37", "Pulmonary valve disorders"),
        ("I38", "Endocarditis unspecified"), ("I39", "Endocarditis in diseases"),
        ("I40", "Acute myocarditis"), ("I41", "Myocarditis in diseases"),
        ("I42", "Cardiomyopathy"), ("I43", "Cardiomyopathy in diseases"),
        ("I44", "Atrioventricular and left bundle branch block"), ("I45", "Other conduction disorders"),
        ("I46", "Cardiac arrest"), ("I47", "Paroxysmal tachycardia"),
        ("I48", "Atrial fibrillation and flutter"), ("I49", "Other cardiac arrhythmias"),
        ("I50", "Heart failure"), ("I51", "Complications of heart disease"),
        ("I52", "Heart disorders in diseases"), ("I60", "Subarachnoid hemorrhage"),
        ("I61", "Intracerebral hemorrhage"), ("I62", "Other nontraumatic intracranial hemorrhage"),
        ("I63", "Cerebral infarction"), ("I64", "Stroke not specified hemorrhage/infarction"),
        ("I65", "Cerebral artery occlusion without infarction"), ("I66", "Cerebral artery occlusion with infarction"),
        ("I67", "Other cerebrovascular diseases"), ("I68", "Cerebrovascular disorders in diseases"),
        ("I69", "Sequelae of cerebrovascular disease"), ("I70", "Atherosclerosis"),
        ("I71", "Aortic aneurysm and dissection"), ("I72", "Other aneurysm"),
        ("I73", "Peripheral vascular disease"), ("I74", "Arterial embolism and thrombosis"),
        ("I77", "Other arterial disorders"), ("I78", "Capillary diseases"),
        ("I79", "Arterial disorders in diseases"), ("I80", "Phlebitis and thrombophlebitis"),
        ("I81", "Portal vein thrombosis"), ("I82", "Other venous embolism/thrombosis"),
        ("I83", "Varicose veins of lower extremities"), ("I84", "Hemorrhoids"),
        ("I85", "Esophageal varices"), ("I86", "Varicose veins other sites"),
        ("I87", "Other venous disorders"), ("I88", "Nonspecific lymphadenitis"),
        ("I89", "Other lymphatic disorders"), ("I95", "Hypotension"),
        ("I97", "Postprocedural circulatory disorders"), ("I98", "Circulatory disorders in diseases"),
        ("I99", "Other circulatory system disorders"),
