#!/usr/bin/env python3
"""
Generate expanded medical standards JSON files for OrionHealth.
Creates comprehensive, real ICD-10, LOINC, RxNorm, and SNOMED CT code lists.
"""
import json, os, sys

OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "medical-standards")

# ============================================================
# ICD-10-CM — 300+ codes covering all 22 chapters
# Based on WHO ICD-10 international version and ICD-10-CM
# ============================================================
ICD10_DATA = [
    # Chapter I: A00-B99 — Infectious/Parasitic
    {"code": "A00", "displayName": "Cholera", "category": "Infectious", "searchTerms": ["Colera", "Vibrio cholerae"]},
    {"code": "A01", "displayName": "Typhoid and paratyphoid fevers", "category": "Infectious", "searchTerms": ["Typhoid fever", "Fiebre tifoidea", "Salmonella typhi"]},
    {"code": "A02", "displayName": "Other salmonella infections", "category": "Infectious", "searchTerms": ["Salmonellosis", "Salmonela"]},
    {"code": "A03", "displayName": "Shigellosis", "category": "Infectious", "searchTerms": ["Bacillary dysentery", "Disenteria bacilar"]},
    {"code": "A04", "displayName": "Other bacterial intestinal infections", "category": "Infectious", "searchTerms": ["E. coli enteritis", "Campylobacter"]},
    {"code": "A05", "displayName": "Other bacterial foodborne intoxications", "category": "Infectious", "searchTerms": ["Food poisoning", "Botulism"]},
    {"code": "A06", "displayName": "Amebiasis", "category": "Infectious", "searchTerms": ["Amebic dysentery", "Amebiasis intestinal", "Entamoeba histolytica"]},
    {"code": "A07", "displayName": "Other protozoal intestinal diseases", "category": "Infectious", "searchTerms": ["Giardiasis", "Cryptosporidiosis", "Isosporiasis"]},
    {"code": "A08", "displayName": "Viral and other specified intestinal infections", "category": "Infectious", "searchTerms": ["Rotavirus enteritis", "Norovirus", "Gastroenteritis viral"]},
    {"code": "A09", "displayName": "Other gastroenteritis and colitis of infectious origin", "category": "Infectious", "searchTerms": ["Infectious diarrhea", "Gastroenteritis infecciosa"]},
    {"code": "A15", "displayName": "Respiratory tuberculosis", "category": "Infectious", "searchTerms": ["Pulmonary TB", "Tuberculosis pulmonar", "TBC"]},
    {"code": "A16", "displayName": "Respiratory tuberculosis, not confirmed bacteriologically or histologically", "category": "Infectious", "searchTerms": ["Tuberculosis", "TB"]},
    {"code": "A17", "displayName": "Tuberculosis of nervous system", "category": "Infectious", "searchTerms": ["Tuberculous meningitis", "TB meningitis"]},
    {"code": "A18", "displayName": "Tuberculosis of other organs", "category": "Infectious", "searchTerms": ["Extrapulmonary TB", "TB lymphadenitis"]},
    {"code": "A19", "displayName": "Miliary tuberculosis", "category": "Infectious", "searchTerms": ["Disseminated TB", "Tuberculosis miliar"]},
    {"code": "A20", "displayName": "Plague", "category": "Infectious", "searchTerms": ["Yersinia pestis", "Bubonic plague", "Peste"]},
    {"code": "A21", "displayName": "Tularemia", "category": "Infectious", "searchTerms": ["Rabbit fever", "Francisella tularensis"]},
    {"code": "A22", "displayName": "Anthrax", "category": "Infectious", "searchTerms": ["Carbunco", "Bacillus anthracis"]},
    {"code": "A23", "displayName": "Brucellosis", "category": "Infectious", "searchTerms": ["Undulant fever", "Brucella", "Fiebre de Malta"]},
    {"code": "A24", "displayName": "Glanders and melioidosis", "category": "Infectious", "searchTerms": ["Burkholderia mallei", "Burkholderia pseudomallei"]},
    {"code": "A27", "displayName": "Leptospirosis", "category": "Infectious", "searchTerms": ["Weil disease", "Leptospira"]},
    {"code": "A30", "displayName": "Leprosy [Hansen disease]", "category": "Infectious", "searchTerms": ["Hansen disease", "Lepra", "Mycobacterium leprae"]},
    {"code": "A31", "displayName": "Infection due to other mycobacteria", "category": "Infectious", "searchTerms": ["Mycobacterium avium", "NTM", "Atypical mycobacteria"]},
    {"code": "A32", "displayName": "Listeriosis", "category": "Infectious", "searchTerms": ["Listeria monocytogenes", "Listeria"]},
    {"code": "A33", "displayName": "Tetanus neonatorum", "category": "Infectious", "searchTerms": ["Neonatal tetanus", "Lockjaw"]},
    {"code": "A34", "displayName": "Obstetric tetanus", "category": "Infectious", "searchTerms": ["Maternal tetanus"]},
    {"code": "A35", "displayName": "Other tetanus", "category": "Infectious", "searchTerms": ["Trismus", "Tetanos"]},
    {"code": "A36", "displayName": "Diphtheria", "category": "Infectious", "searchTerms": ["Corynebacterium diphtheriae", "Difteria"]},
    {"code": "A37", "displayName": "Whooping cough", "category": "Infectious", "searchTerms": ["Pertussis", "Bordetella pertussis", "Tos ferina"]},
    {"code": "A38", "displayName": "Scarlet fever", "category": "Infectious", "searchTerms": ["Scarlatina", "Streptococcal scarlet fever", "Fiebre escarlata"]},
    {"code": "A39", "displayName": "Meningococcal infection", "category": "Infectious", "searchTerms": ["Meningococcal meningitis", "Neisseria meningitidis"]},
    {"code": "A40", "displayName": "Streptococcal sepsis", "category": "Infectious", "searchTerms": ["Group B strep sepsis", "Streptococcus"]},
    {"code": "A41", "displayName": "Other sepsis", "category": "Infectious", "searchTerms": ["Septicemia", "Sepsis bacteriana", "Blood infection"]},
    {"code": "A42", "displayName": "Actinomycosis", "category": "Infectious", "searchTerms": ["Actinomyces"]},
    {"code": "A46", "displayName": "Erysipelas", "category": "Infectious", "searchTerms": ["Erisipela", "St. Anthony fire"]},
    {"code": "A48", "displayName": "Other bacterial diseases, not elsewhere classified", "category": "Infectious", "searchTerms": ["Legionnaires disease", "Legionella"]},
    {"code": "A49", "displayName": "Bacterial infection of unspecified site", "category": "Infectious", "searchTerms": ["Bacterial infection NOS", "Infeccion bacteriana"]},
    {"code": "A50", "displayName": "Congenital syphilis", "category": "Infectious", "searchTerms": ["Treponema pallidum", "Syphilis congenita"]},
    {"code": "A51", "displayName": "Early syphilis", "category": "Infectious", "searchTerms": ["Primary syphilis", "Secondary syphilis", "Chancre"]},
    {"code": "A52", "displayName": "Late syphilis", "category": "Infectious", "searchTerms": ["Tertiary syphilis", "Neurosyphilis", "Gumma"]},
    {"code": "A53", "displayName": "Other and unspecified syphilis", "category": "Infectious", "searchTerms": ["Syphilis NOS", "Sifilis"]},
    {"code": "A54", "displayName": "Gonococcal infection", "category": "Infectious", "searchTerms": ["Gonorrhea", "Neisseria gonorrhoeae", "Gonorrea"]},
    {"code": "A55", "displayName": "Chlamydial lymphogranuloma (venereum)", "category": "Infectious", "searchTerms": ["LGV", "Lymphogranuloma venereum"]},
    {"code": "A56", "displayName": "Other sexually transmitted chlamydial diseases", "category": "Infectious", "searchTerms": ["Chlamydia trachomatis", "Infeccion por clamidia"]},
    {"code": "A57", "displayName": "Chancroid", "category": "Infectious", "searchTerms": ["Haemophilus ducreyi", "Soft chancre"]},
    {"code": "A58", "displayName": "Granuloma inguinale", "category": "Infectious", "searchTerms": ["Donovanosis", "Klebsiella granulomatis"]},
    {"code": "A59", "displayName": "Trichomoniasis", "category": "Infectious", "searchTerms": ["Trichomonas vaginalis", "Tricomoniasis"]},
    {"code": "A60", "displayName": "Anogenital herpesviral infection", "category": "Infectious", "searchTerms": ["Genital herpes", "HSV-2", "Herpes genital"]},
    {"code": "A63", "displayName": "Other predominantly sexually transmitted diseases", "category": "Infectious", "searchTerms": ["HPV", "Genital warts", "Condiloma"]},
    {"code": "A64", "displayName": "Unspecified sexually transmitted disease", "category": "Infectious", "searchTerms": ["STD NOS", "ETS", "ITS"]},
    {"code": "A69", "displayName": "Other spirochetal infections", "category": "Infectious", "searchTerms": ["Lyme disease", "Borrelia burgdorferi", "Borreliosis"]},
    {"code": "A70", "displayName": "Chlamydia psittaci infection", "category": "Infectious", "searchTerms": ["Psittacosis", "Ornithosis", "Parrot fever"]},
    {"code": "A71", "displayName": "Trachoma", "category": "Infectious", "searchTerms": ["Chlamydia trachomatis eye", "Conjunctivitis trachomatous"]},
    {"code": "A74", "displayName": "Other diseases caused by chlamydiae", "category": "Infectious", "searchTerms": ["Chlamydia infection NOS"]},
    {"code": "A75", "displayName": "Typhus fever", "category": "Infectious", "searchTerms": ["Rickettsia prowazekii", "Epidemic typhus", "Tifo"]},
    {"code": "A77", "displayName": "Spotted fever [tick-borne rickettsioses]", "category": "Infectious", "searchTerms": ["Rocky Mountain spotted fever", "Rickettsia rickettsii"]},
    {"code": "A78", "displayName": "Q fever", "category": "Infectious", "searchTerms": ["Coxiella burnetii", "Query fever"]},
    {"code": "A79", "displayName": "Other rickettsioses", "category": "Infectious", "searchTerms": ["Ehrlichiosis", "Anaplasmosis", "Rickettsiosis"]},
    {"code": "A80", "displayName": "Acute poliomyelitis", "category": "Infectious", "searchTerms": ["Polio", "Infantile paralysis", "Poliomielitis"]},
    {"code": "A81", "displayName": "Atypical virus infections of central nervous system", "category": "Infectious", "searchTerms": ["Creutzfeldt-Jakob", "CJD", "Prion disease", "Kuru"]},
    {"code": "A82", "displayName": "Rabies", "category": "Infectious", "searchTerms": ["Hydrophobia", "Lyssavirus", "Rabia"]},
    {"code": "A83", "displayName": "Mosquito-borne viral encephalitis", "category": "Infectious", "searchTerms": ["Japanese encephalitis", "West Nile", "Encefalitis"]},
    {"code": "A84", "displayName": "Tick-borne viral encephalitis", "category": "Infectious", "searchTerms": ["TBE", "Tick-borne encephalitis", "FSME"]},
    {"code": "A85", "displayName": "Other viral encephalitis, not elsewhere classified", "category": "Infectious", "searchTerms": ["Enterovirus encephalitis", "Viral encephalitis NOS"]},
    {"code": "A86", "displayName": "Unspecified viral encephalitis", "category": "Infectious", "searchTerms": ["Encefalitis viral"]},
    {"code": "A87", "displayName": "Viral meningitis", "category": "Infectious", "searchTerms": ["Aseptic meningitis", "Meningitis viral"]},
    {"code": "A88", "displayName": "Other viral infections of central nervous system", "category": "Infectious", "searchTerms": ["Viral myelitis"]},
    {"code": "A90", "displayName": "Dengue fever", "category": "Infectious", "searchTerms": ["Breakbone fever", "Dengue clasico", "Dengue"]},
    {"code": "A91", "displayName": "Dengue hemorrhagic fever", "category": "Infectious", "searchTerms": ["Dengue grave", "DHF", "Dengue hemorragico"]},
    {"code": "A92", "displayName": "Other mosquito-borne viral fevers", "category": "Infectious", "searchTerms": ["Chikungunya", "Zika virus", "Oropouche"]},
    {"code": "A93", "displayName": "Other arthropod-borne viral fevers", "category": "Infectious", "searchTerms": ["Rift Valley fever", "Yellow fever"]},
    {"code": "A95", "displayName": "Yellow fever", "category": "Infectious", "searchTerms": ["Yellow jack", "Fiebre amarilla"]},
    {"code": "A96", "displayName": "Arenaviral hemorrhagic fever", "category": "Infectious", "searchTerms": ["Lassa fever", "Junin virus", "Argentine HF"]},
    {"code": "A97", "displayName": "Cholera", "category": "Infectious", "searchTerms": ["Vibrio cholerae O1", "Colera"]},
    {"code": "A98", "displayName": "Other viral hemorrhagic fevers", "category": "Infectious", "searchTerms": ["Ebola", "Marburg", "Crimean-Congo HF"]},
    {"code": "A99", "displayName": "Unspecified viral hemorrhagic fever", "category": "Infectious", "searchTerms": ["Viral hemorrhagic fever NOS", "VHF"]},
    {"code": "B00", "displayName": "Herpesviral [herpes simplex] infections", "category": "Infectious", "searchTerms": ["HSV", "Cold sores", "Herpes simplex", "Herpes labial"]},
    {"code": "B01", "displayName": "Varicella [chickenpox]", "category": "Infectious", "searchTerms": ["Chickenpox", "Varicela", "Herpes zoster primary"]},
    {"code": "B02", "displayName": "Zoster [herpes zoster]", "category": "Infectious", "searchTerms": ["Shingles", "Herpes zoster", "Culebrilla"]},
    {"code": "B05", "displayName": "Measles", "category": "Infectious", "searchTerms": ["Rubeola", "Morbilli", "Sarampion"]},
    {"code": "B06", "displayName": "Rubella", "category": "Infectious", "searchTerms": ["German measles", "Rubella", "Rubeola"]},
    {"code": "B07", "displayName": "Viral warts", "category": "Infectious", "searchTerms": ["HPV warts", "Verruca", "Verrugas"]},
    {"code": "B08", "displayName": "Other viral infections characterized by skin lesions", "category": "Infectious", "searchTerms": ["Molluscum contagiosum", "Hand foot mouth"]},
    {"code": "B09", "displayName": "Unspecified viral infection characterized by skin lesions", "category": "Infectious", "searchTerms": ["Viral exanthem", "Eruption viral"]},
    {"code": "B15", "displayName": "Acute hepatitis A", "category": "Infectious", "searchTerms": ["HAV", "Hepatitis A", "Infectious hepatitis"]},
    {"code": "B16", "displayName": "Acute hepatitis B", "category": "Infectious", "searchTerms": ["HBV", "Hepatitis B", "Hepatitis serica"]},
    {"code": "B17", "displayName": "Other acute viral hepatitis", "category": "Infectious", "searchTerms": ["Hepatitis C", "HCV", "Hepatitis E"]},
    {"code": "B18", "displayName": "Chronic viral hepatitis", "category": "Infectious", "searchTerms": ["Chronic hepatitis B", "Chronic hepatitis C", "Hepatitis cronica"]},
    {"code": "B19", "displayName": "Unspecified viral hepatitis", "category": "Infectious", "searchTerms": ["Viral hepatitis NOS", "Hepatitis viral"]},
    {"code": "B20", "displayName": "Human immunodeficiency virus [HIV] disease", "category": "Infectious", "searchTerms": ["AIDS", "HIV", "VIH", "SIDA"]},
    {"code": "B24", "displayName": "Unspecified human immunodeficiency virus [HIV] infection", "category": "Infectious", "searchTerms": ["HIV infection NOS", "Infeccion por VIH"]},
    {"code": "B25", "displayName": "Cytomegaloviral disease", "category": "Infectious", "searchTerms": ["CMV", "Cytomegalovirus", "Citomegalovirus"]},
    {"code": "B26", "displayName": "Mumps", "category": "Infectious", "searchTerms": ["Parotitis", "Parotiditis", "Paperas"]},
    {"code": "B27", "displayName": "Infectious mononucleosis", "category": "Infectious", "searchTerms": ["EBV", "Epstein-Barr", "Mononucleosis", "Mono"]},
    {"code": "B30", "displayName": "Viral conjunctivitis", "category": "Infectious", "searchTerms": ["Pink eye", "Conjunctivitis viral", "Ojo rojo"]},
    {"code": "B33", "displayName": "Other viral diseases", "category": "Infectious", "searchTerms": ["Parvovirus B19", "Roseola", "Fifth disease"]},
    {"code": "B34", "displayName": "Viral infection of unspecified site", "category": "Infectious", "searchTerms": ["Viral infection NOS", "Infeccion viral"]},
    {"code": "B35", "displayName": "Dermatophytosis", "category": "Infectious", "searchTerms": ["Ringworm", "Tinea", "Dermatofitosis", "Tiña"]},
    {"code": "B36", "displayName": "Other superficial mycoses", "category": "Infectious", "searchTerms": ["Pityriasis versicolor", "Tinea nigra", "Piedra"]},
    {"code": "B37", "displayName": "Candidiasis", "category": "Infectious", "searchTerms": ["Yeast infection", "Candida albicans", "Thrush", "Candidiasis"]},
    {"code": "B38", "displayName": "Coccidioidomycosis", "category": "Infectious", "searchTerms": ["Valley fever", "Coccidioides", "Coccidioidomicosis"]},
    {"code": "B39", "displayName": "Histoplasmosis", "category": "Infectious", "searchTerms": ["Histoplasma capsulatum", "Histo"]},
    {"code": "B40", "displayName": "Blastomycosis", "category": "Infectious", "searchTerms": ["Blastomyces dermatitidis", "Blastomicosis"]},
    {"code": "B41", "displayName": "Paracoccidioidomycosis", "category": "Infectious", "searchTerms": ["South American blastomycosis", "Paracoccidioides"]},
    {"code": "B42", "displayName": "Sporotrichosis", "category": "Infectious", "searchTerms": ["Sporothrix schenckii", "Rose handler disease"]},
    {"code": "B43", "displayName": "Chromomycosis and pheomycotic abscess", "category": "Infectious", "searchTerms": ["Chromoblastomycosis"]},
    {"code": "B44", "displayName": "Aspergillosis", "category": "Infectious", "searchTerms": ["Aspergillus", "Aspergilosis", "ABPA"]},
    {"code": "B45", "displayName": "Cryptococcosis", "category": "Infectious", "searchTerms": ["Cryptococcus neoformans", "Criptococosis", "Meningitis criptococica"]},
    {"code": "B46", "displayName": "Zygomycosis", "category": "Infectious", "searchTerms": ["Mucormycosis", "Zygomycetes"]},
    {"code": "B47", "displayName": "Mycetoma", "category": "Infectious", "searchTerms": ["Madura foot", "Actinomycetoma", "Eumycetoma"]},
    {"code": "B48", "displayName": "Other mycoses, not elsewhere classified", "category": "Infectious", "searchTerms": ["Pneumocystis jirovecii", "PCP"]},
    {"code": "B49", "displayName": "Unspecified mycosis", "category": "Infectious", "searchTerms": ["Fungal infection NOS", "Hongos", "Micosis"]},
    {"code": "B50", "displayName": "Plasmodium falciparum malaria", "category": "Infectious", "searchTerms": ["Cerebral malaria", "Malaria falciparum", "Paludismo"]},
    {"code": "B51", "displayName": "Plasmodium vivax malaria", "category": "Infectious", "searchTerms": ["Vivax malaria", "Benign tertian malaria"]},
    {"code": "B52", "displayName": "Plasmodium malariae malaria", "category": "Infectious", "searchTerms": ["Quartan malaria", "Malaria malariae"]},
    {"code": "B53", "displayName": "Other parasitologically confirmed malaria", "category": "Infectious", "searchTerms": ["Ovale malaria", "Malaria mixta"]},
    {"code": "B54", "displayName": "Unspecified malaria", "category": "Infectious", "searchTerms": ["Malaria NOS", "Paludismo sin especificar"]},
    {"code": "B55", "displayName": "Leishmaniasis", "category": "Infectious", "searchTerms": ["Visceral leishmaniasis", "Kala-azar", "Cutaneous leishmaniasis"]},
    {"code": "B56", "displayName": "African trypanosomiasis", "category": "Infectious", "searchTerms": ["Sleeping sickness", "Trypanosoma brucei"]},
    {"code": "B57", "displayName": "Chagas disease", "category": "Infectious", "searchTerms": ["American trypanosomiasis", "Trypanosoma cruzi", "Mal de Chagas"]},
    {"code": "B58", "displayName": "Toxoplasmosis", "category": "Infectious", "searchTerms": ["Toxoplasma gondii", "Toxoplasma", "Toxoplasmosis"]},
    {"code": "B59", "displayName": "Pneumocystosis", "category": "Infectious", "searchTerms": ["Pneumocystis jirovecii pneumonia", "PCP", "Pneumonia por Pneumocystis"]},
    {"code": "B60", "displayName": "Other protozoal diseases", "category": "Infectious", "searchTerms": ["Babesiosis", "Microsporidiosis"]},
    {"code": "B64", "displayName": "Unspecified protozoal disease", "category": "Infectious", "searchTerms": ["Protozoal infection NOS"]},
    {"code": "B65", "displayName": "Schistosomiasis [bilharziasis]", "category": "Infectious", "searchTerms": ["Bilharzia", "Schistosoma", "Esquistosomiasis"]},
    {"code": "B66", "displayName": "Other fluke infections", "category": "Infectious", "searchTerms": ["Liver fluke", "Clonorchiasis", "Fascioliasis"]},
    {"code": "B67", "displayName": "Echinococcosis", "category": "Infectious", "searchTerms": ["Hydatid disease", "Echinococcus granulosus", "Quiste hidatidico"]},
    {"code": "B68", "displayName": "Taeniasis", "category": "Infectious", "searchTerms": ["Tapeworm", "Taenia saginata", "Taenia solium", "Teniasis"]},
    {"code": "B69", "displayName": "Cysticercosis", "category": "Infectious", "searchTerms": ["Neurocysticercosis", "Cisticercosis"]},
    {"code": "B70", "displayName": "Diphyllobothriasis and sparganosis", "category": "Infectious", "searchTerms": ["Fish tapeworm", "Broad tapeworm"]},
    {"code": "B71", "displayName": "Other cestode infections", "category": "Infectious", "searchTerms": ["Hymenolepis", "Dipyldium"]},
    {"code": "B72", "displayName": "Dracunculiasis", "category": "Infectious", "searchTerms": ["Guinea worm disease", "Dracunculus medinensis"]},
    {"code": "B73", "displayName": "Onchocerciasis", "category": "Infectious", "searchTerms": ["River blindness", "Onchocerca volvulus", "Oncocercosis"]},
    {"code": "B74", "displayName": "Filariasis", "category": "Infectious", "searchTerms": ["Lymphatic filariasis", "Wuchereria bancrofti", "Elephantiasis"]},
    {"code": "B75", "displayName": "Trichinellosis", "category": "Infectious", "searchTerms": ["Trichinosis", "Trichinella spiralis", "Triquinosis"]},
    {"code": "B76", "displayName": "Hookworm diseases", "category": "Infectious", "searchTerms": ["Ancylostomiasis", "Necator americanus", "Anquilostomiasis"]},
    {"code": "B77", "displayName": "Ascariasis", "category": "Infectious", "searchTerms": ["Roundworm", "Ascaris lumbricoides", "Ascaridiasis"]},
    {"code": "B78", "displayName": "Strongyloidiasis", "category": "Infectious", "searchTerms": ["Strongyloides stercoralis", "Estrongiloidiasis"]},
    {"code": "B79", "displayName": "Trichuriasis", "category": "Infectious", "searchTerms": ["Whipworm", "Trichuris trichiura"]},
    {"code": "B80", "displayName": "Enterobiasis", "category": "Infectious", "searchTerms": ["Pinworm", "Enterobius vermicularis", "Oxiuriasis"]},
    {"code": "B81", "displayName": "Other intestinal helminthiases", "category": "Infectious", "searchTerms": ["Intestinal worm NOS"]},
    {"code": "B82", "displayName": "Unspecified intestinal parasitism", "category": "Infectious", "searchTerms": ["Parasitosis intestinal", "Intestinal parasites"]},
    {"code": "B83", "displayName": "Other helminthiases", "category": "Infectious", "searchTerms": ["Visceral larva migrans", "Toxocariasis"]},
    {"code": "B85", "displayName": "Pediculosis and phthiriasis", "category": "Infectious", "searchTerms": ["Lice", "Head lice", "Pediculosis", "Piojos"]},
    {"code": "B86", "displayName": "Scabies", "category": "Infectious", "searchTerms": ["Sarcoptes scabiei", "Sarna", "Mange"]},
    {"code": "B87", "displayName": "Myiasis", "category": "Infectious", "searchTerms": ["Botfly", "Maggot infestation", "Miasis"]},
    {"code": "B88", "displayName": "Other infestations", "category": "Infectious", "searchTerms": ["Flea infestation", "Tick infestation"]},
    {"code": "B89", "displayName": "Unspecified parasitic disease", "category": "Infectious", "searchTerms": ["Parasitosis NOS", "Enfermedad parasitaria"]},
    {"code": "B90", "displayName": "Sequelae of tuberculosis", "category": "Infectious", "searchTerms": ["TB sequelae", "Secuelas de tuberculosis"]},
    {"code": "B91", "displayName": "Sequelae of poliomyelitis", "category": "Infectious", "searchTerms": ["Post-polio syndrome", "Secuelas de polio"]},
    {"code": "B94", "displayName": "Sequelae of other and unspecified infectious diseases", "category": "Infectious", "searchTerms": ["Post-infectious sequelae"]},
    {"code": "B95", "displayName": "Streptococcus and staphylococcus as cause of diseases", "category": "Infectious", "searchTerms": ["Group A strep", "Staph aureus", "Staphylococcus"]},
    {"code": "B96", "displayName": "Other bacterial agents as cause of diseases", "category": "Infectious", "searchTerms": ["E. coli", "Pseudomonas", "H. influenzae"]},
    {"code": "B97", "displayName": "Viral agents as cause of diseases", "category": "Infectious", "searchTerms": ["RSV", "Adenovirus", "Enterovirus", "Influenza"]},
    {"code": "B99", "displayName": "Other and unspecified infectious diseases", "category": "Infectious", "searchTerms": ["Infectious disease NOS", "Enfermedad infecciosa"]},

    # Chapter II: C00-D48 — Neoplasms
    {"code": "C00", "displayName": "Malignant neoplasm of lip", "category": "Neoplasms", "searchTerms": ["Lip cancer", "Cancer de labio"]},
    {"code": "C01", "displayName": "Malignant neoplasm of base of tongue", "category": "Neoplasms", "searchTerms": ["Tongue cancer", "Cancer de lengua"]},
    {"code": "C02", "displayName": "Malignant neoplasm of other and unspecified parts of tongue", "category": "Neoplasms", "searchTerms": ["Oral tongue cancer"]},
    {"code": "C03", "displayName": "Malignant neoplasm of gum", "category": "Neoplasms", "searchTerms": ["Gingival cancer", "Alveolar ridge cancer"]},
    {"code": "C04", "displayName": "Malignant neoplasm of floor of mouth", "category": "Neoplasms", "searchTerms": ["Oral cancer", "Suelo de boca"]},
    {"code": "C05", "displayName": "Malignant neoplasm of palate", "category": "Neoplasms", "searchTerms": ["Palatal cancer", "Paladar cancer"]},
    {"code": "C06", "displayName": "Malignant neoplasm of other and unspecified parts of mouth", "category": "Neoplasms", "searchTerms": ["Buccal cancer", "Buccal mucosa"]},
    {"code": "C07", "displayName": "Malignant neoplasm of parotid gland", "category": "Neoplasms", "searchTerms": ["Parotid cancer", "Parotid tumor"]},
    {"code": "C08", "displayName": "Malignant neoplasm of other major salivary glands", "category": "Neoplasms", "searchTerms": ["Salivary gland cancer", "Submandibular"]},
    {"code": "C09", "displayName": "Malignant neoplasm of tonsil", "category": "Neoplasms", "searchTerms": ["Tonsillar cancer", "Oropharyngeal cancer"]},
    {"code": "C10", "displayName": "Malignant neoplasm of oropharynx", "category": "Neoplasms", "searchTerms": ["Oropharyngeal cancer", "Cancer de orofaringe"]},
    {"code": "C11", "displayName": "Malignant neoplasm of nasopharynx", "category": "Neoplasms", "searchTerms": ["Nasopharyngeal cancer", "NPC", "Cancer nasofaringeo"]},
    {"code": "C12", "displayName": "Malignant neoplasm of pyriform sinus", "category": "Neoplasms",