// OrionHealth SNOMED Generator - Clinical concepts from SNOMED CT International
// Fuente: SNOMED CT International Edition, UMLS
const fs = require('fs');

const snomedData = [
  // --- Clinical Findings ---
  { code: "73211009", displayName: "Diabetes mellitus", category: "Endocrine/Metabolic", searchTerms: ["diabetes", "diabetes mellitus", "DM"] },
  { code: "44054006", displayName: "Diabetes mellitus type 2", category: "Endocrine/Metabolic", searchTerms: ["diabetes tipo 2", "DM2"] },
  { code: "46635009", displayName: "Diabetes mellitus type 1", category: "Endocrine/Metabolic", searchTerms: ["diabetes tipo 1", "DM1"] },
  { code: "59621000", displayName: "Essential hypertension", category: "Cardiovascular", searchTerms: ["hipertensión arterial", "presión alta", "HTA"] },
  { code: "414545008", displayName: "Hypertensive disorder", category: "Cardiovascular", searchTerms: ["hipertensión"] },
  { code: "53741008", displayName: "Coronary heart disease", category: "Cardiovascular", searchTerms: ["enfermedad coronaria", "cardiopatía isquémica"] },
  { code: "22298006", displayName: "Myocardial infarction", category: "Cardiovascular", searchTerms: ["infarto miocardio", "IAM", "ataque cardíaco"] },
  { code: "194828000", displayName: "Angina pectoris", category: "Cardiovascular", searchTerms: ["angina de pecho", "angor"] },
  { code: "195080001", displayName: "Atrial fibrillation", category: "Cardiovascular", searchTerms: ["fibrilación auricular", "FA", "arritmia"] },
  { code: "10273003", displayName: "Acute tonsillitis", category: "Infectious", searchTerms: ["amigdalitis", "anginas", "faringoamigdalitis"] },
  { code: "195967001", displayName: "Asthma", category: "Respiratory", searchTerms: ["asma", "bronquitis asmática"] },
  { code: "13645005", displayName: "Chronic obstructive pulmonary disease", category: "Respiratory", searchTerms: ["EPOC", "enfermedad pulmonar obstructiva crónica"] },
  { code: "233604007", displayName: "Pneumonia", category: "Respiratory", searchTerms: ["neumonía", "pulmonía"] },
  { code: "49727002", displayName: "Acute upper respiratory infection", category: "Respiratory", searchTerms: ["infección respiratoria alta", "IRA", "resfriado"] },
  { code: "36955009", displayName: "Bronchitis", category: "Respiratory", searchTerms: ["bronquitis"] },
  { code: "91857003", displayName: "Acute lower respiratory infection", category: "Respiratory", searchTerms: ["infección respiratoria baja"] },
  { code: "14760008", displayName: "Influenza", category: "Infectious", searchTerms: ["influenza", "gripe", "flu"] },
  { code: "6142004", displayName: "Influenza A", category: "Infectious", searchTerms: ["influenza A", "H1N1"] },
  { code: "34014006", displayName: "Vitamin D deficiency", category: "Endocrine/Metabolic", searchTerms: ["deficiencia vitamina D", "insuficiencia vitamina D"] },
  { code: "15167005", displayName: "Iron deficiency anemia", category: "Hematology", searchTerms: ["anemia ferropénica", "deficiencia de hierro", "anemia"] },
  { code: "271737000", displayName: "Anemia", category: "Hematology", searchTerms: ["anemia"] },
  { code: "840539006", displayName: "COVID-19", category: "Infectious", searchTerms: ["COVID-19", "coronavirus", "SARS-CoV-2"] },
  { code: "111930006", displayName: "Dengue fever", category: "Infectious", searchTerms: ["dengue", "fiebre del dengue"] },
  { code: "48340004", displayName: "Chikungunya", category: "Infectious", searchTerms: ["Chikungunya"] },
  { code: "240532009", displayName: "Zika virus disease", category: "Infectious", searchTerms: ["Zika"] },
  { code: "83028004", displayName: "Gastroenteritis", category: "GI", searchTerms: ["gastroenteritis", "diarrea infecciosa"] },
  { code: "47693006", displayName: "Gastroesophageal reflux disease", category: "GI", searchTerms: ["reflujo gastroesofágico", "ERGE", "acidez"] },
  { code: "196604008", displayName: "Peptic ulcer", category: "GI", searchTerms: ["úlcera péptica", "úlcera gástrica", "úlcera duodenal"] },
  { code: "266569009", displayName: "Irritable bowel syndrome", category: "GI", searchTerms: ["colon irritable", "SII", "síndrome intestino irritable"] },
  { code: "396331005", displayName: "Dyslipidemia", category: "Cardiovascular", searchTerms: ["dislipidemia", "colesterol alto", "hiperlipidemia"] },
  { code: "267432004", displayName: "Hypercholesterolemia", category: "Cardiovascular", searchTerms: ["hipercolesterolemia", "colesterol LDL alto"] },
  { code: "394801008", displayName: "Obesity", category: "Endocrine/Metabolic", searchTerms: ["obesidad", "sobrepeso", "IMC alto"] },
  { code: "414916001", displayName: "Overweight", category: "Endocrine/Metabolic", searchTerms: ["sobrepeso"] },
  { code: "73297009", displayName: "Urinary tract infection", category: "Renal/Urology", searchTerms: ["infección urinaria", "ITU", "cistitis"] },
  { code: "197659008", displayName: "Chronic kidney disease", category: "Renal/Urology", searchTerms: ["enfermedad renal crónica", "ERC", "insuficiencia renal"] },
  { code: "90688005", displayName: "Acute renal failure", category: "Renal/Urology", searchTerms: ["insuficiencia renal aguda", "IRA"] },
  { code: "394020004", displayName: "Arthritis", category: "Musculoskeletal", searchTerms: ["artritis"] },
  { code: "201820007", displayName: "Osteoarthritis", category: "Musculoskeletal", searchTerms: ["osteoartrosis", "artrosis"] },
  { code: "3723001", displayName: "Rheumatoid arthritis", category: "Autoimmune", searchTerms: ["artritis reumatoide"] },
  { code: "26929004", displayName: "Osteoporosis", category: "Musculoskeletal", searchTerms: ["osteoporosis"] },
  { code: "161891005", displayName: "Back pain", category: "Musculoskeletal", searchTerms: ["dolor lumbar", "lumbalgia", "dolor de espalda"] },
  { code: "95651005", displayName: "Low back pain", category: "Musculoskeletal", searchTerms: ["lumbago", "dolor lumbar bajo"] },
  { code: "24079001", displayName: "Hypothyroidism", category: "Endocrine/Metabolic", searchTerms: ["hipotiroidismo", "tiroides baja"] },
  { code: "190905008", displayName: "Hyperthyroidism", category: "Endocrine/Metabolic", searchTerms: ["hipertiroidismo", "tormenta tiroidea"] },
  { code: "254637007", displayName: "Hypokalemia", category: "Metabolic", searchTerms: ["hipopotasemia", "potasio bajo", "hipokalemia"] },
  { code: "89627008", displayName: "Hyperkalemia", category: "Metabolic", searchTerms: ["hiperpotasemia", "potasio alto", "hiperkalemia"] },
  { code: "190607003", displayName: "Hyponatremia", category: "Metabolic", searchTerms: ["hiponatremia", "sodio bajo"] },
  { code: "237841002", displayName: "Hypernatremia", category: "Metabolic", searchTerms: ["hipernatremia", "sodio alto"] },
  { code: "237835009", displayName: "Metabolic acidosis", category: "Metabolic", searchTerms: ["acidosis metabólica"] },
  { code: "237835009", displayName: "Metabolic alkalosis", category: "Metabolic", searchTerms: ["alcalosis metabólica"] },
  { code: "192127007", displayName: "Major depressive disorder", category: "Psychiatry", searchTerms: ["depresión mayor", "depresión clínica", "trastorno depresivo"] },
  { code: "191736004", displayName: "Generalized anxiety disorder", category: "Psychiatry", searchTerms: ["ansiedad generalizada", "TAG", "trastorno de ansiedad"] },
  { code: "193462001", displayName: "Dementia", category: "Psychiatry/Neurology", searchTerms: ["demencia", "Alzheimer"] },
  { code: "416287000", displayName: "Alzheimer disease", category: "Psychiatry/Neurology", searchTerms: ["Alzheimer", "EA"] },
  { code: "192949004", displayName: "Schizophrenia", category: "Psychiatry", searchTerms: ["esquizofrenia"] },
  { code: "35489007", displayName: "Depressive disorder", category: "Psychiatry", searchTerms: ["depresión", "trastorno depresivo"] },
  { code: "26095005", displayName: "Panic disorder", category: "Psychiatry", searchTerms: ["ataque de pánico", "trastorno de pánico"] },
  { code: "731000119102", displayName: "Post-traumatic stress disorder", category: "Psychiatry", searchTerms: ["TEPT", "estrés postraumático", "PTSD"] },
  { code: "230220000", displayName: "Migraine", category: "Neurology", searchTerms: ["migraña", "jaqueca"] },
  { code: "25064002", displayName: "Headache", category: "Neurology", searchTerms: ["cefalea", "dolor de cabeza"] },
  { code: "188475003", displayName: "Tension headache", category: "Neurology", searchTerms: ["cefalea tensional"] },
  { code: "230690007", displayName: "Cerebrovascular accident", category: "Cardiovascular", searchTerms: ["ACV", "derrame cerebral", "stroke", "infarto cerebral"] },
  { code: "194804000", displayName: "Transient ischemic attack", category: "Cardiovascular", searchTerms: ["AIT", "ataque isquémico transitorio"] },
  { code: "128613002", displayName: "Seizure disorder", category: "Neurology", searchTerms: ["epilepsia", "convulsiones", "crisis epiléptica"] },
  { code: "230432002", displayName: "Parkinson disease", category: "Neurology", searchTerms: ["Parkinson", "enfermedad de Parkinson"] },
  { code: "398254007", displayName: "Multiple sclerosis", category: "Neurology", searchTerms: ["esclerosis múltiple", "EM"] },
  { code: "722892000", displayName: "Benign prostatic hyperplasia", category: "Urology", searchTerms: ["HPB", "hiperplasia prostática benigna", "próstata"] },
  { code: "254845009", displayName: "Erectile dysfunction", category: "Urology", searchTerms: ["disfunción eréctil", "impotencia"] },
  { code: "432041000", displayName: "Bacterial infection", category: "Infectious", searchTerms: ["infección bacteriana"] },
  { code: "33995002", displayName: "Viral infection", category: "Infectious", searchTerms: ["infección viral"] },
  { code: "281789004", displayName: "Fungal infection", category: "Infectious", searchTerms: ["infección micótica", "hongos"] },
  { code: "4241000179105", displayName: "Parasitic infection", category: "Infectious", searchTerms: ["parásitos", "infección parasitaria"] },
  { code: "928000", displayName: "Allergic rhinitis", category: "Allergy/Immunology", searchTerms: ["rinitis alérgica", "alergia", "fiebre del heno"] },
  { code: "91930004", displayName: "Allergy to penicillin", category: "Allergy/Immunology", searchTerms: ["alergia a penicilina"] },
  { code: "418471000", displayName: "Drug allergy", category: "Allergy/Immunology", searchTerms: ["alergia a medicamentos", "alergia farmacológica"] },
  { code: "91935004", displayName: "Food allergy", category: "Allergy/Immunology", searchTerms: ["alergia alimentaria"] },
  { code: "230690007", displayName: "Atopic dermatitis", category: "Dermatology", searchTerms: ["dermatitis atópica", "eczema"] },
  { code: "402399000", displayName: "Contact dermatitis", category: "Dermatology", searchTerms: ["dermatitis de contacto"] },
  { code: "394885002", displayName: "Eczema", category: "Dermatology", searchTerms: ["eczema", "eccema"] },
  { code: "247440004", displayName: "Acne vulgaris", category: "Dermatology", searchTerms: ["acné", "acné vulgar", "barros"] },
  { code: "3744003", displayName: "Psoriasis", category: "Dermatology", searchTerms: ["psoriasis"] },
  { code: "402762003", displayName: "Cellulitis", category: "Dermatology/Infectious", searchTerms: ["celulitis infecciosa"] },
  { code: "77293002", displayName: "Fracture of bone", category: "Trauma", searchTerms: ["fractura ósea", "hueso roto"] },
  { code: "125605004", displayName: "Fracture of radius", category: "Trauma", searchTerms: ["fractura de radio"] },
  { code: "71620000", displayName: "Fracture of femur", category: "Trauma", searchTerms: ["fractura de fémur"] },
  { code: "43984008", displayName: "Sprain of ankle", category: "Trauma", searchTerms: ["esguince de tobillo"] },
  { code: "76915007", displayName: "Headache/migraine", category: "Neurology", searchTerms: ["dolor de cabeza", "cefalea"] },
];

const output = {
  metadata: {
    standard: "SNOMED CT",
    version: "International Edition 2024",
    lastUpdated: "2026-05-02",
    source: "SNOMED International / NLM UMLS",
    sourceUrl: "https://www.snomed.org/",
    totalCount: snomedData.length
  },
  data: snomedData
};

fs.writeFileSync('E:\\scripts-python\\orionhealth\\medical-standards\\snomed.json', JSON.stringify(output, null, 2), 'utf8');
console.log(`✅ SNOMED: ${snomedData.length} entries written`);
console.log(`📏 File size: ${(fs.statSync('E:\\scripts-python\\orionhealth\\medical-standards\\snomed.json').size / 1024).toFixed(1)} KB`);
