#!/usr/bin/env python3
"""
Generate all 4 medical standards files for OrionHealth with real codes.
ICD-10: 300+ codes, LOINC: 50+, RxNorm: 100+, SNOMED: 50+
"""
import json, os

OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "medical-standards")
os.makedirs(OUT_DIR, exist_ok=True)

def write_json(filename, obj):
    path = os.path.join(OUT_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)
    size_kb = os.path.getsize(path) / 1024
    print(f"  ✓ {filename}: {len(obj['data'])} entries, {size_kb:.1f} KB")
    return path

# ==============================================================================
# ICD-10 — 300+ codes covering all chapters
# ==============================================================================
icd10_data = []
categories = {
    "Infectious": [
        ("A00", "Cholera", ["Colera", "Vibrio cholerae"]),
        ("A01", "Typhoid and paratyphoid fevers", ["Typhoid", "Fiebre tifoidea", "Salmonella typhi"]),
        ("A02", "Other salmonella infections", ["Salmonellosis", "Salmonela"]),
        ("A03", "Shigellosis", ["Bacillary dysentery", "Disenteria bacilar"]),
        ("A04", "Other bacterial intestinal infections", ["E. coli enteritis", "Campylobacter"]),
        ("A05", "Other bacterial foodborne intoxications", ["Food poisoning", "Botulism"]),
        ("A06", "Amebiasis", ["Amebic dysentery", "Entamoeba histolytica"]),
        ("A07", "Other protozoal intestinal diseases", ["Giardiasis", "Cryptosporidiosis"]),
        ("A08", "Viral intestinal infections", ["Rotavirus", "Norovirus", "Gastroenteritis viral"]),
        ("A09", "Infectious gastroenteritis/colitis", ["Infectious diarrhea", "Gastroenteritis"]),
        ("A15", "Respiratory tuberculosis", ["Pulmonary TB", "TBC", "Tuberculosis pulmonar"]),
        ("A16", "Respiratory tuberculosis (unconfirmed)", ["Tuberculosis", "TB"]),
        ("A17", "Tuberculosis of nervous system", ["Tuberculous meningitis"]),
        ("A18", "Tuberculosis of other organs", ["Extrapulmonary TB", "TB lymphadenitis"]),
        ("A19", "Miliary tuberculosis", ["Disseminated TB", "Tuberculosis miliar"]),
        ("A20", "Plague", ["Yersinia pestis", "Bubonic plague", "Peste"]),
        ("A21", "Tularemia", ["Rabbit fever", "Francisella tularensis"]),
        ("A22", "Anthrax", ["Bacillus anthracis", "Carbunco"]),
        ("A23", "Brucellosis", ["Undulant fever", "Brucella", "Fiebre de Malta"]),
        ("A27", "Leptospirosis", ["Weil disease", "Leptospira"]),
        ("A30", "Leprosy [Hansen disease]", ["Hansen disease", "Lepra"]),
        ("A31", "Other mycobacterial infection", ["NTM", "Mycobacterium avium"]),
        ("A32", "Listeriosis", ["Listeria monocytogenes", "Listeria"]),
        ("A35", "Other tetanus", ["Tetanos", "Lockjaw", "Trismus"]),
        ("A36", "Diphtheria", ["Corynebacterium diphtheriae", "Difteria"]),
        ("A37", "Whooping cough", ["Pertussis", "Bordetella", "Tos ferina"]),
        ("A38", "Scarlet fever", ["Scarlatina", "Fiebre escarlata"]),
        ("A39", "Meningococcal infection", ["Meningococcal meningitis", "Neisseria"]),
        ("A40", "Streptococcal sepsis", ["Group B strep", "Streptococcus"]),
        ("A41", "Other sepsis", ["Septicemia", "Sepsis bacteriana"]),
        ("A46", "Erysipelas", ["Erisipela", "St. Anthony fire"]),
        ("A49", "Bacterial infection, unspecified", ["Bacterial infection NOS"]),
        ("A50", "Congenital syphilis", ["Treponema pallidum"]),
        ("A51", "Early syphilis", ["Primary syphilis", "Chancre"]),
        ("A52", "Late syphilis", ["Tertiary syphilis", "Neurosyphilis"]),
        ("A53", "Syphilis, unspecified", ["Sifilis", "Lues"]),
        ("A54", "Gonococcal infection", ["Gonorrhea", "Neisseria gonorrhoeae", "Gonorrea"]),
        ("A55", "Chlamydial lymphogranuloma", ["LGV", "Lymphogranuloma venereum"]),
        ("A56", "Other chlamydial STD", ["Chlamydia trachomatis", "Clamidia"]),
        ("A59", "Trichomoniasis", ["Trichomonas vaginalis", "Tricomoniasis"]),
        ("A60", "Anogenital herpesviral infection", ["Genital herpes", "HSV-2", "Herpes genital"]),
        ("A64", "Unspecified sexually transmitted disease", ["STD NOS", "ETS", "ITS"]),
        ("A69", "Other spirochetal infections", ["Lyme disease", "Borrelia burgdorferi"]),
        ("A71", "Trachoma", ["Chlamydia trachomatis eye"]),
        ("A75", "Typhus fever", ["Rickettsia prowazekii", "Tifo"]),
        ("A77", "Spotted fever [tick-borne]", ["Rocky Mountain spotted fever", "Rickettsia"]),
        ("A78", "Q fever", ["Coxiella burnetii"]),
        ("A79", "Other rickettsioses", ["Ehrlichiosis", "Anaplasmosis"]),
        ("A80", "Acute poliomyelitis", ["Polio", "Poliomielitis"]),
        ("A81", "Atypical virus CNS infections", ["CJD", "Prion disease", "Kuru"]),
        ("A82", "Rabies", ["Hydrophobia", "Lyssavirus", "Rabia"]),
        ("A83", "Mosquito-borne viral encephalitis", ["Japanese encephalitis", "West Nile"]),
        ("A84", "Tick-borne viral encephalitis", ["TBE", "FSME"]),
        ("A86", "Unspecified viral encephalitis", ["Encefalitis viral"]),
        ("A87", "Viral meningitis", ["Aseptic meningitis"]),
        ("A90", "Dengue fever", ["Breakbone fever", "Dengue clasico"]),
        ("A91", "Dengue hemorrhagic fever", ["DHF", "Dengue hemorragico"]),
        ("A92", "Other mosquito-borne viral fevers", ["Chikungunya", "Zika virus"]),
        ("A95", "Yellow fever", ["Yellow jack", "Fiebre amarilla"]),
        ("A96", "Arenaviral hemorrhagic fever", ["Lassa fever", "Junin virus"]),
        ("A98", "Other viral hemorrhagic fevers", ["Ebola", "Marburg", "Crimean-Congo"]),
        ("A99", "Viral hemorrhagic fever, unspecified", ["Viral hemorrhagic fever NOS", "VHF"]),
        ("B00", "Herpesviral [herpes simplex] infections", ["HSV", "Cold sores", "Herpes labial"]),
        ("B01", "Varicella [chickenpox]", ["Chickenpox", "Varicela"]),
        ("B02", "Zoster [herpes zoster]", ["Shingles", "Culebrilla"]),
        ("B05", "Measles", ["Rubeola", "Sarampion"]),
        ("B06", "Rubella", ["German measles", "Rubella"]),
        ("B07", "Viral warts", ["HPV warts", "Verruca", "Verrugas"]),
        ("B08", "Other viral skin infections", ["Molluscum contagiosum"]),
        ("B15", "Acute hepatitis A", ["HAV", "Hepatitis A"]),
        ("B16", "Acute hepatitis B", ["HBV", "Hepatitis B"]),
        ("B17", "Other acute viral hepatitis", ["Hepatitis C", "HCV", "Hepatitis E"]),
        ("B18", "Chronic viral hepatitis", ["Chronic hepatitis B", "Chronic hepatitis C"]),
        ("B19", "Unspecified viral hepatitis", ["Viral hepatitis NOS"]),
        ("B20", "HIV disease", ["AIDS", "HIV", "VIH", "SIDA"]),
        ("B24", "Unspecified HIV infection", ["HIV infection NOS", "Infeccion por VIH"]),
        ("B25", "Cytomegaloviral disease", ["CMV", "Cytomegalovirus", "Citomegalovirus"]),
        ("B26", "Mumps", ["Parotitis", "Parotiditis", "Paperas"]),
        ("B27", "Infectious mononucleosis", ["EBV", "Epstein-Barr", "Mono"]),
        ("B30", "Viral conjunctivitis", ["Pink eye", "Ojo rojo"]),
        ("B34", "Viral infection, unspecified site", ["Viral infection NOS"]),
        ("B35", "Dermatophytosis", ["Ringworm", "Tinea", "Tiña"]),
        ("B36", "Other superficial mycoses", ["Pityriasis versicolor"]),
        ("B37", "Candidiasis", ["Yeast infection", "Candida", "Thrush", "Candidiasis"]),
        ("B38", "Coccidioidomycosis", ["Valley fever", "Coccidioides"]),
        ("B39", "Histoplasmosis", ["Histoplasma capsulatum"]),
        ("B40", "Blastomycosis", ["Blastomyces dermatitidis"]),
        ("B44", "Aspergillosis", ["Aspergillus", "ABPA", "Aspergilosis"]),
        ("B45", "Cryptococcosis", ["Cryptococcus neoformans"]),
        ("B46", "Zygomycosis", ["Mucormycosis", "Zygomycetes"]),
        ("B48", "Other mycoses NEC", ["Pneumocystis jirovecii", "PCP"]),
        ("B49", "Unspecified mycosis", ["Fungal infection NOS", "Hongos", "Micosis"]),
        ("B50", "Plasmodium falciparum malaria", ["Cerebral malaria", "Paludismo"]),
        ("B51", "Plasmodium vivax malaria", ["Vivax malaria"]),
        ("B52", "Plasmodium malariae malaria", ["Quartan malaria"]),
        ("B53", "Other malaria", ["Malaria mixta"]),
        ("B54", "Unspecified malaria", ["Malaria NOS", "Paludismo"]),
        ("B55", "Leishmaniasis", ["Kala-azar", "Visceral leishmaniasis"]),
        ("B56", "African trypanosomiasis", ["Sleeping sickness", "Trypanosoma"]),
        ("B57", "Chagas disease", ["American trypanosomiasis", "Trypanosoma cruzi"]),
        ("B58", "Toxoplasmosis", ["Toxoplasma gondii", "Toxoplasmosis"]),
        ("B59", "Pneumocystosis", ["Pneumocystis pneumonia", "PCP"]),
        ("B65", "Schistosomiasis [bilharziasis]", ["Bilharzia", "Schistosoma"]),
        ("B67", "Echinococcosis", ["Hydatid disease", "Quiste hidatidico"]),
        ("B68", "Taeniasis", ["Tapeworm", "Taenia", "Teniasis"]),
        ("B69", "Cysticercosis", ["Neurocysticercosis", "Cisticercosis"]),
        ("B73", "Onchocerciasis", ["River blindness", "Onchocerca"]),
        ("B74", "Filariasis", ["Lymphatic filariasis", "Elephantiasis"]),
        ("B75", "Trichinellosis", ["Trichinosis", "Triquinosis"]),
        ("B76", "Hookworm diseases", ["Ancylostomiasis", "Anquilostomiasis"]),
        ("B77", "Ascariasis", ["Roundworm", "Ascaris lumbricoides"]),
        ("B78", "Strongyloidiasis", ["Strongyloides stercoralis"]),
        ("B80", "Enterobiasis", ["Pinworm", "Oxiuriasis"]),
        ("B82", "Unspecified intestinal parasitism", ["Parasitosis intestinal"]),
        ("B85", "Pediculosis and phthiriasis", ["Lice", "Head lice", "Piojos"]),
        ("B86", "Scabies", ["Sarcoptes scabiei", "Sarna"]),
        ("B89", "Unspecified parasitic disease", ["Parasitosis NOS"]),
        ("B90", "Sequelae of tuberculosis", ["TB sequelae"]),
        ("B91", "Sequelae of poliomyelitis", ["Post-polio syndrome"]),
        ("B94", "Sequelae of other infectious diseases", ["Post-infectious sequelae"]),
        ("B95", "Strep/staph as disease cause", ["Group A strep", "Staph aureus"]),
        ("B96", "Other bacterial agents as cause", ["E. coli", "Pseudomonas", "H. influenzae"]),
        ("B97", "Viral agents as disease cause", ["RSV", "Adenovirus", "Influenza"]),
        ("B99", "Other infectious diseases", ["Infectious disease NOS"]),
    ],
    "Neoplasms": [
        ("C00", "Malignant neoplasm of lip", ["Lip cancer"]),
        ("C01", "Malignant neoplasm of base of tongue", ["Tongue cancer"]),
        ("C02", "Malignant neoplasm of other tongue parts", ["Oral tongue cancer"]),
        ("C03", "Malignant neoplasm of gum", ["Gingival cancer"]),
        ("C04", "Malignant neoplasm of floor of mouth", ["Oral cancer"]),
        ("C05", "Malignant neoplasm of palate", ["Palatal cancer"]),
        ("C06", "Malignant neoplasm of other mouth parts", ["Buccal mucosa cancer"]),
        ("C07", "Malignant neoplasm of parotid gland", ["Parotid cancer"]),
        ("C08", "Malignant neoplasm of other salivary glands", ["Salivary gland cancer"]),
        ("C09", "Malignant neoplasm of tonsil", ["Tonsillar cancer"]),
        ("C10", "Malignant neoplasm of oropharynx", ["Oropharyngeal cancer"]),
        ("C11", "Malignant neoplasm of nasopharynx", ["Nasopharyngeal cancer", "NPC"]),
        ("C12", "Malignant neoplasm of pyriform sinus", ["Hypopharyngeal cancer"]),
        ("C13", "Malignant neoplasm of hypopharynx", ["Hypopharyngeal cancer"]),
        ("C14", "Malignant neoplasm of lip/oral cavity/pharynx NEC", ["Head and neck cancer"]),
        ("C15", "Malignant neoplasm of esophagus", ["Esophageal cancer"]),
        ("C16", "Malignant neoplasm of stomach", ["Gastric cancer", "Stomach cancer"]),
        ("C17", "Malignant neoplasm of small intestine", ["Small bowel cancer"]),
        ("C18", "Malignant neoplasm of colon", ["Colon cancer", "Colorectal cancer"]),
        ("C19", "Malignant neoplasm of rectosigmoid junction", ["Rectosigmoid cancer"]),
        ("C20", "Malignant neoplasm of rectum", ["Rectal cancer"]),
        ("C21", "Malignant neoplasm of anus", ["Anal cancer"]),
        ("C22", "Malignant neoplasm of liver", ["Hepatocellular carcinoma", "HCC", "Liver cancer"]),
        ("C23", "Malignant neoplasm of gallbladder", ["Gallbladder cancer"]),
        ("C24", "Malignant neoplasm of biliary tract", ["Cholangiocarcinoma"]),
        ("C25", "Malignant neoplasm of pancreas", ["Pancreatic cancer", "Pancreas cancer"]),
        ("C26", "Malignant neoplasm of other digestive organs", ["Digestive cancer NOS"]),
        ("C30", "Malignant neoplasm of nasal cavity", ["Nasal cancer"]),
        ("C31", "Malignant neoplasm of sinuses", ["Sinus cancer"]),
        ("C32", "Malignant neoplasm of larynx", ["Laryngeal cancer", "Cancer de laringe"]),
        ("C33", "Malignant neoplasm of trachea", ["Tracheal cancer"]),
        ("C34", "Malignant neoplasm of bronchus and lung", ["Lung cancer", "NSCLC", "SCLC"]),
        ("C37", "Malignant neoplasm of thymus", ["Thymoma", "Thymic cancer"]),
        ("C38", "Malignant neoplasm of heart/mediastinum/pleura", ["Mediastinal cancer"]),
        ("C40", "Malignant neoplasm of bone/cartilage", ["Bone cancer"]),
        ("C41", "Malignant neoplasm of other bone", ["Chondrosarcoma"]),
        ("C43", "Malignant melanoma of skin", ["Melanoma", "Melanoma maligno"]),
        ("C44", "Other malignant neoplasm of skin", ["Basal cell carcinoma", "Squamous cell skin"]),
        ("C45", "Mesothelioma", ["Malignant mesothelioma", "Pleural mesothelioma"]),
        ("C46", "Kaposi sarcoma", ["KS", "Kaposi sarcoma"]),
        ("C47", "Malignant neoplasm of peripheral nerves", ["Neurofibrosarcoma"]),
        ("C48", "Malignant neoplasm of retroperitoneum", ["Retroperitoneal cancer"]),
        ("C49", "Malignant neoplasm of connective/soft tissue", ["Sarcoma", "Soft tissue sarcoma"]),
        ("C50", "Malignant neoplasm of breast", ["Breast cancer", "Breast carcinoma", "Cancer de mama"]),
        ("C51", "Malignant neoplasm of vulva", ["Vulvar cancer"]),
        ("C52", "Malignant neoplasm of vagina", ["Vaginal cancer"]),
        ("C53", "Malignant neoplasm of cervix uteri", ["Cervical cancer", "Cancer de cuello uterino"]),
        ("C54", "Malignant neoplasm of corpus uteri", ["Endometrial cancer", "Uterine cancer"]),
        ("C55", "Malignant neoplasm of uterus unspecified", ["Uterine cancer NOS"]),
        ("C56", "Malignant neoplasm of ovary", ["Ovarian cancer", "Cancer de ovario"]),
        ("C57", "Malignant neoplasm of other female genital", ["Fallopian tube cancer"]),
        ("C58", "Malignant neoplasm of placenta", ["Choriocarcinoma"]),
        ("C60", "Malignant neoplasm of penis", ["Penile cancer"]),
        ("C61", "Malignant neoplasm of prostate", ["Prostate cancer", "Prostatic cancer"]),
        ("C62", "Malignant neoplasm of testis", ["Testicular cancer", "Germ cell tumor"]),
        ("C63", "Malignant neoplasm of other male genital", ["Male genital cancer NOS"]),
        ("C64", "Malignant neoplasm of kidney", ["Renal cell carcinoma", "RCC", "Renal cancer"]),
        ("C65", "Malignant neoplasm of renal pelvis", ["Transitional cell renal"]),
        ("C66", "Malignant neoplasm of ureter", ["Ureteral cancer"]),
        ("C67", "Malignant neoplasm of bladder", ["Bladder cancer", "Urothelial cancer"]),
        ("C68", "Malignant neoplasm of other urinary organs", ["Urethral cancer"]),
        ("C69", "Malignant neoplasm of eye and adnexa", ["Ocular cancer", "Retinoblastoma"]),
        ("C70", "Malignant neoplasm of meninges", ["Meningioma malignant"]),
        ("C71", "Malignant neoplasm of brain", ["Brain cancer", "Glioma", "Glioblastoma"]),
        ("C72", "Malignant neoplasm of spinal cord/CNS", ["Spinal cord tumor"]),
        ("C73", "Malignant neoplasm of thyroid gland", ["Thyroid cancer", "Papillary thyroid"]),
        ("C74", "Malignant neoplasm of adrenal gland", ["Adrenal cancer", "Pheochromocytoma"]),
        ("C75", "Malignant neoplasm of other endocrine", ["Pituitary gland tumor"]),
        ("C76", "Malignant neoplasm of ill-defined sites", ["Metastatic NOS"]),
        ("C77", "Secondary neoplasm of lymph nodes", ["Lymph node metastasis"]),
        ("C78", "Secondary neoplasm of respiratory/digestive", ["Metastatic to lung", "Metastatic to liver"]),
        ("C79", "Secondary neoplasm of other sites", ["Bone metastasis", "Brain metastasis"]),
        ("C80", "Malignant neoplasm without specification", ["Cancer NOS", "Cancer sin especificar"]),
        ("C81", "Hodgkin lymphoma", ["Hodgkin disease", "HL"]),
        ("C82", "Follicular lymphoma", ["FL", "Follicular NHL"]),
        ("C83", "Non-follicular lymphoma", ["Diffuse large B-cell", "DLBCL"]),
        ("C84", "Mature T/NK-cell lymphomas", ["T-cell lymphoma", "NK lymphoma"]),
        ("C85", "Other NHL types", ["Non-Hodgkin lymphoma NOS"]),
        ("C86", "Other T/NK-cell lymphomas", ["Mycosis fungoides", "Sezary"]),
        ("C88", "Malignant immunoproliferative diseases", ["Waldenstrom macroglobulinemia"]),
        ("C90", "Multiple myeloma", ["Myeloma", "Plasma cell myeloma", "Mieloma multiple"]),
        ("C91", "Lymphoid leukemia", ["ALL", "CLL", "Leucemia linfatica"]),
        ("C92", "Myeloid leukemia", ["AML", "CML", "Leucemia mieloide"]),
        ("C93", "Monocytic leukemia", ["AMoL"]),
        ("C94", "Other specified cell type leukemias", ["Leukemia NOS"]),
        ("C95", "Leukemia of unspecified cell type", ["Leucemia sin especificar"]),
        ("C96", "Other malignant lymphoid/hematopoietic", ["Histiocytic sarcoma"]),
        ("D00", "Carcinoma in situ of oral/esophagus/stomach", ["CIS oral"]),
        ("D01", "Carcinoma in situ of other digestive", ["CIS digestive"]),
        ("D02", "Carcinoma in situ of respiratory", ["CIS lung"]),
        ("D03", "Melanoma in situ", ["Melanoma in situ"]),
        ("D04", "Carcinoma in situ of skin", ["SCC in situ", "Bowen disease"]),
        ("D05", "Carcinoma in situ of breast", ["DCIS", "LCIS"]),
        ("D06", "Carcinoma in situ of cervix", ["CIN III", "Cervical CIS"]),
        ("D07", "Carcinoma in situ of other genital", ["CIS genital"]),
        ("D09", "Carcinoma in situ of other sites", ["CIS NOS"]),
        ("D10", "Benign neoplasm of mouth/pharynx", ["Benign oral tumor"]),
        ("D11", "Benign neoplasm of salivary glands", ["Salivary adenoma"]),
        ("D12", "Benign neoplasm of colon/rectum/anus", ["Colonic polyp", "Adenomatous polyp"]),
        ("D13", "Benign neoplasm of other digestive", ["Benign gastric tumor"]),
        ("D14", "Benign neoplasm of respiratory", ["Lung hamartoma"]),
        ("D15", "Benign neoplasm of intrathoracic organs", ["Mediastinal adenoma"]),
        ("D16", "Benign neoplasm of bone and cartilage", ["Osteoma", "Osteochondroma"]),
        ("D17", "Benign lipomatous neoplasm", ["Lipoma"]),
        ("D18", "Hemangioma", ["Hemangioma", "Angioma"]),
        ("D19", "Benign neoplasm of mesothelial tissue", ["Mesothelial cyst"]),
        ("D20", "Benign neoplasm of peritoneum/retroperitoneum", ["Retroperitoneal cyst"]),
        ("D21", "Other benign connective/soft tissue", ["Fibroma", "Desmoid"]),
        ("D22", "Melanocytic nevi", ["Nevus", "Mole", "Lunar"]),
        ("D23", "Other benign skin neoplasms", ["Seborrheic keratosis", "Skin tag"]),
        ("D24", "Benign neoplasm of breast", ["Fibroadenoma"]),
        ("D25", "Leiomyoma of uterus", ["Fibroids", "Uterine fibroids", "Miomas"]),
        ("D26", "Other benign uterine neoplasms", ["Endometrial polyp"]),
        ("D27", "Benign neoplasm of ovary", ["Ovarian cystadenoma"]),
        ("D28", "Benign neoplasm of other female genital", ["Vaginal adenosis"]),
        ("D29", "Benign neoplasm of male genital", ["Benign prostatic hyperplasia"]),
        ("D30", "Benign neoplasm of urinary organs", ["Renal angiomyolipoma"]),
        ("D31", "Benign neoplasm of eye and adnexa", ["Choroidal nevus"]),
        ("D32", "Benign neoplasm of meninges", ["Meningioma"]),
        ("D33", "Benign neoplasm of brain and CNS", ["Benign brain tumor"]),
        ("D34", "Benign neoplasm of thyroid gland", ["Thyroid adenoma", "Thyroid nodule"]),
        ("D35", "Benign neoplasm of other endocrine", ["Pituitary adenoma"]),
        ("D36", "Benign neoplasm of unspecified sites", ["Benign neoplasm NOS"]),
        ("D37", "Neoplasm uncertain oral/digestive", ["Gastric GIST"]),
        ("D38", "Neoplasm uncertain respiratory", ["Lung neoplasm uncertain"]),
        ("D39", "Neoplasm uncertain female genital", ["Ovarian borderline"]),
        ("D40", "Neoplasm uncertain male genital", ["Prostate PIN"]),
        ("D41", "Neoplasm uncertain urinary", ["Bladder neoplasm uncertain"]),
        ("D42", "Neoplasm uncertain meninges", ["Atypical meningioma"]),
        ("D43", "Neoplasm uncertain brain/CNS", ["Low grade glioma"]),
        ("D44", "Neoplasm uncertain endocrine", ["Adrenal incidentaloma"]),
        ("D45", "Polycythemia vera", ["PV", "Polycythemia vera"]),
        ("D46", "Myelodysplastic syndromes", ["MDS", "Preleukemia"]),
        ("D47", "Other lymphoid/hematopoietic uncertain", ["MGUS", "Monoclonal gammopathy"]),
        ("D48", "Neoplasm uncertain other sites", ["Neoplasm uncertain NOS"]),
    ],
    "Blood & Immune": [
        ("D50", "Iron deficiency anemia", ["IDA", "Anemia ferropenica"]),
        ("D51", "Vitamin B12 deficiency anemia", ["Pernicious anemia", "Pernicious"]),
        ("D52", "Folate deficiency anemia", ["Folic acid deficiency"]),
        ("D53", "Other nutritional anemias", ["Nutritional anemia NOS"]),
        ("D55", "Anemia due to enzyme disorders", ["G6PD deficiency anemia"]),
        ("D56", "Thalassemia", ["Beta thalassemia", "Cooley anemia"]),
        ("D57", "Sickle cell disorders", ["SCD", "Sickle cell disease"]),
        ("D58", "Other hereditary hemolytic anemias", ["Hereditary spherocytosis"]),
        ("D59", "Acquired hemolytic anemia", ["Autoimmune hemolytic", "AIHA"]),
        ("D60", "Acquired pure red cell aplasia", ["PRCA"]),
        ("D61", "Other aplastic anemias", ["Aplastic anemia"]),
        ("D62", "Acute posthemorrhagic anemia", ["Acute blood loss anemia"]),
        ("D63", "Anemia in chronic diseases", ["Anemia of chronic disease"]),
        ("D64", "Other anemias", ["Anemia NOS", "Anemia sin especificar"]),
        ("D65", "Disseminated intravascular coagulation", ["DIC", "Coagulopatia"]),
        ("D66", "Hereditary factor VIII deficiency", ["Hemophilia A", "Classic hemophilia"]),
        ("D67", "Hereditary factor IX deficiency", ["Hemophilia B", "Christmas disease"]),
        ("D68", "Other coagulation defects", ["Von Willebrand disease", "VWD"]),
        ("D69", "Purpura and hemorrhagic conditions", ["ITP", "Immune thrombocytopenia"]),
        ("D70", "Neutropenia", ["Agranulocytosis"]),
        ("D71", "Functional neutrophil disorders", ["Chediak-Higashi"]),
        ("D72", "Other WBC disorders", ["Leukocytosis", "Eosinophilia"]),
        ("D73", "Diseases of spleen", ["Splenomegaly", "Bazo"]),
        ("D75", "Other blood-forming organ diseases", ["Myelofibrosis"]),
        ("D80", "Immunodeficiency antibody defects", ["Hypogammaglobulinemia"]),
        ("D81", "Combined immunodeficiencies", ["SCID", "Severe combined ID"]),
        ("D82", "Immunodeficiency with other defects", ["Wiskott-Aldrich", "Ataxia-telangiectasia"]),
        ("D83", "Common variable immunodeficiency", ["CVID"]),
        ("D84", "Other immunodeficiencies", ["Immunodeficiency NOS"]),
        ("D86", "Sarcoidosis", ["Sarcoidosis", "Boeck sarcoid"]),
        ("D89", "Other immune mechanism disorders", ["Immunoglobulin disorder"]),
    ],
    "Endocrine": [
        ("E00", "Congenital iodine deficiency syndrome", ["Congenital hypothyroidism"]),
        ("E01", "Iodine deficiency disorders", ["Goiter due to iodine deficiency"]),
        ("E03", "Other hypothyroidism", ["Hypothyroidism"]),
        ("E04", "Other nontoxic goiter", ["Goiter", "Bocio"]),
        ("E05", "Thyrotoxicosis [hyperthyroidism]", ["Hyperthyroidism", "Tirotoxicosis"]),
        ("E06", "Thyroiditis", ["Hashimoto thyroiditis"]),
        ("E07", "Other thyroid disorders", ["Thyroid nodule NOS"]),
        ("E10", "Type 1 diabetes mellitus", ["DM1", "Diabetes tipo 1"]),
        ("E11", "Type 2 diabetes mellitus", ["DM2", "Diabetes tipo 2"]),
        ("E12", "Malnutrition-related diabetes", ["Tropical diabetes"]),
        ("E13", "Other specified diabetes", ["Secondary diabetes", "Steroid diabetes"]),
        ("E14", "Unspecified diabetes", ["Diabetes NOS"]),
        ("E15", "Nondiabetic hypoglycemic coma", ["Hypoglycemic coma"]),
        ("E16", "Other pancreatic endocrine disorders", ["Hypoglycemia NOS"]),
        ("E20", "Hypoparathyroidism", ["Low PTH"]),
        ("E21", "Hyperparathyroidism", ["High PTH"]),
        ("E22", "Pituitary hyperfunction", ["Acromegaly", "Cushing disease"]),
        ("E23", "Pituitary hypofunction", ["Hypopituitarism"]),
        ("E24", "Cushing syndrome", ["Hypercortisolism"]),
        ("E25", "Adrenogenital disorders", ["Adrenal hyperplasia", "CAH"]),
        ("E26", "Hyperaldosteronism", ["Conn syndrome"]),
        ("E27", "Other adrenal disorders", ["Addison disease", "Adrenal insufficiency"]),
        ("E28", "Ovarian dysfunction", ["PCOS", "Polycystic ovarian syndrome"]),
        ("E29", "Testicular dysfunction", ["Hypogonadism", "Testosterone deficiency"]),
        ("E30", "Pubertal disorders", ["Precocious puberty"]),
        ("E31", "Polyglandular dysfunction", ["Autoimmune polyendocrine syndrome"]),
        ("E34", "Other endocrine disorders", ["Short stature"]),
        ("E40", "Kwashiorkor", ["Protein deficiency"]),
        ("E41", "Nutritional marasmus", ["Calorie deficiency"]),
        ("E43", "Severe protein-energy malnutrition", ["Severe malnutrition"]),
        ("E44", "Moderate protein-energy malnutrition", ["Moderate malnutrition"]),
        ("E46", "Unspecified protein-energy malnutrition", ["Malnutrition NOS"]),
        ("E50", "Vitamin A deficiency", ["Night blindness", "Xerophthalmia"]),
        ("E51", "Thiamine deficiency", ["Beriberi"]),
        ("E52", "Niacin deficiency", ["Pellagra"]),
        ("E53", "Other B vitamin deficiencies", ["B12 deficiency NOS", "Folate deficiency"]),
        ("E54", "Ascorbic acid deficiency", ["Scurvy", "Vitamin C deficiency"]),
        ("E55", "Vitamin D deficiency", ["Hypovitaminosis D", "Rickets"]),
        ("E56", "Other vitamin deficiencies", ["Vitamin E deficiency", "Vitamin K deficiency"]),
        ("E58", "Dietary calcium deficiency", ["Calcium deficiency"]),
        ("E61", "Other nutrient deficiencies", ["Zinc deficiency", "Magnesium deficiency"]),
        ("E63", "Other nutritional deficiencies", ["Nutritional deficiency NOS"]),
        ("E64", "Sequelae of malnutrition", ["Malnutrition sequelae"]),
        ("E65", "Localized adiposity", ["Fat distribution disorder"]),
        ("E66", "Obesity", ["Obesity", "Obesidad", "Overweight"]),
        ("E67", "Other hyperalimentation", ["Hypervitaminosis"]),
        ("E70", "Phenylketonuria", ["PKU"]),
        ("E71", "Branched-chain amino acid disorders", ["Maple syrup urine disease", "MSUD"]),
        ("E72", "Other amino acid metabolism disorders", ["Homocystinuria", "Tyrosinemia"]),
        ("E73", "Lactose intolerance", ["Lactose intolerance", "Intolerancia lactosa"]),
        ("E74", "Carbohydrate metabolism disorders", ["Galactosemia", "Glycogen storage"]),
        ("E75", "Sphingolipid storage disorders", ["Gaucher disease", "Niemann-Pick"]),
        ("E76", "Glycosaminoglycan metabolism disorders", ["Mucopolysaccharidosis"]),
        ("E77