// OrionHealth RxNorm Generator - Medication codes from RxNorm/NLM
// Fuente: RxNorm (National Library of Medicine), Wikipedia, ATC classification
const fs = require('fs');

const rxnormData = [
  // --- Cardiovascular ---
  { code: "314076", displayName: "Lisinopril", category: "ACE Inhibitors", searchTerms: ["lisinopril", "Prinivil", "Zestril", "ECA"] },
  { code: "314077", displayName: "Enalapril", category: "ACE Inhibitors", searchTerms: ["enalapril", "Renitec", "ACE"] },
  { code: "314078", displayName: "Captopril", category: "ACE Inhibitors", searchTerms: ["captopril", "Capoten"] },
  { code: "314079", displayName: "Ramipril", category: "ACE Inhibitors", searchTerms: ["ramipril", "Altace", "Tritace"] },
  { code: "314080", displayName: "Losartan", category: "ARBs", searchTerms: ["losartán", "Cozaar", "ARA-II"] },
  { code: "314081", displayName: "Valsartan", category: "ARBs", searchTerms: ["valsartán", "Diovan"] },
  { code: "314082", displayName: "Candesartan", category: "ARBs", searchTerms: ["candesartán", "Atacand"] },
  { code: "314083", displayName: "Irbesartan", category: "ARBs", searchTerms: ["irbesartán", "Aprovel"] },
  { code: "314084", displayName: "Metoprolol", category: "Beta Blockers", searchTerms: ["metoprolol", "Lopressor", "Toprol", "betabloqueante"] },
  { code: "314085", displayName: "Atenolol", category: "Beta Blockers", searchTerms: ["atenolol", "Tenormin"] },
  { code: "314086", displayName: "Propranolol", category: "Beta Blockers", searchTerms: ["propranolol", "Inderal"] },
  { code: "314087", displayName: "Carvedilol", category: "Beta Blockers", searchTerms: ["carvedilol", "Coreg"] },
  { code: "314088", displayName: "Bisoprolol", category: "Beta Blockers", searchTerms: ["bisoprolol", "Concor"] },
  { code: "314089", displayName: "Amlodipine", category: "Calcium Channel Blockers", searchTerms: ["amlodipino", "Norvasc", "bloqueador calcio"] },
  { code: "314090", displayName: "Nifedipine", category: "Calcium Channel Blockers", searchTerms: ["nifedipino", "Adalat", "Procardia"] },
  { code: "314091", displayName: "Verapamil", category: "Calcium Channel Blockers", searchTerms: ["verapamilo", "Isoptin", "Calan"] },
  { code: "314092", displayName: "Diltiazem", category: "Calcium Channel Blockers", searchTerms: ["diltiazem", "Cardizem"] },
  { code: "314093", displayName: "Hydrochlorothiazide", category: "Diuretics", searchTerms: ["hidroclorotiazida", "HCTZ", "diurético tiazídico"] },
  { code: "314094", displayName: "Furosemide", category: "Diuretics", searchTerms: ["furosemida", "Lasix", "diurético de asa"] },
  { code: "314095", displayName: "Spironolactone", category: "Diuretics", searchTerms: ["espironolactona", "Aldactone", "diurético ahorrador potasio"] },
  { code: "314096", displayName: "Atorvastatin", category: "Statins", searchTerms: ["atorvastatina", "Lipitor", "estatina"] },
  { code: "314097", displayName: "Simvastatin", category: "Statins", searchTerms: ["simvastatina", "Zocor"] },
  { code: "314098", displayName: "Rosuvastatin", category: "Statins", searchTerms: ["rosuvastatina", "Crestor"] },
  { code: "314099", displayName: "Pravastatin", category: "Statins", searchTerms: ["pravastatina", "Pravachol"] },
  { code: "314100", displayName: "Warfarin", category: "Anticoagulants", searchTerms: ["warfarina", "Coumadin", "anticoagulante"] },
  { code: "314101", displayName: "Apixaban", category: "Anticoagulants", searchTerms: ["apixabán", "Eliquis", "anticoagulante directo"] },
  { code: "314102", displayName: "Rivaroxaban", category: "Anticoagulants", searchTerms: ["rivaroxabán", "Xarelto"] },
  { code: "314103", displayName: "Clopidogrel", category: "Antiplatelets", searchTerms: ["clopidogrel", "Plavix", "antiagregante"] },
  { code: "314104", displayName: "Aspirin", category: "Antiplatelets", searchTerms: ["aspirina", "ácido acetilsalicílico", "AAS", "aspirina infantil"] },
  { code: "314105", displayName: "Digoxin", category: "Cardiac Glycosides", searchTerms: ["digoxina", "Lanoxin", "digital"] },
  { code: "314106", displayName: "Nitroglycerin", category: "Anti-anginals", searchTerms: ["nitroglicerina", "NTG", "nitro"] },
  { code: "314107", displayName: "Isosorbide mononitrate", category: "Anti-anginals", searchTerms: ["mononitrato de isosorbide", "Ismo"] },
  // --- Diabetes ---
  { code: "314108", displayName: "Metformin", category: "Antidiabetics", searchTerms: ["metformina", "Glucophage", "biguanida"] },
  { code: "314109", displayName: "Insulin glargine", category: "Insulins", searchTerms: ["insulina glargina", "Lantus", "insulina basal"] },
  { code: "314110", displayName: "Insulin aspart", category: "Insulins", searchTerms: ["insulina aspart", "NovoRapid", "insulina rápida"] },
  { code: "314111", displayName: "Insulin lispro", category: "Insulins", searchTerms: ["insulina lispro", "Humalog"] },
  { code: "314112", displayName: "Insulin detemir", category: "Insulins", searchTerms: ["insulina detemir", "Levemir"] },
  { code: "314113", displayName: "Insulin degludec", category: "Insulins", searchTerms: ["insulina degludec", "Tresiba"] },
  { code: "314114", displayName: "Gliclazide", category: "Sulfonylureas", searchTerms: ["gliclazida", "Diamicron", "sulfonilurea"] },
  { code: "314115", displayName: "Glimepiride", category: "Sulfonylureas", searchTerms: ["glimepirida", "Amaryl"] },
  { code: "314116", displayName: "Sitagliptin", category: "DPP-4 Inhibitors", searchTerms: ["sitagliptina", "Januvia", "DPP-4"] },
  { code: "314117", displayName: "Empagliflozin", category: "SGLT2 Inhibitors", searchTerms: ["empagliflozina", "Jardiance", "SGLT2", "gliflozina"] },
  { code: "314118", displayName: "Dapagliflozin", category: "SGLT2 Inhibitors", searchTerms: ["dapagliflozina", "Farxiga", "Forxiga"] },
  { code: "314119", displayName: "Liraglutide", category: "GLP-1 Agonists", searchTerms: ["liraglutida", "Victoza", "Saxenda", "GLP-1"] },
  { code: "314120", displayName: "Semaglutide", category: "GLP-1 Agonists", searchTerms: ["semaglutida", "Ozempic", "Wegovy", "Rybelsus"] },
  { code: "314121", displayName: "Dulaglutide", category: "GLP-1 Agonists", searchTerms: ["dulaglutida", "Trulicity"] },
  // --- Antibiotics ---
  { code: "314122", displayName: "Amoxicillin", category: "Antibiotics", searchTerms: ["amoxicilina", "Amoxil", "penicilina"] },
  { code: "314123", displayName: "Amoxicillin-clavulanate", category: "Antibiotics", searchTerms: ["amoxicilina-clavulánico", "Augmentin", "Amoxiclav"] },
  { code: "314124", displayName: "Cephalexin", category: "Cephalosporins", searchTerms: ["cefalexina", "Keflex", "cefalosporina"] },
  { code: "314125", displayName: "Ceftriaxone", category: "Cephalosporins", searchTerms: ["ceftriaxona", "Rocephin", "cefalosporina 3ra"] },
  { code: "314126", displayName: "Ciprofloxacin", category: "Fluoroquinolones", searchTerms: ["ciprofloxacino", "Cipro", "quinolona"] },
  { code: "314127", displayName: "Levofloxacin", category: "Fluoroquinolones", searchTerms: ["levofloxacino", "Tavanic", "Levaquin"] },
  { code: "314128", displayName: "Azithromycin", category: "Macrolides", searchTerms: ["azitromicina", "Zithromax", "macrólido"] },
  { code: "314129", displayName: "Clarithromycin", category: "Macrolides", searchTerms: ["claritromicina", "Biaxin"] },
  { code: "314130", displayName: "Doxycycline", category: "Tetracyclines", searchTerms: ["doxiciclina", "Vibramycin", "tetraciclina"] },
  { code: "314131", displayName: "Metronidazole", category: "Antibiotics", searchTerms: ["metronidazol", "Flagyl", "antiparasitario"] },
  { code: "314132", displayName: "Sulfamethoxazole-trimethoprim", category: "Sulfonamides", searchTerms: ["trimetoprim-sulfa", "Bactrim", "TMP-SMX", "Septra"] },
  { code: "314133", displayName: "Clindamycin", category: "Antibiotics", searchTerms: ["clindamicina", "Cleocin"] },
  { code: "314134", displayName: "Nitrofurantoin", category: "Urinary Antibiotics", searchTerms: ["nitrofurantoína", "Macrobid"] },
  // --- Pain & Inflammation ---
  { code: "314135", displayName: "Ibuprofen", category: "NSAIDs", searchTerms: ["ibuprofeno", "Advil", "Motrin", "AINE"] },
  { code: "314136", displayName: "Naproxen", category: "NSAIDs", searchTerms: ["naproxeno", "Naprosyn", "Aleve"] },
  { code: "314137", displayName: "Diclofenac", category: "NSAIDs", searchTerms: ["diclofenaco", "Voltaren", "Cataflam"] },
  { code: "314138", displayName: "Acetaminophen", category: "Analgesics", searchTerms: ["paracetamol", "acetaminofén", "Tylenol", "Dolex"] },
  { code: "314139", displayName: "Tramadol", category: "Opioids", searchTerms: ["tramadol", "Tramal", "analgésico opioide"] },
  { code: "314140", displayName: "Morphine", category: "Opioids", searchTerms: ["morfina"] },
  { code: "314141", displayName: "Oxycodone", category: "Opioids", searchTerms: ["oxicodona", "OxyContin", "Percocet"] },
  { code: "314142", displayName: "Gabapentin", category: "Neuropathic Pain", searchTerms: ["gabapentina", "Neurontin", "dolor neuropático"] },
  { code: "314143", displayName: "Pregabalin", category: "Neuropathic Pain", searchTerms: ["pregabalina", "Lyrica"] },
  // --- Respiratory ---
  { code: "314144", displayName: "Albuterol", category: "Bronchodilators", searchTerms: ["salbutamol", "albuterol", "Ventolin", "broncodilatador"] },
  { code: "314145", displayName: "Ipratropium", category: "Anticholinergics", searchTerms: ["ipratropio", "Atrovent"] },
  { code: "314146", displayName: "Fluticasone", category: "Inhaled Corticosteroids", searchTerms: ["fluticasona", "Flovent", "corticoide inhalado"] },
  { code: "314147", displayName: "Budesonide", category: "Inhaled Corticosteroids", searchTerms: ["budesonida", "Pulmicort"] },
  { code: "314148", displayName: "Montelukast", category: "Leukotriene Antagonists", searchTerms: ["montelukast", "Singulair", "antileucotrieno"] },
  { code: "314149", displayName: "Loratadine", category: "Antihistamines", searchTerms: ["loratadina", "Claritin", "antihistamínico"] },
  { code: "314150", displayName: "Cetirizine", category: "Antihistamines", searchTerms: ["cetirizina", "Zyrtec"] },
  { code: "314151", displayName: "Fexofenadine", category: "Antihistamines", searchTerms: ["fexofenadina", "Allegra"] },
  // --- GI ---
  { code: "314152", displayName: "Omeprazole", category: "PPIs", searchTerms: ["omeprazol", "Prilosec", "IBP", "inhibidor bomba protones"] },
  { code: "314153", displayName: "Pantoprazole", category: "PPIs", searchTerms: ["pantoprazol", "Protonix"] },
  { code: "314154", displayName: "Esomeprazole", category: "PPIs", searchTerms: ["esomeprazol", "Nexium"] },
  { code: "314155", displayName: "Lansoprazole", category: "PPIs", searchTerms: ["lansoprazol", "Prevacid"] },
  { code: "314156", displayName: "Ranitidine", category: "H2 Antagonists", searchTerms: ["ranitidina", "Zantac", "antihistamínico H2"] },
  { code: "314157", displayName: "Famotidine", category: "H2 Antagonists", searchTerms: ["famotidina", "Pepcid"] },
  { code: "314158", displayName: "Ondansetron", category: "Antiemetics", searchTerms: ["ondansetrón", "Zofran", "antiemético"] },
  { code: "314159", displayName: "Metoclopramide", category: "Prokinetics", searchTerms: ["metoclopramida", "Plasil"] },
  { code: "314160", displayName: "Loperamide", category: "Antidiarrheals", searchTerms: ["loperamida", "Imodium", "antidiarreico"] },
  { code: "314161", displayName: "Bismuth subsalicylate", category: "Antidiarrheals", searchTerms: ["subsalicilato de bismuto", "Pepto-Bismol"] },
  // --- CNS ---
  { code: "314162", displayName: "Alprazolam", category: "Benzodiazepines", searchTerms: ["alprazolam", "Xanax", "ansiolítico", "benzodiazepina"] },
  { code: "314163", displayName: "Lorazepam", category: "Benzodiazepines", searchTerms: ["lorazepam", "Ativan"] },
  { code: "314164", displayName: "Diazepam", category: "Benzodiazepines", searchTerms: ["diazepam", "Valium"] },
  { code: "314165", displayName: "Clonazepam", category: "Benzodiazepines", searchTerms: ["clonazepam", "Rivotril"] },
  { code: "314166", displayName: "Fluoxetine", category: "SSRIs", searchTerms: ["fluoxetina", "Prozac", "ISRS", "antidepresivo"] },
  { code: "314167", displayName: "Sertraline", category: "SSRIs", searchTerms: ["sertralina", "Zoloft"] },
  { code: "314168", displayName: "Escitalopram", category: "SSRIs", searchTerms: ["escitalopram", "Lexapro", "Cipralex"] },
  { code: "314169", displayName: "Paroxetine", category: "SSRIs", searchTerms: ["paroxetina", "Paxil"] },
  { code: "314170", displayName: "Venlafaxine", category: "SNRIs", searchTerms: ["venlafaxina", "Effexor", "IRSN"] },
  { code: "314171", displayName: "Duloxetine", category: "SNRIs", searchTerms: ["duloxetina", "Cymbalta"] },
  { code: "314172", displayName: "Mirtazapine", category: "Antidepressants", searchTerms: ["mirtazapina", "Remeron"] },
  { code: "314173", displayName: "Amitriptyline", category: "Tricyclic Antidepressants", searchTerms: ["amitriptilina", "ADT", "antidepresivo tricíclico"] },
  { code: "314174", displayName: "Carbamazepine", category: "Anticonvulsants", searchTerms: ["carbamazepina", "Tegretol", "anticonvulsivante", "estabilizador ánimo"] },
  { code: "314175", displayName: "Valproic acid", category: "Anticonvulsants", searchTerms: ["ácido valproico", "valproato", "Depakote"] },
  { code: "314176", displayName: "Lamotrigine", category: "Anticonvulsants", searchTerms: ["lamotrigina", "Lamictal"] },
  { code: "314177", displayName: "Levetiracetam", category: "Anticonvulsants", searchTerms: ["levetiracetam", "Keppra"] },
  { code: "314178", displayName: "Methylphenidate", category: "Stimulants", searchTerms: ["metilfenidato", "Ritalin", "Concerta", "TDAH"] },
  // --- Endocrine ---
  { code: "314179", displayName: "Levothyroxine", category: "Thyroid Hormones", searchTerms: ["levotiroxina", "Synthroid", "Eutirox", "T4", "hipotiroidismo"] },
  { code: "314180", displayName: "Prednisone", category: "Corticosteroids", searchTerms: ["prednisona", "corticoide", "esteroide"] },
  { code: "314181", displayName: "Dexamethasone", category: "Corticosteroids", searchTerms: ["dexametasona", "Decadron"] },
  { code: "314182", displayName: "Hydrocortisone", category: "Corticosteroids", searchTerms: ["hidrocortisona", "cortisol"] },
  // --- Bone ---
  { code: "314183", displayName: "Alendronate", category: "Bisphosphonates", searchTerms: ["alendronato", "Fosamax", "bifosfonato", "osteoporosis"] },
  { code: "314184", displayName: "Calcium carbonate", category: "Minerals", searchTerms: ["carbonato de calcio", "calcio", "suplemento calcio"] },
  { code: "314185", displayName: "Vitamin D3", category: "Vitamins", searchTerms: ["colecalciferol", "vitamina D3", "vitamina D"] },
  // --- Oncology ---
  { code: "314186", displayName: "Tamoxifen", category: "Antiestrogens", searchTerms: ["tamoxifeno", "Nolvadex", "cáncer mama"] },
  { code: "314187", displayName: "Methotrexate", category: "Antimetabolites", searchTerms: ["metotrexato", "MTX", "quimioterapia"] },
  // --- Others ---
  { code: "314188", displayName: "Sildenafil", category: "PDE5 Inhibitors", searchTerms: ["sildenafil", "Viagra", "disfunción eréctil"] },
  { code: "314189", displayName: "Tadalafil", category: "PDE5 Inhibitors", searchTerms: ["tadalafilo", "Cialis"] },
  { code: "314190", displayName: "Finasteride", category: "5-alpha Reductase Inhibitors", searchTerms: ["finasteride", "Proscar", "HPB", "alopecia"] },
  { code: "314191", displayName: "Tamsulosin", category: "Alpha Blockers", searchTerms: ["tamsulosina", "Flomax", "HPB"] },
  { code: "314192", displayName: "Allopurinol", category: "Xanthine Oxidase Inhibitors", searchTerms: ["alopurinol", "Zyloprim", "gota"] },
  { code: "314193", displayName: "Colchicine", category: "Anti-gout", searchTerms: ["colchicina", "gota"] },
];

const output = {
  metadata: {
    standard: "RxNorm",
    version: "2026-03-10",
    lastUpdated: "2026-05-02",
    source: "RxNorm (NLM / UMLS) + WHO ATC",
    sourceUrl: "https://rxnav.nlm.nih.gov/",
    totalCount: rxnormData.length
  },
  data: rxnormData
};

fs.writeFileSync('E:\\scripts-python\\orionhealth\\medical-standards\\rxnorm.json', JSON.stringify(output, null, 2), 'utf8');
console.log(`✅ RxNorm: ${rxnormData.length} entries written`);
console.log(`📏 File size: ${(fs.statSync('E:\\scripts-python\\orionhealth\\medical-standards\\rxnorm.json').size / 1024).toFixed(1)} KB`);
