const fs = require('fs');

const extra = getExtraChapters();
const base = JSON.parse(fs.readFileSync('E:\\scripts-python\\orionhealth\\medical-standards\\icd10.json'));
const merged = [...base.data, ...extra];

const output = {
  metadata: {
    standard: "ICD-10",
    version: "2024-1",
    lastUpdated: "2026-05-02",
    source: "WHO ICD-10-CM 2024",
    sourceUrl: "https://www.who.int/standards/classifications/classification-of-diseases",
    totalCount: merged.length
  },
  data: merged
};

fs.writeFileSync('E:\\scripts-python\\orionhealth\\medical-standards\\icd10.json', JSON.stringify(output, null, 2), 'utf8');
console.log('ICD-10: ' + merged.length + ' entries written');
console.log('File size: ' + (fs.statSync('E:\\scripts-python\\orionhealth\\medical-standards\\icd10.json').size / 1024).toFixed(1) + ' KB');

function getExtraChapters() {
  const items = [];
  // C00-D48 Neoplasms
  const neoplasmCodes = [
    ["C51","Malignant neoplasm of vulva","cancer de vulva","carcinoma vulvar"],
    ["C52","Malignant neoplasm of vagina","cancer de vagina"],
    ["C53","Malignant neoplasm of cervix uteri","cancer de cuello uterino","cancer cervical"],
    ["C54","Malignant neoplasm of corpus uteri","cancer de endometrio","cancer de utero"],
    ["C55","Malignant neoplasm of uterus NOS","cancer uterino"],
    ["C56","Malignant neoplasm of ovary","cancer de ovario"],
    ["C57","Malignant neoplasm of female genital organs","cancer genital femenino"],
    ["C60","Malignant neoplasm of penis","cancer de pene"],
    ["C61","Malignant neoplasm of prostate","cancer de prostata"],
    ["C62","Malignant neoplasm of testis","cancer de testiculo"],
    ["C64","Malignant neoplasm of kidney","cancer de rinon","carcinoma renal"],
    ["C65","Malignant neoplasm of renal pelvis","cancer de pelvis renal"],
    ["C66","Malignant neoplasm of ureter","cancer de ureter"],
    ["C67","Malignant neoplasm of bladder","cancer de vejiga"],
    ["C69","Malignant neoplasm of eye","cancer de ojo","retinoblastoma"],
    ["C70","Malignant neoplasm of meninges","meningioma"],
    ["C71","Malignant neoplasm of brain","cancer de cerebro","tumor cerebral","glioma"],
    ["C72","Malignant neoplasm of spinal cord","tumor de medula espinal"],
    ["C73","Malignant neoplasm of thyroid gland","cancer de tiroides"],
    ["C74","Malignant neoplasm of adrenal gland","cancer suprarrenal","feocromocitoma"],
    ["C76","Malignant neoplasm other ill-defined","cancer sitio impreciso"],
    ["C77","Secondary neoplasm of lymph nodes","metastasis ganglionar"],
    ["C78","Secondary neoplasm of respiratory organs","metastasis pulmonar"],
    ["C79","Secondary neoplasm of other sites","metastasis hepatica","metastasis osea"],
    ["C80","Malignant neoplasm without specification","cancer sin especificar"],
    ["C81","Hodgkin lymphoma","linfoma de Hodgkin"],
    ["C82","Follicular lymphoma","linfoma folicular"],
    ["C83","Diffuse non-Hodgkin lymphoma","linfoma difuso","linfoma no Hodgkin"],
    ["C84","Mature T/NK-cell lymphomas","linfoma T"],
    ["C85","Other non-Hodgkin lymphoma","linfoma no Hodgkin"],
    ["C88","Malignant immunoproliferative diseases","gammapatia monoclonal"],
    ["C90","Multiple myeloma","mieloma multiple"],
    ["C91","Lymphoid leukemia","leucemia linfatica","LLA","LLC"],
    ["C92","Myeloid leukemia","leucemia mieloide","LMA","LMC"],
    ["C93","Monocytic leukemia","leucemia monocitica"],
    ["C94","Other leukemias","leucemia"],
    ["C95","Leukemia unspecified","leucemia sin especificar"],
    ["D00","Carcinoma in situ of oral cavity","carcinoma in situ oral"],
    ["D01","Carcinoma in situ of digestive organs","carcinoma in situ digestivo"],
    ["D05","Carcinoma in situ of breast","carcinoma in situ mama","DCIS"],
    ["D06","Carcinoma in situ of cervix","NIC","neoplasia intraepitelial cervical"],
    ["D10","Benign neoplasm of oral cavity","tumor benigno oral"],
    ["D11","Benign neoplasm of salivary glands","adenoma parotida"],
    ["D12","Benign neoplasm of intestine","polipo intestinal","polipo colon"],
    ["D13","Benign neoplasm of digestive system","tumor benigno digestivo","leiomioma"],
    ["D14","Benign neoplasm of respiratory tract","tumor benigno pulmon"],
    ["D15","Benign neoplasm of thoracic organs","mediastino"],
    ["D16","Benign neoplasm of bone","osteoma","tumor oseo benigno"],
    ["D17","Benign lipomatous neoplasm","lipoma"],
    ["D18","Hemangioma","hemangioma","angioma"],
    ["D19","Benign neoplasm of mesothelial tissue","tumor mesotelial"],
    ["D22","Melanocytic nevi","nevus melanocitico","lunar"],
    ["D23","Benign neoplasm of skin","tumor benigno de piel"],
    ["D24","Benign neoplasm of breast","tumor benigno de mama","fibroadenoma"],
    ["D25","Leiomyoma of uterus","mioma","fibroma uterino"],
    ["D26","Benign neoplasm of uterus","polipo uterino"],
    ["D27","Benign neoplasm of ovary","quiste ovarico"],
    ["D28","Benign neoplasm female genital","tumor benigno genital femenino"],
    ["D29","Benign neoplasm male genital","tumor benigno genital masculino"],
    ["D30","Benign neoplasm of urinary organs","tumor benigno vejiga"],
    ["D31","Benign neoplasm of eye","tumor benigno ojo"],
    ["D32","Benign neoplasm of meninges","meningioma benigno"],
    ["D33","Benign neoplasm of brain","tumor cerebral benigno","astrocitoma"],
    ["D34","Benign neoplasm of thyroid","nodulo tiroideo"],
    ["D35","Benign neoplasm of endocrine glands","adenoma hipofisario"],
    ["D36","Benign neoplasm other sites","tumor benigno"],
    ["D37","Uncertain behavior oral/digestive","tumor borderline"],
    ["D38","Uncertain behavior respiratory","tumor borderline pulmonar"],
    ["D39","Uncertain behavior female genital","tumor borderline ovarico"],
    ["D40","Uncertain behavior male genital","tumor borderline prostata"],
    ["D41","Uncertain behavior urinary","tumor borderline vejiga"],
    ["D43","Uncertain behavior brain/CNS","tumor cerebral borderline"],
    ["D44","Uncertain behavior endocrine","tumor endocrino borderline"],
    ["D48","Uncertain behavior other sites","tumor borderline"],
  ];
  for (const [code, name, ...terms] of neoplasmCodes) {
    items.push({ code, displayName: name, category: "Neoplasms", searchTerms: terms });
  }

  // E00-E90 Endocrine
  const endocrineCodes = [
    ["E00","Congenital iodine-deficiency syndrome","cretinismo"],
    ["E01","Iodine-deficiency thyroid disorders","bocio endemico"],
    ["E02","Subclinical iodine-deficiency hypothyroidism","hipotiroidismo subclinico"],
    ["E03","Other hypothyroidism","hipotiroidismo","mixedema"],
    ["E04","Other nontoxic goiter","bocio nodular","bocio difuso"],
    ["E05","Hyperthyroidism","hipertiroidismo","Graves"],
    ["E06","Thyroiditis","tiroiditis","Hashimoto"],
    ["E07","Other thyroid disorders","nodulo tiroideo","bocio"],
    ["E10","Type 1 diabetes mellitus","diabetes tipo 1","DM1"],
    ["E11","Type 2 diabetes mellitus","diabetes tipo 2","DM2"],
    ["E12","Malnutrition-related diabetes",],
    ["E13","Other specified diabetes","diabetes gestacional","MODY"],
    ["E14","Unspecified diabetes mellitus","diabetes"],
    ["E15","Hypoglycemic coma","coma hipoglucemico"],
    ["E16","Other pancreatic internal secretion disorders","hipoglicemia","hiperinsulinismo"],
    ["E20","Hypoparathyroidism","hipoparatiroidismo"],
    ["E21","Hyperparathyroidism","hiperparatiroidismo"],
    ["E22","Pituitary hyperfunction","acromegalia","prolactinoma"],
    ["E23","Pituitary hypofunction","hipopituitarismo"],
    ["E24","Cushing syndrome","sindrome de Cushing"],
    ["E25","Adrenogenital disorders","hiperplasia suprarrenal congenita"],
    ["E26","Hyperaldosteronism","hiperaldosteronismo","Conn"],
    ["E27","Other adrenal disorders","insuficiencia suprarrenal","Addison"],
    ["E28","Ovarian dysfunction","SOP","ovario poliquistico"],
    ["E29","Testicular dysfunction","hipogonadismo"],
    ["E30","Disorders of puberty","pubertad precoz"],
    ["E31","Polyglandular dysfunction","sindrome poliglandular"],
    ["E34","Other endocrine disorders","enanismo","gigantismo"],
    ["E40","Kwashiorkor","Kwashiorkor","desnutricion"],
    ["E41","Nutritional marasmus","marasmo"],
    ["E43","Severe protein-energy malnutrition","desnutricion severa"],
    ["E44","Moderate and mild malnutrition","desnutricion"],
    ["E46","Unspecified malnutrition","malnutricion"],
    ["E50","Vitamin A deficiency","deficiencia vitamina A"],
    ["E51","Thiamine deficiency","beriberi","deficiencia B1"],
    ["E52","Niacin deficiency","pelagra","deficiencia B3"],
    ["E53","Other B vitamin deficiencies","deficiencia B12","deficiencia folato"],
    ["E54","Ascorbic acid deficiency","escorbuto","deficiencia C"],
    ["E55","Vitamin D deficiency","raquitismo","osteomalacia","deficiencia D"],
    ["E56","Other vitamin deficiencies"],
    ["E58","Dietary calcium deficiency","deficiencia calcio"],
    ["E59","Dietary selenium deficiency","deficiencia selenio"],
    ["E60","Dietary zinc deficiency","deficiencia zinc"],
    ["E61","Other nutrient deficiencies","deficiencia magnesio"],
    ["E63","Other nutritional deficiencies"],
    ["E64","Sequelae of malnutrition"],
    ["E65","Localized adiposity","obesidad localizada"],
    ["E66","Obesity","obesidad","sobrepeso"],
    ["E67","Other hyperalimentation","hipervitaminosis"],
    ["E68","Sequelae of hyperalimentation"],
    ["E70","Phenylketonuria","PKU"],
    ["E71","Amino acid metabolism disorders","maple syrup"],
    ["E72","Other amino acid disorders","homocistinuria","tirosinemia"],
    ["E73","Lactose intolerance","intolerancia a la lactosa"],
    ["E74","Carbohydrate metabolism disorders","glucogenosis","galactosemia"],
    ["E75","Sphingolipid storage disorders","Gaucher","Niemann-Pick","Fabry"],
    ["E76","Mucopolysaccharidosis","MPS","Hurler"],
    ["E77","Glycoprotein metabolism disorders"],
    ["E78","Lipoprotein disorders","hipercolesterolemia familiar"],
    ["E79","Purine/pyrimidine disorders","hiperuricemia","gota"],
    ["E80","Porphyrin/bilirubin disorders","porfiria","Gilbert"],
    ["E83","Mineral metabolism disorders","hemocromatosis","Wilson"],
    ["E84","Cystic fibrosis","fibrosis quistica"],
    ["E85","Amyloidosis","amiloidosis"],
    ["E86","Volume depletion","deshidratacion"],
    ["E87","Fluid/electrolyte/acid-base disorders","trastorno electrolitico"],
    ["E88","Other metabolic disorders","sindrome metabolico"],
    ["E89","Post-procedural endocrine disorders"],
    ["E90","Nutritional/metabolic disorders in disease"],
  ];
  for (const [code, name, ...terms] of endocrineCodes) {
    items.push({ code, displayName: name, category: "Endocrine/Metabolic", searchTerms: terms });
  }

  // F00-F99 Mental disorders
  const mentalCodes = [
    ["F00","Alzheimer dementia","demencia Alzheimer"],
    ["F01","Vascular dementia","demencia vascular"],
    ["F02","Dementia in other diseases","demencia cuerpos Lewy"],
    ["F03","Unspecified dementia","demencia"],
    ["F04","Organic amnesic syndrome","Korsakoff"],
    ["F05","Delirium","delirio","sindrome confusional"],
    ["F06","Other organic mental disorders"],
    ["F07","Personality/behavioral brain disease"],
    ["F10","Alcohol related disorders","alcoholismo"],
    ["F11","Opioid related disorders","heroina","opioides"],
    ["F12","Cannabis related disorders","marihuana","cannabis"],
    ["F13","Sedative/hypnotic related disorders","benzodiazepinas"],
    ["F14","Cocaine related disorders","cocaina"],
    ["F15","Stimulant related disorders","anfetaminas"],
    ["F16","Hallucinogen related disorders","LSD"],
    ["F17","Nicotine dependence","tabaquismo","nicotina"],
    ["F18","Inhalant related disorders","inhalantes"],
    ["F19","Multiple drug use disorders","policonsumo"],
    ["F20","Schizophrenia","esquizofrenia","trastorno psicotico"],
    ["F21","Schizotypal disorder"],
    ["F22","Persistent delusional disorders","trastorno delirante","paranoia"],
    ["F23","Acute psychotic disorders","brote psicotico"],
    ["F24","Induced delusional disorder","folie a deux"],
    ["F25","Schizoaffective disorders"],
    ["F28","Other psychotic disorders","psicosis"],
    ["F29","Unspecified psychosis"],
    ["F30","Manic episode","mania"],
    ["F31","Bipolar disorder","trastorno bipolar"],
    ["F32","Depressive episode","depresion mayor"],
    ["F33","Recurrent depressive disorder","depresion recurrente"],
    ["F34","Persistent mood disorders","distimia","ciclotimia"],
    ["F38","Other mood disorders","trastorno afectivo"],
    ["F39","Unspecified mood disorder"],
    ["F40","Phobic anxiety disorders","fobia social","agorafobia"],
    ["F41","Other anxiety disorders","ansiedad","panico","ansiedad generalizada"],
    ["F42","OCD","TOC","obsesivo compulsivo"],
    ["F43","Reaction to severe stress","TEPT","estres postraumatico"],
    ["F44","Dissociative disorders","trastorno disociativo"],
    ["F45","Somatoform disorders","somatizacion","hipocondria"],
    ["F48","Other neurotic disorders","neurastenia"],
    ["F50","Eating disorders","anorexia","bulimia"],
    ["F51","Sleep disorders","insomnio"],
    ["F52","Sexual dysfunction","disfuncion sexual"],
    ["F60","Personality disorders","trastorno personalidad","borderline"],
    ["F70","Intellectual disability mild","retraso mental leve"],
    ["F71","Intellectual disability moderate"],
    ["F72","Intellectual disability severe"],
    ["F80","Developmental speech/language disorders","tartamudez"],
    ["F81","Developmental learning disorders","dislexia","discalculia"],
    ["F82","Developmental coordination disorder","dispraxia"],
    ["F84","Pervasive developmental disorders","autismo","TEA","Asperger"],
    ["F88","Other developmental disorders","retraso desarrollo"],
    ["F89","Unspecified developmental disorder"],
    ["F90","ADHD","TDAH","hiperactividad","deficit atencion"],
    ["F91","Conduct disorders","trastorno de conducta"],
    ["F92","Mixed conduct/emotional disorders"],
    ["F93","Emotional disorders of childhood"],
    ["F94","Social functioning disorders","mutismo selectivo"],
    ["F95","Tic disorders","tourette","tics"],
    ["F98","Other behavioral/emotional disorders","enuresis","encopresis"],
    ["F99","Mental disorder NOS"],
  ];
  for (const [code, name, ...terms] of mentalCodes) {
    items.push({ code, displayName: name, category: "Psychiatry", searchTerms: terms });
  }
  
  return items;
}
