// OrionHealth ICD-10 Generator - WHO-based codes
// Fuente: WHO ICD-10 2024, CMS ICD-10-CM, Wikipedia
const fs = require('fs');

// Chapter A00-B99: Certain infectious and parasitic diseases
const infectious = [
  { code: "A00", displayName: "Cholera", category: "Infectious", searchTerms: ["cólera", "vibrio cholerae", "cólera"] },
  { code: "A01", displayName: "Typhoid and paratyphoid fevers", category: "Infectious", searchTerms: ["fiebre tifoidea", "salmonella typhi", "paratifoidea"] },
  { code: "A02", displayName: "Other salmonella infections", category: "Infectious", searchTerms: ["salmonelosis", "Salmonella"] },
  { code: "A03", displayName: "Shigellosis", category: "Infectious", searchTerms: ["shigelosis", "disentería bacilar", "Shigella"] },
  { code: "A04", displayName: "Other bacterial intestinal infections", category: "Infectious", searchTerms: ["E. coli", "infección intestinal bacteriana", "enteritis bacteriana"] },
  { code: "A05", displayName: "Other bacterial foodborne intoxications", category: "Infectious", searchTerms: ["intoxicación alimentaria", "botulismo", "Clostridium"] },
  { code: "A06", displayName: "Amebiasis", category: "Infectious", searchTerms: ["amebiasis", "Entamoeba histolytica", "disentería amebiana"] },
  { code: "A07", displayName: "Other protozoal intestinal diseases", category: "Infectious", searchTerms: ["giardiasis", "cryptosporidiosis", "protozoos intestinales"] },
  { code: "A08", displayName: "Viral and other specified intestinal infections", category: "Infectious", searchTerms: ["gastroenteritis viral", "rotavirus", "norovirus"] },
  { code: "A09", displayName: "Infectious gastroenteritis and colitis", category: "Infectious", searchTerms: ["gastroenteritis", "colitis infecciosa"] },
  { code: "A15", displayName: "Respiratory tuberculosis", category: "Infectious", searchTerms: ["tuberculosis pulmonar", "TB", "TBC", "tuberculosis respiratoria"] },
  { code: "A16", displayName: "Respiratory tuberculosis not confirmed bacteriologically", category: "Infectious", searchTerms: ["TB pulmonar sin confirmación"] },
  { code: "A17", displayName: "Tuberculosis of nervous system", category: "Infectious", searchTerms: ["tuberculosis meníngea", "TB SNC"] },
  { code: "A18", displayName: "Tuberculosis of other organs", category: "Infectious", searchTerms: ["TB extrapulmonar", "mal de Pott", "tuberculosis ósea"] },
  { code: "A19", displayName: "Miliary tuberculosis", category: "Infectious", searchTerms: ["TB miliar", "tuberculosis diseminada"] },
  { code: "A20", displayName: "Plague", category: "Infectious", searchTerms: ["peste", "Yersinia pestis"] },
  { code: "A21", displayName: "Tularemia", category: "Infectious", searchTerms: ["tularemia", "Francisella tularensis"] },
  { code: "A22", displayName: "Anthrax", category: "Infectious", searchTerms: ["ántrax", "carbunco", "Bacillus anthracis"] },
  { code: "A23", displayName: "Brucellosis", category: "Infectious", searchTerms: ["brucelosis", "fiebre de Malta"] },
  { code: "A24", displayName: "Glanders and melioidosis", category: "Infectious", searchTerms: ["muermo", "melioidosis"] },
  { code: "A25", displayName: "Rat-bite fevers", category: "Infectious", searchTerms: ["fiebre por mordedura de rata"] },
  { code: "A26", displayName: "Erysipeloid", category: "Infectious", searchTerms: ["erisipeloide"] },
  { code: "A27", displayName: "Leptospirosis", category: "Infectious", searchTerms: ["leptospirosis", "enfermedad de Weil"] },
  { code: "A28", displayName: "Other zoonotic bacterial diseases", category: "Infectious", searchTerms: ["zoonosis bacteriana"] },
  { code: "A30", displayName: "Leprosy", category: "Infectious", searchTerms: ["lepra", "Hansen", "Mycobacterium leprae"] },
  { code: "A31", displayName: "Infection due to other mycobacteria", category: "Infectious", searchTerms: ["Mycobacterium avium", "micobacteria atípica"] },
  { code: "A32", displayName: "Listeriosis", category: "Infectious", searchTerms: ["listeriosis", "Listeria monocytogenes"] },
  { code: "A35", displayName: "Other tetanus", category: "Infectious", searchTerms: ["tétanos", "trismo"] },
  { code: "A36", displayName: "Diphtheria", category: "Infectious", searchTerms: ["difteria", "Corynebacterium diphtheriae"] },
  { code: "A37", displayName: "Whooping cough", category: "Infectious", searchTerms: ["tos ferina", "coqueluche", "Bordetella pertussis"] },
  { code: "A38", displayName: "Scarlet fever", category: "Infectious", searchTerms: ["escarlatina"] },
  { code: "A39", displayName: "Meningococcal infection", category: "Infectious", searchTerms: ["meningitis meningocócica", "Neisseria meningitidis"] },
  { code: "A40", displayName: "Streptococcal sepsis", category: "Infectious", searchTerms: ["sepsis estreptocócica"] },
  { code: "A41", displayName: "Other sepsis", category: "Infectious", searchTerms: ["sepsis", "septicemia"] },
  { code: "A46", displayName: "Erysipelas", category: "Infectious", searchTerms: ["erisipela"] },
  { code: "A48", displayName: "Other bacterial diseases NEC", category: "Infectious", searchTerms: ["gangrena gaseosa", "legionelosis", "Legionella"] },
  { code: "A49", displayName: "Bacterial infection of unspecified site", category: "Infectious", searchTerms: ["infección bacteriana"] },
  { code: "A50", displayName: "Congenital syphilis", category: "Infectious", searchTerms: ["sífilis congénita"] },
  { code: "A51", displayName: "Early syphilis", category: "Infectious", searchTerms: ["sífilis primaria", "sífilis secundaria"] },
  { code: "A52", displayName: "Late syphilis", category: "Infectious", searchTerms: ["sífilis terciaria", "neurossífilis"] },
  { code: "A53", displayName: "Other and unspecified syphilis", category: "Infectious", searchTerms: ["sífilis"] },
  { code: "A54", displayName: "Gonococcal infection", category: "Infectious", searchTerms: ["gonorrea", "gonococia", "Neisseria gonorrhoeae"] },
  { code: "A55", displayName: "Chlamydial lymphogranuloma", category: "Infectious", searchTerms: ["linfogranuloma venéreo", "LGV"] },
  { code: "A56", displayName: "Other sexually transmitted chlamydial diseases", category: "Infectious", searchTerms: ["clamidia", "Chlamydia trachomatis"] },
  { code: "A57", displayName: "Chancroid", category: "Infectious", searchTerms: ["chancroide", "Haemophilus ducreyi"] },
  { code: "A59", displayName: "Trichomoniasis", category: "Infectious", searchTerms: ["tricomoniasis", "Trichomonas vaginalis"] },
  { code: "A60", displayName: "Anogenital herpesviral infection", category: "Infectious", searchTerms: ["herpes genital", "HSV-2"] },
  { code: "A63", displayName: "Other predominantly STDs", category: "Infectious", searchTerms: ["ETS", "Molluscum contagiosum genital"] },
  { code: "A64", displayName: "Unspecified sexually transmitted disease", category: "Infectious", searchTerms: ["ETS sin especificar"] },
  { code: "A69", displayName: "Other spirochetal infections", category: "Infectious", searchTerms: ["enfermedad de Lyme", "Borrelia burgdorferi"] },
  { code: "A70", displayName: "Chlamydia psittaci infection", category: "Infectious", searchTerms: ["psitacosis", "fiebre del loro"] },
  { code: "A71", displayName: "Trachoma", category: "Infectious", searchTerms: ["tracoma", "Chlamydia trachomatis"] },
  { code: "A74", displayName: "Other chlamydial diseases", category: "Infectious", searchTerms: ["clamidia"] },
  { code: "A75", displayName: "Typhus fever", category: "Infectious", searchTerms: ["tifus", "Rickettsia"] },
  { code: "A77", displayName: "Spotted fever", category: "Infectious", searchTerms: ["fiebre manchada", "Rickettsia rickettsii", "RMSF"] },
  { code: "A78", displayName: "Q fever", category: "Infectious", searchTerms: ["fiebre Q", "Coxiella burnetii"] },
  { code: "A79", displayName: "Other rickettsioses", category: "Infectious", searchTerms: ["rickettsiosis", "ehrlichiosis"] },
  { code: "A80", displayName: "Acute poliomyelitis", category: "Infectious", searchTerms: ["poliomielitis", "polio"] },
  { code: "A81", displayName: "Atypical virus infections of CNS", category: "Infectious", searchTerms: ["Creutzfeldt-Jakob", "priones", "vCJD", "Kuru"] },
  { code: "A82", displayName: "Rabies", category: "Infectious", searchTerms: ["rabia", "hidrofobia"] },
  { code: "A83", displayName: "Mosquito-borne viral encephalitis", category: "Infectious", searchTerms: ["West Nile", "encefalitis japonesa", "encefalitis viral"] },
  { code: "A84", displayName: "Tick-borne viral encephalitis", category: "Infectious", searchTerms: ["encefalitis por garrapatas", "TBE"] },
  { code: "A85", displayName: "Other viral encephalitis", category: "Infectious", searchTerms: ["encefalitis viral", "enterovirus"] },
  { code: "A86", displayName: "Unspecified viral encephalitis", category: "Infectious", searchTerms: ["encefalitis"] },
  { code: "A87", displayName: "Viral meningitis", category: "Infectious", searchTerms: ["meningitis viral"] },
  { code: "A90", displayName: "Dengue fever", category: "Infectious", searchTerms: ["dengue", "fiebre del dengue"] },
  { code: "A91", displayName: "Dengue hemorrhagic fever", category: "Infectious", searchTerms: ["dengue hemorrágico", "dengue grave"] },
  { code: "A92", displayName: "Other mosquito-borne viral fevers", category: "Infectious", searchTerms: ["Chikungunya", "Zika", "fiebre amarilla"] },
  { code: "A93", displayName: "Other arthropod-borne viral fevers", category: "Infectious", searchTerms: ["fiebre del Valle del Rift", "fiebre por flebótomos"] },
  { code: "A95", displayName: "Yellow fever", category: "Infectious", searchTerms: ["fiebre amarilla"] },
  { code: "A96", displayName: "Arenaviral hemorrhagic fever", category: "Infectious", searchTerms: ["fiebre de Lassa", "arenavirus"] },
  { code: "A98", displayName: "Other viral hemorrhagic fevers", category: "Infectious", searchTerms: ["Ebola", "Marburg", "fiebre hemorrágica"] },
  { code: "A99", displayName: "Unspecified viral hemorrhagic fever", category: "Infectious", searchTerms: ["fiebre hemorrágica viral", "VHF"] },
  { code: "B00", displayName: "Herpesviral infections", category: "Infectious", searchTerms: ["herpes simple", "HSV-1", "HSV-2", "herpes labial"] },
  { code: "B01", displayName: "Varicella", category: "Infectious", searchTerms: ["varicela", "chickenpox"] },
  { code: "B02", displayName: "Zoster", category: "Infectious", searchTerms: ["herpes zoster", "culebrilla", "shingles"] },
  { code: "B05", displayName: "Measles", category: "Infectious", searchTerms: ["sarampión"] },
  { code: "B06", displayName: "Rubella", category: "Infectious", searchTerms: ["rubeola", "sarampión alemán"] },
  { code: "B07", displayName: "Viral warts", category: "Infectious", searchTerms: ["verrugas virales", "VPH", "verruga vulgar"] },
  { code: "B08", displayName: "Other viral infections with skin lesions", category: "Infectious", searchTerms: ["Molluscum contagiosum", "enfermedad mano-pie-boca"] },
  { code: "B09", displayName: "Unspecified viral infection with skin lesions", category: "Infectious", searchTerms: ["exantema viral"] },
  { code: "B15", displayName: "Acute hepatitis A", category: "Infectious", searchTerms: ["hepatitis A", "VHA"] },
  { code: "B16", displayName: "Acute hepatitis B", category: "Infectious", searchTerms: ["hepatitis B", "VHB"] },
  { code: "B17", displayName: "Other acute viral hepatitis", category: "Infectious", searchTerms: ["hepatitis C", "VHC", "hepatitis E", "hepatitis D"] },
  { code: "B18", displayName: "Chronic viral hepatitis", category: "Infectious", searchTerms: ["hepatitis B crónica", "hepatitis C crónica"] },
  { code: "B19", displayName: "Unspecified viral hepatitis", category: "Infectious", searchTerms: ["hepatitis viral"] },
  { code: "B20", displayName: "HIV disease resulting in infectious diseases", category: "Infectious", searchTerms: ["VIH", "SIDA", "HIV"] },
  { code: "B21", displayName: "HIV disease resulting in malignant neoplasms", category: "Infectious", searchTerms: ["VIH cáncer", "HIV neoplasm"] },
  { code: "B22", displayName: "HIV disease resulting in other specified diseases", category: "Infectious", searchTerms: ["VIH wasting", "HIV encephalopathy"] },
  { code: "B23", displayName: "HIV disease resulting in other conditions", category: "Infectious", searchTerms: ["VIH linfadenopatía"] },
  { code: "B24", displayName: "Unspecified HIV disease", category: "Infectious", searchTerms: ["VIH sin especificar"] },
  { code: "B25", displayName: "Cytomegaloviral disease", category: "Infectious", searchTerms: ["citomegalovirus", "CMV"] },
  { code: "B26", displayName: "Mumps", category: "Infectious", searchTerms: ["paperas", "parotiditis"] },
  { code: "B27", displayName: "Infectious mononucleosis", category: "Infectious", searchTerms: ["mononucleosis", "Epstein-Barr", "EBV"] },
  { code: "B30", displayName: "Viral conjunctivitis", category: "Infectious", searchTerms: ["conjuntivitis viral"] },
  { code: "B33", displayName: "Other viral diseases", category: "Infectious", searchTerms: ["Kawasaki", "COVID-19", "SARS-CoV-2"] },
  { code: "B34", displayName: "Viral infection of unspecified site", category: "Infectious", searchTerms: ["virosis"] },
  { code: "B35", displayName: "Dermatophytosis", category: "Infectious", searchTerms: ["tiña", "dermatofitosis", "micosis cutánea"] },
  { code: "B36", displayName: "Other superficial mycoses", category: "Infectious", searchTerms: ["pitiriasis versicolor", "candidiasis cutánea"] },
  { code: "B37", displayName: "Candidiasis", category: "Infectious", searchTerms: ["candidiasis", "Candida albicans", "candidiasis vaginal"] },
  { code: "B38", displayName: "Coccidioidomycosis", category: "Infectious", searchTerms: ["coccidioidomicosis", "fiebre del valle"] },
  { code: "B39", displayName: "Histoplasmosis", category: "Infectious", searchTerms: ["histoplasmosis"] },
  { code: "B40", displayName: "Blastomycosis", category: "Infectious", searchTerms: ["blastomicosis"] },
  { code: "B41", displayName: "Paracoccidioidomycosis", category: "Infectious", searchTerms: ["paracoccidioidomicosis"] },
  { code: "B42", displayName: "Sporotrichosis", category: "Infectious", searchTerms: ["esporotricosis"] },
  { code: "B44", displayName: "Aspergillosis", category: "Infectious", searchTerms: ["aspergilosis", "Aspergillus"] },
  { code: "B45", displayName: "Cryptococcosis", category: "Infectious", searchTerms: ["criptococosis", "Cryptococcus neoformans"] },
  { code: "B46", displayName: "Zygomycosis", category: "Infectious", searchTerms: ["mucormicosis"] },
  { code: "B47", displayName: "Mycetoma", category: "Infectious", searchTerms: ["micetoma", "pie de Madura"] },
  { code: "B48", displayName: "Other mycoses", category: "Infectious", searchTerms: ["micosis"] },
  { code: "B49", displayName: "Unspecified mycosis", category: "Infectious", searchTerms: ["micosis sin especificar"] },
  { code: "B50", displayName: "Plasmodium falciparum malaria", category: "Infectious", searchTerms: ["malaria", "paludismo", "Plasmodium falciparum"] },
  { code: "B51", displayName: "Plasmodium vivax malaria", category: "Infectious", searchTerms: ["malaria vivax"] },
  { code: "B52", displayName: "Plasmodium malariae malaria", category: "Infectious", searchTerms: ["malaria malariae"] },
  { code: "B53", displayName: "Other parasitologically confirmed malaria", category: "Infectious", searchTerms: ["malaria ovale"] },
  { code: "B54", displayName: "Unspecified malaria", category: "Infectious", searchTerms: ["malaria"] },
  { code: "B55", displayName: "Leishmaniasis", category: "Infectious", searchTerms: ["leishmaniasis", "Leishmania"] },
  { code: "B56", displayName: "Trypanosomiasis", category: "Infectious", searchTerms: ["tripanosomiasis", "enfermedad del sueño"] },
  { code: "B57", displayName: "Chagas disease", category: "Infectious", searchTerms: ["Chagas", "Trypanosoma cruzi"] },
  { code: "B58", displayName: "Toxoplasmosis", category: "Infectious", searchTerms: ["toxoplasmosis", "Toxoplasma gondii"] },
  { code: "B59", displayName: "Pneumocystosis", category: "Infectious", searchTerms: ["Pneumocystis jirovecii", "PCP", "neumocistosis"] },
  { code: "B60", displayName: "Other protozoal diseases", category: "Infectious", searchTerms: ["babesiosis", "protozoarios"] },
  { code: "B64", displayName: "Unspecified protozoal disease", category: "Infectious", searchTerms: ["enfermedad por protozoos"] },
  { code: "B65", displayName: "Schistosomiasis", category: "Infectious", searchTerms: ["esquistosomiasis", "bilharzia"] },
  { code: "B66", displayName: "Other fluke infections", category: "Infectious", searchTerms: ["fascioliasis", "clonorquiasis"] },
  { code: "B67", displayName: "Echinococcosis", category: "Infectious", searchTerms: ["hidatidosis", "equinococosis"] },
  { code: "B68", displayName: "Taeniasis", category: "Infectious", searchTerms: ["teniasis", "solitaria"] },
  { code: "B69", displayName: "Cysticercosis", category: "Infectious", searchTerms: ["cisticercosis", "neurocisticercosis"] },
  { code: "B70", displayName: "Diphyllobothriasis", category: "Infectious", searchTerms: ["difilobotriasis"] },
  { code: "B71", displayName: "Other cestode infections", category: "Infectious", searchTerms: ["cestodiasis"] },
  { code: "B72", displayName: "Dracunculiasis", category: "Infectious", searchTerms: ["dracunculosis", "gusano de Guinea"] },
  { code: "B73", displayName: "Onchocerciasis", category: "Infectious", searchTerms: ["oncocercosis", "ceguera de los ríos"] },
  { code: "B74", displayName: "Filariasis", category: "Infectious", searchTerms: ["filariasis", "elefantiasis"] },
  { code: "B75", displayName: "Trichinellosis", category: "Infectious", searchTerms: ["triquinosis", "Trichinella spiralis"] },
  { code: "B76", displayName: "Hookworm diseases", category: "Infectious", searchTerms: ["anquilostomiasis", "uncinariasis"] },
  { code: "B77", displayName: "Ascariasis", category: "Infectious", searchTerms: ["ascariasis", "Ascaris lumbricoides"] },
  { code: "B78", displayName: "Strongyloidiasis", category: "Infectious", searchTerms: ["estrongiloidiasis"] },
  { code: "B79", displayName: "Trichuriasis", category: "Infectious", searchTerms: ["tricuriasis"] },
  { code: "B80", displayName: "Enterobiasis", category: "Infectious", searchTerms: ["enterobiasis", "oxiuros", "oxiuriasis"] },
  { code: "B81", displayName: "Other intestinal helminthiases", category: "Infectious", searchTerms: ["helmintiasis intestinal"] },
  { code: "B82", displayName: "Unspecified intestinal parasitism", category: "Infectious", searchTerms: ["parasitosis intestinal"] },
  { code: "B83", displayName: "Other helminthiases", category: "Infectious", searchTerms: ["helmintiasis"] },
  { code: "B85", displayName: "Pediculosis", category: "Infectious", searchTerms: ["piojos", "pediculosis", "liendres"] },
  { code: "B86", displayName: "Scabies", category: "Infectious", searchTerms: ["sarna", "escabiosis", "Sarcoptes scabiei"] },
  { code: "B87", displayName: "Myiasis", category: "Infectious", searchTerms: ["miasis", "gusanos en piel"] },
  { code: "B88", displayName: "Other infestations", category: "Infectious", searchTerms: ["tungiasis", "pulgas"] },
  { code: "B89", displayName: "Unspecified parasitic disease", category: "Infectious", searchTerms: ["parasitosis"] },
  { code: "B90", displayName: "Sequelae of tuberculosis", category: "Infectious", searchTerms: ["secuelas TB"] },
  { code: "B95", displayName: "Streptococcus as cause of disease", category: "Infectious", searchTerms: ["Streptococcus", "S. pyogenes", "S. pneumoniae"] },
  { code: "B96", displayName: "Other bacterial agents as cause", category: "Infectious", searchTerms: ["E. coli", "Pseudomonas", "Klebsiella", "Staphylococcus"] },
  { code: "B97", displayName: "Viral agents as cause of disease", category: "Infectious", searchTerms: ["VRS", "adenovirus", "rinovirus"] },
  { code: "B99", displayName: "Other infectious diseases", category: "Infectious", searchTerms: ["enfermedad infecciosa", "infección"] },
];

// Chapter C00-D48: Neoplasms
const neoplasms = [
  { code: "C00", displayName: "Malignant neoplasm of lip", category: "Neoplasms", searchTerms: ["cáncer de labio"] },
  { code: "C01", displayName: "Malignant neoplasm of base of tongue", category: "Neoplasms", searchTerms: ["cáncer de lengua"] },
  { code: "C02", displayName: "Malignant neoplasm of other parts of tongue", category: "Neoplasms", searchTerms: ["cáncer lingual"] },
  { code: "C03", displayName: "Malignant neoplasm of gum", category: "Neoplasms", searchTerms: ["cáncer de encía"] },
  { code: "C04", displayName: "Malignant neoplasm of floor of mouth", category: "Neoplasms", searchTerms: ["cáncer de piso de boca"] },
  { code: "C05", displayName: "Malignant neoplasm of palate", category: "Neoplasms", searchTerms: ["cáncer de paladar"] },
  { code: "C06", displayName: "Malignant neoplasm of other mouth parts", category: "Neoplasms", searchTerms: ["cáncer oral"] },
  { code: "C07", displayName: "Malignant neoplasm of parotid gland", category: "Neoplasms", searchTerms: ["cáncer de parótida"] },
  { code: "C08", displayName: "Malignant neoplasm of salivary glands", category: "Neoplasms", searchTerms: ["cáncer de glándula salival"] },
  { code: "C09", displayName: "Malignant neoplasm of tonsil", category: "Neoplasms", searchTerms: ["cáncer de amígdala"] },
  { code: "C10", displayName: "Malignant neoplasm of oropharynx", category: "Neoplasms", searchTerms: ["cáncer de orofaringe"] },
  { code: "C11", displayName: "Malignant neoplasm of nasopharynx", category: "Neoplasms", searchTerms: ["cáncer de nasofaringe"] },
  { code: "C12", displayName: "Malignant neoplasm of pyriform sinus", category: "Neoplasms", searchTerms: ["cáncer de seno piriforme"] },
  { code: "C13", displayName: "Malignant neoplasm of hypopharynx", category: "Neoplasms", searchTerms: ["cáncer de hipofaringe"] },
  { code: "C14", displayName: "Malignant neoplasm of lip/oral cavity/pharynx", category: "Neoplasms", searchTerms: ["cáncer oral y faríngeo"] },
  { code: "C15", displayName: "Malignant neoplasm of esophagus", category: "Neoplasms", searchTerms: ["cáncer de esófago"] },
  { code: "C16", displayName: "Malignant neoplasm of stomach", category: "Neoplasms", searchTerms: ["cáncer de estómago", "adenocarcinoma gástrico"] },
  { code: "C17", displayName: "Malignant neoplasm of small intestine", category: "Neoplasms", searchTerms: ["cáncer de intestino delgado"] },
  { code: "C18", displayName: "Malignant neoplasm of colon", category: "Neoplasms", searchTerms: ["cáncer de colon", "cáncer colorrectal"] },
  { code: "C19", displayName: "Malignant neoplasm of rectosigmoid junction", category: "Neoplasms", searchTerms: ["cáncer rectosigmoideo"] },
  { code: "C20", displayName: "Malignant neoplasm of rectum", category: "Neoplasms", searchTerms: ["cáncer de recto"] },
  { code: "C21", displayName: "Malignant neoplasm of anus and anal canal", category: "Neoplasms", searchTerms: ["cáncer de ano"] },
  { code: "C22", displayName: "Malignant neoplasm of liver", category: "Neoplasms", searchTerms: ["cáncer de hígado", "carcinoma hepatocelular", "CHC"] },
  { code: "C23", displayName: "Malignant neoplasm of gallbladder", category: "Neoplasms", searchTerms: ["cáncer de vesícula biliar"] },
  { code: "C24", displayName: "Malignant neoplasm of biliary tract", category: "Neoplasms", searchTerms: ["cáncer de vías biliares", "colangiocarcinoma"] },
  { code: "C25", displayName: "Malignant neoplasm of pancreas", category: "Neoplasms", searchTerms: ["cáncer de páncreas", "adenocarcinoma pancreático"] },
  { code: "C30", displayName: "Malignant neoplasm of nasal cavity", category: "Neoplasms", searchTerms: ["cáncer de cavidad nasal"] },
  { code: "C31", displayName: "Malignant neoplasm of accessory sinuses", category: "Neoplasms", searchTerms: ["cáncer de senos paranasales"] },
  { code: "C32", displayName: "Malignant neoplasm of larynx", category: "Neoplasms", searchTerms: ["cáncer de laringe"] },
  { code: "C33", displayName: "Malignant neoplasm of trachea", category: "Neoplasms", searchTerms: ["cáncer de tráquea"] },
  { code: "C34", displayName: "Malignant neoplasm of bronchus and lung", category: "Neoplasms", searchTerms: ["cáncer de pulmón", "CPCNP", "CPCP"] },
  { code: "C37", displayName: "Malignant neoplasm of thymus", category: "Neoplasms", searchTerms: ["cáncer de timo", "timoma"] },
  { code: "C38", displayName: "Malignant neoplasm of heart/mediastinum", category: "Neoplasms", searchTerms: ["cáncer de mediastino"] },
  { code: "C40", displayName: "Malignant neoplasm of bone and cartilage of limbs", category: "Neoplasms", searchTerms: ["osteosarcoma", "sarcoma óseo"] },
  { code: "C41", displayName: "Malignant neoplasm of bone and cartilage NEC", category: "Neoplasms", searchTerms: ["sarcoma de Ewing", "condrosarcoma"] },
  { code: "C43", displayName: "Malignant melanoma of skin", category: "Neoplasms", searchTerms: ["melanoma", "cáncer de piel melanoma"] },
  { code: "C44", displayName: "Other malignant neoplasms of skin", category: "Neoplasms", searchTerms: ["carcinoma basocelular", "carcinoma escamocelular", "cáncer de piel no melanoma"] },
  { code: "C45", displayName: "Mesothelioma", category: "Neoplasms", searchTerms: ["mesotelioma"] },
  { code: "C46", displayName: "Kaposi sarcoma", category: "Neoplasms", searchTerms: ["sarcoma de Kaposi", "Kaposi"] },
  { code: "C47", displayName: "Malignant neoplasm of peripheral nerves", category: "Neoplasms", searchTerms: ["tumor de vaina nerviosa"] },
  { code: "C48", displayName: "Malignant neoplasm of peritoneum", category: "Neoplasms", searchTerms: ["cáncer de peritoneo"] },
  { code: "C49", displayName: "Malignant neoplasm of connective tissue", category: "Neoplasms", searchTerms: ["sarcoma de partes blandas"] },
  { code: "C50", displayName: "Malignant neoplasm of breast", category: "Neoplasms", searchTerms: ["cáncer de mama", "cáncer de seno"] },
  { code: "C51", displayName: "Malignant neoplasm of vulva", category: "Neoplasms", searchTerms: ["cáncer de vulva"] },
  { code: "